# Auto-generated by tools/build.sh. Safe to overwrite.
BUILD_VERSION = 143
BUILD_TS = "2026-08-04T07:40:51Z"
GIT_COMMIT = "35d17c6"

def build_info(component: str) -> dict:
    return {
        "component": component,
        "build_version": BUILD_VERSION,
        "build_ts": BUILD_TS,
        "git_commit": GIT_COMMIT,
    }
