# Auto-generated by tools/build.sh. Safe to overwrite.
BUILD_VERSION = 118
BUILD_TS = "2026-07-10T15:44:29Z"
GIT_COMMIT = "19d70ec"

def build_info(component: str) -> dict:
    return {
        "component": component,
        "build_version": BUILD_VERSION,
        "build_ts": BUILD_TS,
        "git_commit": GIT_COMMIT,
    }
