# Auto-generated by tools/build.sh. Safe to overwrite.
BUILD_VERSION = 199
BUILD_TS = "2026-09-06T01:36:30Z"
GIT_COMMIT = "235a3c5"

def build_info(component: str) -> dict:
    return {
        "component": component,
        "build_version": BUILD_VERSION,
        "build_ts": BUILD_TS,
        "git_commit": GIT_COMMIT,
    }
