# Auto-generated by tools/build.sh. Safe to overwrite.
BUILD_VERSION = 125
BUILD_TS = "2026-07-11T14:38:29Z"
GIT_COMMIT = "f3b250e"

def build_info(component: str) -> dict:
    return {
        "component": component,
        "build_version": BUILD_VERSION,
        "build_ts": BUILD_TS,
        "git_commit": GIT_COMMIT,
    }
