// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: agent_jobs.sql

package dbq

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const cancelQueuedAgentJob = `-- name: CancelQueuedAgentJob :one
UPDATE agent_jobs
SET status = 'cancelled',
    cancel_requested_at = now(),
    cancelled_by_user_id = $1,
    completed_at = now(),
    updated_at = now(),
    state_version = state_version + 1
WHERE id = $2 AND agent_id = $3 AND status = 'queued'
RETURNING id, agent_id, handler_name, handler_version, input_schema_hash, output_schema_hash, source_run_id, cron_id, cron_slug, initiator_kind, initiator_user_id, initiator_conversation_id, initiator_access, status, timeout_ms, max_attempts, attempt_limit, attempt_count, next_attempt_at, scheduled_at, input_payload, output_payload, progress_phase, progress_message, progress_completed, progress_total, progress_attempt, progress_updated_at, last_error, cancel_requested_at, cancelled_by_user_id, started_at, completed_at, state_version, created_at, updated_at
`

type CancelQueuedAgentJobParams struct {
	CancelledByUserID pgtype.UUID `json:"cancelled_by_user_id"`
	ID                pgtype.UUID `json:"id"`
	AgentID           pgtype.UUID `json:"agent_id"`
}

func (q *Queries) CancelQueuedAgentJob(ctx context.Context, arg CancelQueuedAgentJobParams) (AgentJob, error) {
	row := q.db.QueryRow(ctx, cancelQueuedAgentJob, arg.CancelledByUserID, arg.ID, arg.AgentID)
	var i AgentJob
	err := row.Scan(
		&i.ID,
		&i.AgentID,
		&i.HandlerName,
		&i.HandlerVersion,
		&i.InputSchemaHash,
		&i.OutputSchemaHash,
		&i.SourceRunID,
		&i.CronID,
		&i.CronSlug,
		&i.InitiatorKind,
		&i.InitiatorUserID,
		&i.InitiatorConversationID,
		&i.InitiatorAccess,
		&i.Status,
		&i.TimeoutMs,
		&i.MaxAttempts,
		&i.AttemptLimit,
		&i.AttemptCount,
		&i.NextAttemptAt,
		&i.ScheduledAt,
		&i.InputPayload,
		&i.OutputPayload,
		&i.ProgressPhase,
		&i.ProgressMessage,
		&i.ProgressCompleted,
		&i.ProgressTotal,
		&i.ProgressAttempt,
		&i.ProgressUpdatedAt,
		&i.LastError,
		&i.CancelRequestedAt,
		&i.CancelledByUserID,
		&i.StartedAt,
		&i.CompletedAt,
		&i.StateVersion,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const cancelRunningAgentJob = `-- name: CancelRunningAgentJob :one
UPDATE agent_jobs
SET status = 'cancelled',
    cancel_requested_at = coalesce(cancel_requested_at, now()),
    cancelled_by_user_id = coalesce(cancelled_by_user_id, $1),
    completed_at = now(),
    updated_at = now(),
    state_version = state_version + 1
WHERE id = $2 AND status = 'running'
RETURNING id, agent_id, handler_name, handler_version, input_schema_hash, output_schema_hash, source_run_id, cron_id, cron_slug, initiator_kind, initiator_user_id, initiator_conversation_id, initiator_access, status, timeout_ms, max_attempts, attempt_limit, attempt_count, next_attempt_at, scheduled_at, input_payload, output_payload, progress_phase, progress_message, progress_completed, progress_total, progress_attempt, progress_updated_at, last_error, cancel_requested_at, cancelled_by_user_id, started_at, completed_at, state_version, created_at, updated_at
`

type CancelRunningAgentJobParams struct {
	CancelledByUserID pgtype.UUID `json:"cancelled_by_user_id"`
	ID                pgtype.UUID `json:"id"`
}

func (q *Queries) CancelRunningAgentJob(ctx context.Context, arg CancelRunningAgentJobParams) (AgentJob, error) {
	row := q.db.QueryRow(ctx, cancelRunningAgentJob, arg.CancelledByUserID, arg.ID)
	var i AgentJob
	err := row.Scan(
		&i.ID,
		&i.AgentID,
		&i.HandlerName,
		&i.HandlerVersion,
		&i.InputSchemaHash,
		&i.OutputSchemaHash,
		&i.SourceRunID,
		&i.CronID,
		&i.CronSlug,
		&i.InitiatorKind,
		&i.InitiatorUserID,
		&i.InitiatorConversationID,
		&i.InitiatorAccess,
		&i.Status,
		&i.TimeoutMs,
		&i.MaxAttempts,
		&i.AttemptLimit,
		&i.AttemptCount,
		&i.NextAttemptAt,
		&i.ScheduledAt,
		&i.InputPayload,
		&i.OutputPayload,
		&i.ProgressPhase,
		&i.ProgressMessage,
		&i.ProgressCompleted,
		&i.ProgressTotal,
		&i.ProgressAttempt,
		&i.ProgressUpdatedAt,
		&i.LastError,
		&i.CancelRequestedAt,
		&i.CancelledByUserID,
		&i.StartedAt,
		&i.CompletedAt,
		&i.StateVersion,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const candidateAgentJobContractMatches = `-- name: CandidateAgentJobContractMatches :one
SELECT EXISTS (
    SELECT 1
    FROM agent_build_job_handlers candidate
    JOIN agent_builds build ON build.id = candidate.build_id
    WHERE build.id = $1
      AND build.agent_id = $2
      AND build.job_manifest_extracted_at IS NOT NULL
      AND candidate.name = $3
      AND candidate.version = $4
      AND candidate.input_schema_hash = $5
      AND candidate.output_schema_hash = $6
)::boolean
`

type CandidateAgentJobContractMatchesParams struct {
	BuildID          pgtype.UUID `json:"build_id"`
	AgentID          pgtype.UUID `json:"agent_id"`
	HandlerName      string      `json:"handler_name"`
	HandlerVersion   int32       `json:"handler_version"`
	InputSchemaHash  string      `json:"input_schema_hash"`
	OutputSchemaHash string      `json:"output_schema_hash"`
}

func (q *Queries) CandidateAgentJobContractMatches(ctx context.Context, arg CandidateAgentJobContractMatchesParams) (bool, error) {
	row := q.db.QueryRow(ctx, candidateAgentJobContractMatches,
		arg.BuildID,
		arg.AgentID,
		arg.HandlerName,
		arg.HandlerVersion,
		arg.InputSchemaHash,
		arg.OutputSchemaHash,
	)
	var column_1 bool
	err := row.Scan(&column_1)
	return column_1, err
}

const claimDueAgentJob = `-- name: ClaimDueAgentJob :one
WITH candidate AS (
    SELECT j.id,
           j.agent_id,
           j.handler_name,
           j.handler_version,
           j.attempt_count + 1 AS attempt_number,
           h.agent_token_version AS runtime_generation
    FROM agent_jobs j
    JOIN agent_job_handlers h
      ON h.agent_id = j.agent_id
     AND h.name = j.handler_name
     AND h.version = j.handler_version
    JOIN agents a ON a.id = j.agent_id
    WHERE ($3::uuid IS NULL OR j.agent_id = $3)
      AND j.status IN ('queued', 'running')
      AND j.next_attempt_at <= now()
      AND j.cancel_requested_at IS NULL
      AND j.attempt_count < j.attempt_limit
      AND h.active = true
      AND h.agent_token_version = a.agent_token_version
      AND a.status = 'active'
      AND a.job_dispatch_paused_build_id IS NULL
      AND NOT EXISTS (
          SELECT 1 FROM agent_job_attempts active
          WHERE active.job_id = j.id AND active.status IN ('leased', 'running')
      )
      AND (
          SELECT count(*) FROM agent_job_attempts active
          WHERE active.status IN ('leased', 'running')
      ) < $4::bigint
      AND (
          SELECT count(*)
          FROM agent_job_attempts active
          JOIN agent_jobs active_job ON active_job.id = active.job_id
          WHERE active.status IN ('leased', 'running')
            AND active_job.agent_id = j.agent_id
      ) < $5::bigint
      AND (
          SELECT count(*)
          FROM agent_job_attempts active
          JOIN agent_jobs active_job ON active_job.id = active.job_id
          WHERE active.status IN ('leased', 'running')
            AND active_job.agent_id = j.agent_id
            AND active_job.handler_name = j.handler_name
            AND active_job.handler_version = j.handler_version
      ) < h.max_concurrency
    ORDER BY j.next_attempt_at, j.created_at, j.id
    FOR UPDATE OF j SKIP LOCKED
    LIMIT 1
), claimed AS (
    UPDATE agent_jobs j
    SET status = 'running',
        attempt_count = candidate.attempt_number,
        progress_phase = NULL,
        progress_message = NULL,
        progress_completed = NULL,
        progress_total = NULL,
        progress_attempt = NULL,
        progress_updated_at = NULL,
        started_at = coalesce(j.started_at, now()),
        updated_at = now(),
        state_version = state_version + 1
    FROM candidate
    WHERE j.id = candidate.id
    RETURNING j.id,
              candidate.attempt_number,
              candidate.runtime_generation
)
INSERT INTO agent_job_attempts (
    job_id, attempt_number, status, runtime_generation, lease_owner,
    lease_token, lease_expires_at, leased_at
)
SELECT claimed.id,
       claimed.attempt_number,
       'leased',
       claimed.runtime_generation,
       $1,
       gen_random_uuid(),
       now() + make_interval(secs => $2::integer),
       now()
FROM claimed
RETURNING job_id, attempt_number, status, runtime_generation, lease_owner, lease_token, lease_expires_at, run_id, error_kind, error_message, leased_at, started_at, completed_at, created_at, updated_at
`

type ClaimDueAgentJobParams struct {
	LeaseOwner   pgtype.UUID `json:"lease_owner"`
	LeaseSeconds int32       `json:"lease_seconds"`
	AgentID      pgtype.UUID `json:"agent_id"`
	GlobalLimit  int64       `json:"global_limit"`
	AgentLimit   int64       `json:"agent_limit"`
}

func (q *Queries) ClaimDueAgentJob(ctx context.Context, arg ClaimDueAgentJobParams) (AgentJobAttempt, error) {
	row := q.db.QueryRow(ctx, claimDueAgentJob,
		arg.LeaseOwner,
		arg.LeaseSeconds,
		arg.AgentID,
		arg.GlobalLimit,
		arg.AgentLimit,
	)
	var i AgentJobAttempt
	err := row.Scan(
		&i.JobID,
		&i.AttemptNumber,
		&i.Status,
		&i.RuntimeGeneration,
		&i.LeaseOwner,
		&i.LeaseToken,
		&i.LeaseExpiresAt,
		&i.RunID,
		&i.ErrorKind,
		&i.ErrorMessage,
		&i.LeasedAt,
		&i.StartedAt,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const failAgentJob = `-- name: FailAgentJob :execrows
UPDATE agent_jobs
SET status = 'failed',
    output_payload = NULL,
    last_error = $1,
    completed_at = now(),
    updated_at = now(),
    state_version = state_version + 1
WHERE id = $2 AND status = 'running' AND cancel_requested_at IS NULL
`

type FailAgentJobParams struct {
	LastError pgtype.Text `json:"last_error"`
	ID        pgtype.UUID `json:"id"`
}

func (q *Queries) FailAgentJob(ctx context.Context, arg FailAgentJobParams) (int64, error) {
	result, err := q.db.Exec(ctx, failAgentJob, arg.LastError, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const failAgentJobAttempt = `-- name: FailAgentJobAttempt :execrows
UPDATE agent_job_attempts
SET status = 'failed',
    error_kind = $1,
    error_message = $2,
    completed_at = now(),
    updated_at = now()
WHERE job_id = $3
  AND attempt_number = $4
  AND lease_owner = $5
  AND lease_token = $6
  AND status IN ('leased', 'running')
  AND lease_expires_at > now()
`

type FailAgentJobAttemptParams struct {
	ErrorKind     pgtype.Text `json:"error_kind"`
	ErrorMessage  pgtype.Text `json:"error_message"`
	JobID         pgtype.UUID `json:"job_id"`
	AttemptNumber int32       `json:"attempt_number"`
	LeaseOwner    pgtype.UUID `json:"lease_owner"`
	LeaseToken    pgtype.UUID `json:"lease_token"`
}

func (q *Queries) FailAgentJobAttempt(ctx context.Context, arg FailAgentJobAttemptParams) (int64, error) {
	result, err := q.db.Exec(ctx, failAgentJobAttempt,
		arg.ErrorKind,
		arg.ErrorMessage,
		arg.JobID,
		arg.AttemptNumber,
		arg.LeaseOwner,
		arg.LeaseToken,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const forceInterruptAgentJobAttemptForDeployment = `-- name: ForceInterruptAgentJobAttemptForDeployment :one
WITH deployment AS MATERIALIZED (
    SELECT agent.id
    FROM agents agent
    JOIN agent_builds build ON build.id = agent.job_dispatch_paused_build_id
    WHERE agent.id = $2
      AND build.id = $3
      AND build.agent_id = agent.id
      AND build.deployment_token = $4
    FOR UPDATE OF agent
), locked_job AS MATERIALIZED (
    SELECT job.id, job.cancel_requested_at
    FROM agent_jobs job, deployment
    WHERE job.id = $5
      AND job.agent_id = deployment.id
      AND job.status = 'running'
    FOR UPDATE OF job
), interrupted AS (
    UPDATE agent_job_attempts attempt
    SET status = 'interrupted',
        error_kind = 'deployment',
        error_message = $1,
        completed_at = now(),
        updated_at = now()
    FROM locked_job
    WHERE attempt.job_id = $5
      AND attempt.attempt_number = $6
      AND attempt.lease_token = $7
      AND attempt.status IN ('leased', 'running')
      AND locked_job.id = attempt.job_id
    RETURNING attempt.job_id, attempt.run_id, locked_job.cancel_requested_at
), failed_run AS (
    UPDATE runs run
    SET status = CASE WHEN interrupted.cancel_requested_at IS NOT NULL THEN 'cancelled' ELSE 'error' END,
        error_kind = CASE WHEN interrupted.cancel_requested_at IS NOT NULL THEN '' ELSE 'platform' END,
        error_message = CASE WHEN interrupted.cancel_requested_at IS NOT NULL THEN 'cancelled by user' ELSE $1 END,
        finished_at = now(),
        duration_ms = (EXTRACT(EPOCH FROM (now() - run.started_at)) * 1000)::integer
    FROM interrupted
    WHERE interrupted.run_id IS NOT NULL
      AND run.id = interrupted.run_id
      AND run.status = 'running'
    RETURNING run.id
)
UPDATE agent_jobs job
SET status = CASE WHEN job.cancel_requested_at IS NOT NULL THEN 'cancelled' ELSE job.status END,
    attempt_limit = CASE WHEN job.cancel_requested_at IS NOT NULL THEN job.attempt_limit ELSE job.attempt_limit + 1 END,
    last_error = $1,
    next_attempt_at = now(),
    completed_at = CASE WHEN job.cancel_requested_at IS NOT NULL THEN now() ELSE job.completed_at END,
    updated_at = now(),
    state_version = state_version + 1
FROM interrupted
WHERE job.id = interrupted.job_id
RETURNING job.id, job.agent_id, job.handler_name, job.handler_version, job.input_schema_hash, job.output_schema_hash, job.source_run_id, job.cron_id, job.cron_slug, job.initiator_kind, job.initiator_user_id, job.initiator_conversation_id, job.initiator_access, job.status, job.timeout_ms, job.max_attempts, job.attempt_limit, job.attempt_count, job.next_attempt_at, job.scheduled_at, job.input_payload, job.output_payload, job.progress_phase, job.progress_message, job.progress_completed, job.progress_total, job.progress_attempt, job.progress_updated_at, job.last_error, job.cancel_requested_at, job.cancelled_by_user_id, job.started_at, job.completed_at, job.state_version, job.created_at, job.updated_at
`

type ForceInterruptAgentJobAttemptForDeploymentParams struct {
	ErrorMessage    pgtype.Text `json:"error_message"`
	AgentID         pgtype.UUID `json:"agent_id"`
	BuildID         pgtype.UUID `json:"build_id"`
	DeploymentToken pgtype.UUID `json:"deployment_token"`
	JobID           pgtype.UUID `json:"job_id"`
	AttemptNumber   int32       `json:"attempt_number"`
	LeaseToken      pgtype.UUID `json:"lease_token"`
}

func (q *Queries) ForceInterruptAgentJobAttemptForDeployment(ctx context.Context, arg ForceInterruptAgentJobAttemptForDeploymentParams) (AgentJob, error) {
	row := q.db.QueryRow(ctx, forceInterruptAgentJobAttemptForDeployment,
		arg.ErrorMessage,
		arg.AgentID,
		arg.BuildID,
		arg.DeploymentToken,
		arg.JobID,
		arg.AttemptNumber,
		arg.LeaseToken,
	)
	var i AgentJob
	err := row.Scan(
		&i.ID,
		&i.AgentID,
		&i.HandlerName,
		&i.HandlerVersion,
		&i.InputSchemaHash,
		&i.OutputSchemaHash,
		&i.SourceRunID,
		&i.CronID,
		&i.CronSlug,
		&i.InitiatorKind,
		&i.InitiatorUserID,
		&i.InitiatorConversationID,
		&i.InitiatorAccess,
		&i.Status,
		&i.TimeoutMs,
		&i.MaxAttempts,
		&i.AttemptLimit,
		&i.AttemptCount,
		&i.NextAttemptAt,
		&i.ScheduledAt,
		&i.InputPayload,
		&i.OutputPayload,
		&i.ProgressPhase,
		&i.ProgressMessage,
		&i.ProgressCompleted,
		&i.ProgressTotal,
		&i.ProgressAttempt,
		&i.ProgressUpdatedAt,
		&i.LastError,
		&i.CancelRequestedAt,
		&i.CancelledByUserID,
		&i.StartedAt,
		&i.CompletedAt,
		&i.StateVersion,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAgentJobByAttemptRunID = `-- name: GetAgentJobByAttemptRunID :one
SELECT j.id, j.agent_id, j.handler_name, j.handler_version, j.input_schema_hash, j.output_schema_hash, j.source_run_id, j.cron_id, j.cron_slug, j.initiator_kind, j.initiator_user_id, j.initiator_conversation_id, j.initiator_access, j.status, j.timeout_ms, j.max_attempts, j.attempt_limit, j.attempt_count, j.next_attempt_at, j.scheduled_at, j.input_payload, j.output_payload, j.progress_phase, j.progress_message, j.progress_completed, j.progress_total, j.progress_attempt, j.progress_updated_at, j.last_error, j.cancel_requested_at, j.cancelled_by_user_id, j.started_at, j.completed_at, j.state_version, j.created_at, j.updated_at
FROM agent_jobs j
JOIN agent_job_attempts a ON a.job_id = j.id
WHERE a.run_id = $1
`

func (q *Queries) GetAgentJobByAttemptRunID(ctx context.Context, runID pgtype.UUID) (AgentJob, error) {
	row := q.db.QueryRow(ctx, getAgentJobByAttemptRunID, runID)
	var i AgentJob
	err := row.Scan(
		&i.ID,
		&i.AgentID,
		&i.HandlerName,
		&i.HandlerVersion,
		&i.InputSchemaHash,
		&i.OutputSchemaHash,
		&i.SourceRunID,
		&i.CronID,
		&i.CronSlug,
		&i.InitiatorKind,
		&i.InitiatorUserID,
		&i.InitiatorConversationID,
		&i.InitiatorAccess,
		&i.Status,
		&i.TimeoutMs,
		&i.MaxAttempts,
		&i.AttemptLimit,
		&i.AttemptCount,
		&i.NextAttemptAt,
		&i.ScheduledAt,
		&i.InputPayload,
		&i.OutputPayload,
		&i.ProgressPhase,
		&i.ProgressMessage,
		&i.ProgressCompleted,
		&i.ProgressTotal,
		&i.ProgressAttempt,
		&i.ProgressUpdatedAt,
		&i.LastError,
		&i.CancelRequestedAt,
		&i.CancelledByUserID,
		&i.StartedAt,
		&i.CompletedAt,
		&i.StateVersion,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAgentJobByID = `-- name: GetAgentJobByID :one
SELECT id, agent_id, handler_name, handler_version, input_schema_hash, output_schema_hash, source_run_id, cron_id, cron_slug, initiator_kind, initiator_user_id, initiator_conversation_id, initiator_access, status, timeout_ms, max_attempts, attempt_limit, attempt_count, next_attempt_at, scheduled_at, input_payload, output_payload, progress_phase, progress_message, progress_completed, progress_total, progress_attempt, progress_updated_at, last_error, cancel_requested_at, cancelled_by_user_id, started_at, completed_at, state_version, created_at, updated_at FROM agent_jobs WHERE id = $1
`

func (q *Queries) GetAgentJobByID(ctx context.Context, id pgtype.UUID) (AgentJob, error) {
	row := q.db.QueryRow(ctx, getAgentJobByID, id)
	var i AgentJob
	err := row.Scan(
		&i.ID,
		&i.AgentID,
		&i.HandlerName,
		&i.HandlerVersion,
		&i.InputSchemaHash,
		&i.OutputSchemaHash,
		&i.SourceRunID,
		&i.CronID,
		&i.CronSlug,
		&i.InitiatorKind,
		&i.InitiatorUserID,
		&i.InitiatorConversationID,
		&i.InitiatorAccess,
		&i.Status,
		&i.TimeoutMs,
		&i.MaxAttempts,
		&i.AttemptLimit,
		&i.AttemptCount,
		&i.NextAttemptAt,
		&i.ScheduledAt,
		&i.InputPayload,
		&i.OutputPayload,
		&i.ProgressPhase,
		&i.ProgressMessage,
		&i.ProgressCompleted,
		&i.ProgressTotal,
		&i.ProgressAttempt,
		&i.ProgressUpdatedAt,
		&i.LastError,
		&i.CancelRequestedAt,
		&i.CancelledByUserID,
		&i.StartedAt,
		&i.CompletedAt,
		&i.StateVersion,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAgentJobByIDAndAgent = `-- name: GetAgentJobByIDAndAgent :one
SELECT id, agent_id, handler_name, handler_version, input_schema_hash, output_schema_hash, source_run_id, cron_id, cron_slug, initiator_kind, initiator_user_id, initiator_conversation_id, initiator_access, status, timeout_ms, max_attempts, attempt_limit, attempt_count, next_attempt_at, scheduled_at, input_payload, output_payload, progress_phase, progress_message, progress_completed, progress_total, progress_attempt, progress_updated_at, last_error, cancel_requested_at, cancelled_by_user_id, started_at, completed_at, state_version, created_at, updated_at FROM agent_jobs WHERE id = $1 AND agent_id = $2
`

type GetAgentJobByIDAndAgentParams struct {
	ID      pgtype.UUID `json:"id"`
	AgentID pgtype.UUID `json:"agent_id"`
}

func (q *Queries) GetAgentJobByIDAndAgent(ctx context.Context, arg GetAgentJobByIDAndAgentParams) (AgentJob, error) {
	row := q.db.QueryRow(ctx, getAgentJobByIDAndAgent, arg.ID, arg.AgentID)
	var i AgentJob
	err := row.Scan(
		&i.ID,
		&i.AgentID,
		&i.HandlerName,
		&i.HandlerVersion,
		&i.InputSchemaHash,
		&i.OutputSchemaHash,
		&i.SourceRunID,
		&i.CronID,
		&i.CronSlug,
		&i.InitiatorKind,
		&i.InitiatorUserID,
		&i.InitiatorConversationID,
		&i.InitiatorAccess,
		&i.Status,
		&i.TimeoutMs,
		&i.MaxAttempts,
		&i.AttemptLimit,
		&i.AttemptCount,
		&i.NextAttemptAt,
		&i.ScheduledAt,
		&i.InputPayload,
		&i.OutputPayload,
		&i.ProgressPhase,
		&i.ProgressMessage,
		&i.ProgressCompleted,
		&i.ProgressTotal,
		&i.ProgressAttempt,
		&i.ProgressUpdatedAt,
		&i.LastError,
		&i.CancelRequestedAt,
		&i.CancelledByUserID,
		&i.StartedAt,
		&i.CompletedAt,
		&i.StateVersion,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAgentJobByIDAndAgentForUpdate = `-- name: GetAgentJobByIDAndAgentForUpdate :one
SELECT id, agent_id, handler_name, handler_version, input_schema_hash, output_schema_hash, source_run_id, cron_id, cron_slug, initiator_kind, initiator_user_id, initiator_conversation_id, initiator_access, status, timeout_ms, max_attempts, attempt_limit, attempt_count, next_attempt_at, scheduled_at, input_payload, output_payload, progress_phase, progress_message, progress_completed, progress_total, progress_attempt, progress_updated_at, last_error, cancel_requested_at, cancelled_by_user_id, started_at, completed_at, state_version, created_at, updated_at FROM agent_jobs WHERE id = $1 AND agent_id = $2 FOR UPDATE
`

type GetAgentJobByIDAndAgentForUpdateParams struct {
	ID      pgtype.UUID `json:"id"`
	AgentID pgtype.UUID `json:"agent_id"`
}

func (q *Queries) GetAgentJobByIDAndAgentForUpdate(ctx context.Context, arg GetAgentJobByIDAndAgentForUpdateParams) (AgentJob, error) {
	row := q.db.QueryRow(ctx, getAgentJobByIDAndAgentForUpdate, arg.ID, arg.AgentID)
	var i AgentJob
	err := row.Scan(
		&i.ID,
		&i.AgentID,
		&i.HandlerName,
		&i.HandlerVersion,
		&i.InputSchemaHash,
		&i.OutputSchemaHash,
		&i.SourceRunID,
		&i.CronID,
		&i.CronSlug,
		&i.InitiatorKind,
		&i.InitiatorUserID,
		&i.InitiatorConversationID,
		&i.InitiatorAccess,
		&i.Status,
		&i.TimeoutMs,
		&i.MaxAttempts,
		&i.AttemptLimit,
		&i.AttemptCount,
		&i.NextAttemptAt,
		&i.ScheduledAt,
		&i.InputPayload,
		&i.OutputPayload,
		&i.ProgressPhase,
		&i.ProgressMessage,
		&i.ProgressCompleted,
		&i.ProgressTotal,
		&i.ProgressAttempt,
		&i.ProgressUpdatedAt,
		&i.LastError,
		&i.CancelRequestedAt,
		&i.CancelledByUserID,
		&i.StartedAt,
		&i.CompletedAt,
		&i.StateVersion,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAgentJobByIDForUpdate = `-- name: GetAgentJobByIDForUpdate :one
SELECT id, agent_id, handler_name, handler_version, input_schema_hash, output_schema_hash, source_run_id, cron_id, cron_slug, initiator_kind, initiator_user_id, initiator_conversation_id, initiator_access, status, timeout_ms, max_attempts, attempt_limit, attempt_count, next_attempt_at, scheduled_at, input_payload, output_payload, progress_phase, progress_message, progress_completed, progress_total, progress_attempt, progress_updated_at, last_error, cancel_requested_at, cancelled_by_user_id, started_at, completed_at, state_version, created_at, updated_at FROM agent_jobs WHERE id = $1 FOR UPDATE
`

func (q *Queries) GetAgentJobByIDForUpdate(ctx context.Context, id pgtype.UUID) (AgentJob, error) {
	row := q.db.QueryRow(ctx, getAgentJobByIDForUpdate, id)
	var i AgentJob
	err := row.Scan(
		&i.ID,
		&i.AgentID,
		&i.HandlerName,
		&i.HandlerVersion,
		&i.InputSchemaHash,
		&i.OutputSchemaHash,
		&i.SourceRunID,
		&i.CronID,
		&i.CronSlug,
		&i.InitiatorKind,
		&i.InitiatorUserID,
		&i.InitiatorConversationID,
		&i.InitiatorAccess,
		&i.Status,
		&i.TimeoutMs,
		&i.MaxAttempts,
		&i.AttemptLimit,
		&i.AttemptCount,
		&i.NextAttemptAt,
		&i.ScheduledAt,
		&i.InputPayload,
		&i.OutputPayload,
		&i.ProgressPhase,
		&i.ProgressMessage,
		&i.ProgressCompleted,
		&i.ProgressTotal,
		&i.ProgressAttempt,
		&i.ProgressUpdatedAt,
		&i.LastError,
		&i.CancelRequestedAt,
		&i.CancelledByUserID,
		&i.StartedAt,
		&i.CompletedAt,
		&i.StateVersion,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAgentJobHandlerForEnqueue = `-- name: GetAgentJobHandlerForEnqueue :one
SELECT h.agent_id, h.name, h.version, h.description, h.timeout_ms, h.max_attempts, h.max_concurrency, h.input_schema, h.output_schema, h.input_schema_hash, h.output_schema_hash, h.agent_token_version, h.active, h.created_at, h.updated_at
FROM agent_job_handlers h
JOIN agents a ON a.id = h.agent_id
WHERE h.agent_id = $1
  AND h.name = $2
  AND h.version = $3
  AND h.active = true
  AND h.agent_token_version = a.agent_token_version
`

type GetAgentJobHandlerForEnqueueParams struct {
	AgentID        pgtype.UUID `json:"agent_id"`
	HandlerName    string      `json:"handler_name"`
	HandlerVersion int32       `json:"handler_version"`
}

func (q *Queries) GetAgentJobHandlerForEnqueue(ctx context.Context, arg GetAgentJobHandlerForEnqueueParams) (AgentJobHandler, error) {
	row := q.db.QueryRow(ctx, getAgentJobHandlerForEnqueue, arg.AgentID, arg.HandlerName, arg.HandlerVersion)
	var i AgentJobHandler
	err := row.Scan(
		&i.AgentID,
		&i.Name,
		&i.Version,
		&i.Description,
		&i.TimeoutMs,
		&i.MaxAttempts,
		&i.MaxConcurrency,
		&i.InputSchema,
		&i.OutputSchema,
		&i.InputSchemaHash,
		&i.OutputSchemaHash,
		&i.AgentTokenVersion,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getExpiredAgentJobAttemptForUpdate = `-- name: GetExpiredAgentJobAttemptForUpdate :one
SELECT attempt.job_id, attempt.attempt_number, attempt.status, attempt.runtime_generation, attempt.lease_owner, attempt.lease_token, attempt.lease_expires_at, attempt.run_id, attempt.error_kind, attempt.error_message, attempt.leased_at, attempt.started_at, attempt.completed_at, attempt.created_at, attempt.updated_at
FROM agent_jobs job
JOIN agent_job_attempts attempt ON attempt.job_id = job.id
WHERE attempt.status IN ('leased', 'running')
  AND attempt.lease_expires_at <= now()
ORDER BY attempt.lease_expires_at, attempt.job_id, attempt.attempt_number
FOR UPDATE OF job, attempt SKIP LOCKED
LIMIT 1
`

func (q *Queries) GetExpiredAgentJobAttemptForUpdate(ctx context.Context) (AgentJobAttempt, error) {
	row := q.db.QueryRow(ctx, getExpiredAgentJobAttemptForUpdate)
	var i AgentJobAttempt
	err := row.Scan(
		&i.JobID,
		&i.AttemptNumber,
		&i.Status,
		&i.RuntimeGeneration,
		&i.LeaseOwner,
		&i.LeaseToken,
		&i.LeaseExpiresAt,
		&i.RunID,
		&i.ErrorKind,
		&i.ErrorMessage,
		&i.LeasedAt,
		&i.StartedAt,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getRunningRunForJobEnqueue = `-- name: GetRunningRunForJobEnqueue :one
SELECT id, agent_id, bridge_id, status, trigger_type, trigger_ref, source_ref, input_payload, actions, llm_calls, llm_tokens_in, llm_tokens_out, llm_cost_estimate, duration_ms, stdout_log, error_message, error_kind, exit_code, panic_trace, checkpoint, compacted, started_at, finished_at, parent_run_id, llm_tokens_cached, caller_user_id, caller_conversation_id, caller_access
FROM runs
WHERE id = $1
  AND agent_id = $2
  AND status = 'running'
FOR SHARE
`

type GetRunningRunForJobEnqueueParams struct {
	SourceRunID pgtype.UUID `json:"source_run_id"`
	AgentID     pgtype.UUID `json:"agent_id"`
}

func (q *Queries) GetRunningRunForJobEnqueue(ctx context.Context, arg GetRunningRunForJobEnqueueParams) (Run, error) {
	row := q.db.QueryRow(ctx, getRunningRunForJobEnqueue, arg.SourceRunID, arg.AgentID)
	var i Run
	err := row.Scan(
		&i.ID,
		&i.AgentID,
		&i.BridgeID,
		&i.Status,
		&i.TriggerType,
		&i.TriggerRef,
		&i.SourceRef,
		&i.InputPayload,
		&i.Actions,
		&i.LlmCalls,
		&i.LlmTokensIn,
		&i.LlmTokensOut,
		&i.LlmCostEstimate,
		&i.DurationMs,
		&i.StdoutLog,
		&i.ErrorMessage,
		&i.ErrorKind,
		&i.ExitCode,
		&i.PanicTrace,
		&i.Checkpoint,
		&i.Compacted,
		&i.StartedAt,
		&i.FinishedAt,
		&i.ParentRunID,
		&i.LlmTokensCached,
		&i.CallerUserID,
		&i.CallerConversationID,
		&i.CallerAccess,
	)
	return i, err
}

const hasActiveAgentJobAttempt = `-- name: HasActiveAgentJobAttempt :one
SELECT EXISTS (
    SELECT 1
    FROM agent_job_attempts
    WHERE job_id = $1 AND status IN ('leased', 'running')
)
`

func (q *Queries) HasActiveAgentJobAttempt(ctx context.Context, jobID pgtype.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, hasActiveAgentJobAttempt, jobID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const insertAgentJob = `-- name: InsertAgentJob :one
INSERT INTO agent_jobs (
    id, agent_id, handler_name, handler_version, input_schema_hash,
    output_schema_hash, source_run_id, cron_id, cron_slug,
    initiator_kind, initiator_user_id, initiator_conversation_id, initiator_access, status, timeout_ms,
    max_attempts, attempt_limit, attempt_count, next_attempt_at, scheduled_at, input_payload, state_version
)
VALUES (
    $1, $2, $3, $4, $5,
    $6, $7, NULL, NULL, $8, $9,
    $10, $11, 'queued', $12,
    $13, $13, 0, coalesce($14, now()), $14, $15, 1
)
ON CONFLICT (id) DO NOTHING
RETURNING id, agent_id, handler_name, handler_version, input_schema_hash, output_schema_hash, source_run_id, cron_id, cron_slug, initiator_kind, initiator_user_id, initiator_conversation_id, initiator_access, status, timeout_ms, max_attempts, attempt_limit, attempt_count, next_attempt_at, scheduled_at, input_payload, output_payload, progress_phase, progress_message, progress_completed, progress_total, progress_attempt, progress_updated_at, last_error, cancel_requested_at, cancelled_by_user_id, started_at, completed_at, state_version, created_at, updated_at
`

type InsertAgentJobParams struct {
	ID                      pgtype.UUID        `json:"id"`
	AgentID                 pgtype.UUID        `json:"agent_id"`
	HandlerName             string             `json:"handler_name"`
	HandlerVersion          int32              `json:"handler_version"`
	InputSchemaHash         string             `json:"input_schema_hash"`
	OutputSchemaHash        string             `json:"output_schema_hash"`
	SourceRunID             pgtype.UUID        `json:"source_run_id"`
	InitiatorKind           string             `json:"initiator_kind"`
	InitiatorUserID         pgtype.UUID        `json:"initiator_user_id"`
	InitiatorConversationID pgtype.UUID        `json:"initiator_conversation_id"`
	InitiatorAccess         string             `json:"initiator_access"`
	TimeoutMs               int64              `json:"timeout_ms"`
	MaxAttempts             int32              `json:"max_attempts"`
	ScheduledAt             pgtype.Timestamptz `json:"scheduled_at"`
	InputPayload            []byte             `json:"input_payload"`
}

func (q *Queries) InsertAgentJob(ctx context.Context, arg InsertAgentJobParams) (AgentJob, error) {
	row := q.db.QueryRow(ctx, insertAgentJob,
		arg.ID,
		arg.AgentID,
		arg.HandlerName,
		arg.HandlerVersion,
		arg.InputSchemaHash,
		arg.OutputSchemaHash,
		arg.SourceRunID,
		arg.InitiatorKind,
		arg.InitiatorUserID,
		arg.InitiatorConversationID,
		arg.InitiatorAccess,
		arg.TimeoutMs,
		arg.MaxAttempts,
		arg.ScheduledAt,
		arg.InputPayload,
	)
	var i AgentJob
	err := row.Scan(
		&i.ID,
		&i.AgentID,
		&i.HandlerName,
		&i.HandlerVersion,
		&i.InputSchemaHash,
		&i.OutputSchemaHash,
		&i.SourceRunID,
		&i.CronID,
		&i.CronSlug,
		&i.InitiatorKind,
		&i.InitiatorUserID,
		&i.InitiatorConversationID,
		&i.InitiatorAccess,
		&i.Status,
		&i.TimeoutMs,
		&i.MaxAttempts,
		&i.AttemptLimit,
		&i.AttemptCount,
		&i.NextAttemptAt,
		&i.ScheduledAt,
		&i.InputPayload,
		&i.OutputPayload,
		&i.ProgressPhase,
		&i.ProgressMessage,
		&i.ProgressCompleted,
		&i.ProgressTotal,
		&i.ProgressAttempt,
		&i.ProgressUpdatedAt,
		&i.LastError,
		&i.CancelRequestedAt,
		&i.CancelledByUserID,
		&i.StartedAt,
		&i.CompletedAt,
		&i.StateVersion,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const interruptAgentJobAttempt = `-- name: InterruptAgentJobAttempt :execrows
UPDATE agent_job_attempts
SET status = 'interrupted',
    error_kind = 'platform',
    error_message = $1,
    completed_at = now(),
    updated_at = now()
WHERE job_id = $2
  AND attempt_number = $3
  AND lease_owner = $4
  AND lease_token = $5
  AND status IN ('leased', 'running')
  AND lease_expires_at > now()
`

type InterruptAgentJobAttemptParams struct {
	ErrorMessage  pgtype.Text `json:"error_message"`
	JobID         pgtype.UUID `json:"job_id"`
	AttemptNumber int32       `json:"attempt_number"`
	LeaseOwner    pgtype.UUID `json:"lease_owner"`
	LeaseToken    pgtype.UUID `json:"lease_token"`
}

func (q *Queries) InterruptAgentJobAttempt(ctx context.Context, arg InterruptAgentJobAttemptParams) (int64, error) {
	result, err := q.db.Exec(ctx, interruptAgentJobAttempt,
		arg.ErrorMessage,
		arg.JobID,
		arg.AttemptNumber,
		arg.LeaseOwner,
		arg.LeaseToken,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const interruptExpiredAgentJobAttempt = `-- name: InterruptExpiredAgentJobAttempt :execrows
UPDATE agent_job_attempts
SET status = 'interrupted',
    error_kind = 'platform',
    error_message = $1,
    completed_at = now(),
    updated_at = now()
WHERE job_id = $2
  AND attempt_number = $3
  AND lease_token = $4
  AND status IN ('leased', 'running')
  AND lease_expires_at <= now()
`

type InterruptExpiredAgentJobAttemptParams struct {
	ErrorMessage  pgtype.Text `json:"error_message"`
	JobID         pgtype.UUID `json:"job_id"`
	AttemptNumber int32       `json:"attempt_number"`
	LeaseToken    pgtype.UUID `json:"lease_token"`
}

func (q *Queries) InterruptExpiredAgentJobAttempt(ctx context.Context, arg InterruptExpiredAgentJobAttemptParams) (int64, error) {
	result, err := q.db.Exec(ctx, interruptExpiredAgentJobAttempt,
		arg.ErrorMessage,
		arg.JobID,
		arg.AttemptNumber,
		arg.LeaseToken,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listActiveAgentJobAttempts = `-- name: ListActiveAgentJobAttempts :many
SELECT attempt.job_id, attempt.attempt_number, attempt.status, attempt.runtime_generation, attempt.lease_owner, attempt.lease_token, attempt.lease_expires_at, attempt.run_id, attempt.error_kind, attempt.error_message, attempt.leased_at, attempt.started_at, attempt.completed_at, attempt.created_at, attempt.updated_at
FROM agent_job_attempts attempt
JOIN agent_jobs job ON job.id = attempt.job_id
WHERE job.agent_id = $1
  AND attempt.status IN ('leased', 'running')
ORDER BY attempt.leased_at, attempt.job_id, attempt.attempt_number
LIMIT $2
`

type ListActiveAgentJobAttemptsParams struct {
	AgentID pgtype.UUID `json:"agent_id"`
	Lim     int32       `json:"lim"`
}

func (q *Queries) ListActiveAgentJobAttempts(ctx context.Context, arg ListActiveAgentJobAttemptsParams) ([]AgentJobAttempt, error) {
	rows, err := q.db.Query(ctx, listActiveAgentJobAttempts, arg.AgentID, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AgentJobAttempt{}
	for rows.Next() {
		var i AgentJobAttempt
		if err := rows.Scan(
			&i.JobID,
			&i.AttemptNumber,
			&i.Status,
			&i.RuntimeGeneration,
			&i.LeaseOwner,
			&i.LeaseToken,
			&i.LeaseExpiresAt,
			&i.RunID,
			&i.ErrorKind,
			&i.ErrorMessage,
			&i.LeasedAt,
			&i.StartedAt,
			&i.CompletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAgentBuildBlockingJobs = `-- name: ListAgentBuildBlockingJobs :many
SELECT job.id, job.agent_id, job.handler_name, job.handler_version, job.input_schema_hash, job.output_schema_hash, job.source_run_id, job.cron_id, job.cron_slug, job.initiator_kind, job.initiator_user_id, job.initiator_conversation_id, job.initiator_access, job.status, job.timeout_ms, job.max_attempts, job.attempt_limit, job.attempt_count, job.next_attempt_at, job.scheduled_at, job.input_payload, job.output_payload, job.progress_phase, job.progress_message, job.progress_completed, job.progress_total, job.progress_attempt, job.progress_updated_at, job.last_error, job.cancel_requested_at, job.cancelled_by_user_id, job.started_at, job.completed_at, job.state_version, job.created_at, job.updated_at
FROM agent_jobs job
JOIN agent_builds build ON build.id = $1 AND build.agent_id = job.agent_id
WHERE job.agent_id = $2
  AND build.job_manifest_extracted_at IS NOT NULL
  AND job.status IN ('queued', 'running')
  AND (
      ($3::timestamptz IS NULL AND $4::uuid IS NULL)
      OR (job.created_at, job.id) > ($3, $4)
  )
  AND NOT EXISTS (
      SELECT 1
      FROM agent_build_job_handlers candidate
      WHERE candidate.build_id = build.id
        AND candidate.name = job.handler_name
        AND candidate.version = job.handler_version
        AND candidate.input_schema_hash = job.input_schema_hash
        AND candidate.output_schema_hash = job.output_schema_hash
  )
ORDER BY job.created_at, job.id
LIMIT $5
`

type ListAgentBuildBlockingJobsParams struct {
	BuildID         pgtype.UUID        `json:"build_id"`
	AgentID         pgtype.UUID        `json:"agent_id"`
	CursorCreatedAt pgtype.Timestamptz `json:"cursor_created_at"`
	CursorID        pgtype.UUID        `json:"cursor_id"`
	Lim             int32              `json:"lim"`
}

func (q *Queries) ListAgentBuildBlockingJobs(ctx context.Context, arg ListAgentBuildBlockingJobsParams) ([]AgentJob, error) {
	rows, err := q.db.Query(ctx, listAgentBuildBlockingJobs,
		arg.BuildID,
		arg.AgentID,
		arg.CursorCreatedAt,
		arg.CursorID,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AgentJob{}
	for rows.Next() {
		var i AgentJob
		if err := rows.Scan(
			&i.ID,
			&i.AgentID,
			&i.HandlerName,
			&i.HandlerVersion,
			&i.InputSchemaHash,
			&i.OutputSchemaHash,
			&i.SourceRunID,
			&i.CronID,
			&i.CronSlug,
			&i.InitiatorKind,
			&i.InitiatorUserID,
			&i.InitiatorConversationID,
			&i.InitiatorAccess,
			&i.Status,
			&i.TimeoutMs,
			&i.MaxAttempts,
			&i.AttemptLimit,
			&i.AttemptCount,
			&i.NextAttemptAt,
			&i.ScheduledAt,
			&i.InputPayload,
			&i.OutputPayload,
			&i.ProgressPhase,
			&i.ProgressMessage,
			&i.ProgressCompleted,
			&i.ProgressTotal,
			&i.ProgressAttempt,
			&i.ProgressUpdatedAt,
			&i.LastError,
			&i.CancelRequestedAt,
			&i.CancelledByUserID,
			&i.StartedAt,
			&i.CompletedAt,
			&i.StateVersion,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAgentJobAttempts = `-- name: ListAgentJobAttempts :many
SELECT job_id, attempt_number, status, runtime_generation, lease_owner, lease_token, lease_expires_at, run_id, error_kind, error_message, leased_at, started_at, completed_at, created_at, updated_at
FROM agent_job_attempts
WHERE job_id = $1
ORDER BY attempt_number
`

func (q *Queries) ListAgentJobAttempts(ctx context.Context, jobID pgtype.UUID) ([]AgentJobAttempt, error) {
	rows, err := q.db.Query(ctx, listAgentJobAttempts, jobID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AgentJobAttempt{}
	for rows.Next() {
		var i AgentJobAttempt
		if err := rows.Scan(
			&i.JobID,
			&i.AttemptNumber,
			&i.Status,
			&i.RuntimeGeneration,
			&i.LeaseOwner,
			&i.LeaseToken,
			&i.LeaseExpiresAt,
			&i.RunID,
			&i.ErrorKind,
			&i.ErrorMessage,
			&i.LeasedAt,
			&i.StartedAt,
			&i.CompletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAgentJobsByAgent = `-- name: ListAgentJobsByAgent :many
SELECT id, agent_id, handler_name, handler_version, input_schema_hash, output_schema_hash, source_run_id, cron_id, cron_slug, initiator_kind, initiator_user_id, initiator_conversation_id, initiator_access, status, timeout_ms, max_attempts, attempt_limit, attempt_count, next_attempt_at, scheduled_at, input_payload, output_payload, progress_phase, progress_message, progress_completed, progress_total, progress_attempt, progress_updated_at, last_error, cancel_requested_at, cancelled_by_user_id, started_at, completed_at, state_version, created_at, updated_at
FROM agent_jobs
WHERE agent_id = $1
  AND (
      ($2::timestamptz IS NULL AND $3::uuid IS NULL)
      OR (created_at, id) < ($2, $3)
  )
ORDER BY created_at DESC, id DESC
LIMIT $4
`

type ListAgentJobsByAgentParams struct {
	AgentID         pgtype.UUID        `json:"agent_id"`
	CursorCreatedAt pgtype.Timestamptz `json:"cursor_created_at"`
	CursorID        pgtype.UUID        `json:"cursor_id"`
	Lim             int32              `json:"lim"`
}

func (q *Queries) ListAgentJobsByAgent(ctx context.Context, arg ListAgentJobsByAgentParams) ([]AgentJob, error) {
	rows, err := q.db.Query(ctx, listAgentJobsByAgent,
		arg.AgentID,
		arg.CursorCreatedAt,
		arg.CursorID,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AgentJob{}
	for rows.Next() {
		var i AgentJob
		if err := rows.Scan(
			&i.ID,
			&i.AgentID,
			&i.HandlerName,
			&i.HandlerVersion,
			&i.InputSchemaHash,
			&i.OutputSchemaHash,
			&i.SourceRunID,
			&i.CronID,
			&i.CronSlug,
			&i.InitiatorKind,
			&i.InitiatorUserID,
			&i.InitiatorConversationID,
			&i.InitiatorAccess,
			&i.Status,
			&i.TimeoutMs,
			&i.MaxAttempts,
			&i.AttemptLimit,
			&i.AttemptCount,
			&i.NextAttemptAt,
			&i.ScheduledAt,
			&i.InputPayload,
			&i.OutputPayload,
			&i.ProgressPhase,
			&i.ProgressMessage,
			&i.ProgressCompleted,
			&i.ProgressTotal,
			&i.ProgressAttempt,
			&i.ProgressUpdatedAt,
			&i.LastError,
			&i.CancelRequestedAt,
			&i.CancelledByUserID,
			&i.StartedAt,
			&i.CompletedAt,
			&i.StateVersion,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNonterminalJobHandlerVersions = `-- name: ListNonterminalJobHandlerVersions :many
SELECT DISTINCT handler_name, handler_version
FROM agent_jobs
WHERE agent_id = $1 AND status IN ('queued', 'running')
ORDER BY handler_name, handler_version
`

type ListNonterminalJobHandlerVersionsRow struct {
	HandlerName    string `json:"handler_name"`
	HandlerVersion int32  `json:"handler_version"`
}

func (q *Queries) ListNonterminalJobHandlerVersions(ctx context.Context, agentID pgtype.UUID) ([]ListNonterminalJobHandlerVersionsRow, error) {
	rows, err := q.db.Query(ctx, listNonterminalJobHandlerVersions, agentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListNonterminalJobHandlerVersionsRow{}
	for rows.Next() {
		var i ListNonterminalJobHandlerVersionsRow
		if err := rows.Scan(&i.HandlerName, &i.HandlerVersion); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockAgentForDueJob = `-- name: LockAgentForDueJob :one
SELECT a.id
FROM agents a
WHERE a.status = 'active'
  AND a.job_dispatch_paused_build_id IS NULL
  AND EXISTS (
      SELECT 1
      FROM agent_jobs j
      JOIN agent_job_handlers h
        ON h.agent_id = j.agent_id
       AND h.name = j.handler_name
       AND h.version = j.handler_version
      WHERE j.agent_id = a.id
        AND j.status IN ('queued', 'running')
        AND j.next_attempt_at <= now()
        AND j.cancel_requested_at IS NULL
        AND j.attempt_count < j.attempt_limit
        AND h.active
        AND h.agent_token_version = a.agent_token_version
        AND NOT EXISTS (
            SELECT 1 FROM agent_job_attempts active
            WHERE active.job_id = j.id AND active.status IN ('leased', 'running')
        )
        AND (
            SELECT count(*) FROM agent_job_attempts active
            WHERE active.status IN ('leased', 'running')
        ) < $1::bigint
        AND (
            SELECT count(*)
            FROM agent_job_attempts active
            JOIN agent_jobs active_job ON active_job.id = active.job_id
            WHERE active.status IN ('leased', 'running')
              AND active_job.agent_id = j.agent_id
        ) < $2::bigint
        AND (
            SELECT count(*)
            FROM agent_job_attempts active
            JOIN agent_jobs active_job ON active_job.id = active.job_id
            WHERE active.status IN ('leased', 'running')
              AND active_job.agent_id = j.agent_id
              AND active_job.handler_name = j.handler_name
              AND active_job.handler_version = j.handler_version
        ) < h.max_concurrency
  )
ORDER BY (
    SELECT min(j.next_attempt_at)
    FROM agent_jobs j
    WHERE j.agent_id = a.id
      AND j.status IN ('queued', 'running')
      AND j.cancel_requested_at IS NULL
), a.id
FOR UPDATE OF a SKIP LOCKED
LIMIT 1
`

type LockAgentForDueJobParams struct {
	GlobalLimit int64 `json:"global_limit"`
	AgentLimit  int64 `json:"agent_limit"`
}

func (q *Queries) LockAgentForDueJob(ctx context.Context, arg LockAgentForDueJobParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, lockAgentForDueJob, arg.GlobalLimit, arg.AgentLimit)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const lockAgentJobDispatch = `-- name: LockAgentJobDispatch :exec
SELECT pg_advisory_xact_lock(4705497361458202689)
`

func (q *Queries) LockAgentJobDispatch(ctx context.Context) error {
	_, err := q.db.Exec(ctx, lockAgentJobDispatch)
	return err
}

const pauseAgentJobDispatch = `-- name: PauseAgentJobDispatch :one
WITH pause_time AS (
    SELECT statement_timestamp() AS paused_at
), paused AS (
    UPDATE agents agent
    SET job_dispatch_paused_build_id = $1,
        job_dispatch_paused_at = pause_time.paused_at,
        job_dispatch_pause_deadline = pause_time.paused_at + interval '2 minutes',
        updated_at = now()
    FROM agent_builds build, pause_time
    WHERE agent.id = $2
      AND agent.job_dispatch_paused_build_id IS NULL
      AND build.id = $1
      AND build.agent_id = agent.id
      AND build.deployment_token = $3
      AND build.job_manifest_extracted_at IS NOT NULL
      AND build.deployment_phase IN ('manifest', 'blocked')
      AND build.cancel_requested_at IS NULL
      AND NOT EXISTS (
          SELECT 1
          FROM agent_jobs job
          WHERE job.agent_id = agent.id
            AND job.status IN ('queued', 'running')
            AND NOT EXISTS (
                SELECT 1
                FROM agent_build_job_handlers candidate
                WHERE candidate.build_id = build.id
                  AND candidate.name = job.handler_name
                  AND candidate.version = job.handler_version
                  AND candidate.input_schema_hash = job.input_schema_hash
                  AND candidate.output_schema_hash = job.output_schema_hash
            )
      )
    RETURNING agent.id, agent.owner_principal_id, agent.slug, agent.name, agent.description, agent.status, agent.upgrade_status, agent.auto_fix, agent.build_provider_id, agent.build_model, agent.exec_provider_id, agent.exec_model, agent.stt_provider_id, agent.stt_model, agent.vision_provider_id, agent.vision_model, agent.tts_provider_id, agent.tts_model, agent.image_gen_provider_id, agent.image_gen_model, agent.embedding_provider_id, agent.embedding_model, agent.search_provider_id, agent.search_model, agent.source_ref, agent.image_ref, agent.db_schema, agent.db_password, agent.sdk_version, agent.config, agent.instructions, agent.error_message, agent.created_at, agent.updated_at, agent.mcp_enabled, agent.allow_public_mcp, agent.allow_public_routes, agent.tools_hash, agent.emoji, agent.allow_oauth_mcp_prompt, agent.allow_public_mcp_prompt, agent.git_remote_url, agent.git_mode, agent.git_credential_id, agent.git_default_branch, agent.git_webhook_secret, agent.git_last_synced_ref, agent.agent_token_version, agent.job_dispatch_paused_build_id, agent.job_dispatch_paused_at, agent.job_dispatch_pause_deadline
), phase AS (
    UPDATE agent_builds build
    SET deployment_phase = 'paused'
    FROM paused
    WHERE build.id = paused.job_dispatch_paused_build_id
    RETURNING build.id
)
SELECT paused.id, paused.owner_principal_id, paused.slug, paused.name, paused.description, paused.status, paused.upgrade_status, paused.auto_fix, paused.build_provider_id, paused.build_model, paused.exec_provider_id, paused.exec_model, paused.stt_provider_id, paused.stt_model, paused.vision_provider_id, paused.vision_model, paused.tts_provider_id, paused.tts_model, paused.image_gen_provider_id, paused.image_gen_model, paused.embedding_provider_id, paused.embedding_model, paused.search_provider_id, paused.search_model, paused.source_ref, paused.image_ref, paused.db_schema, paused.db_password, paused.sdk_version, paused.config, paused.instructions, paused.error_message, paused.created_at, paused.updated_at, paused.mcp_enabled, paused.allow_public_mcp, paused.allow_public_routes, paused.tools_hash, paused.emoji, paused.allow_oauth_mcp_prompt, paused.allow_public_mcp_prompt, paused.git_remote_url, paused.git_mode, paused.git_credential_id, paused.git_default_branch, paused.git_webhook_secret, paused.git_last_synced_ref, paused.agent_token_version, paused.job_dispatch_paused_build_id, paused.job_dispatch_paused_at, paused.job_dispatch_pause_deadline FROM paused JOIN phase ON true
`

type PauseAgentJobDispatchParams struct {
	BuildID         pgtype.UUID `json:"build_id"`
	AgentID         pgtype.UUID `json:"agent_id"`
	DeploymentToken pgtype.UUID `json:"deployment_token"`
}

type PauseAgentJobDispatchRow struct {
	ID                       pgtype.UUID        `json:"id"`
	OwnerPrincipalID         pgtype.UUID        `json:"owner_principal_id"`
	Slug                     string             `json:"slug"`
	Name                     string             `json:"name"`
	Description              string             `json:"description"`
	Status                   string             `json:"status"`
	UpgradeStatus            string             `json:"upgrade_status"`
	AutoFix                  bool               `json:"auto_fix"`
	BuildProviderID          pgtype.UUID        `json:"build_provider_id"`
	BuildModel               string             `json:"build_model"`
	ExecProviderID           pgtype.UUID        `json:"exec_provider_id"`
	ExecModel                string             `json:"exec_model"`
	SttProviderID            pgtype.UUID        `json:"stt_provider_id"`
	SttModel                 string             `json:"stt_model"`
	VisionProviderID         pgtype.UUID        `json:"vision_provider_id"`
	VisionModel              string             `json:"vision_model"`
	TtsProviderID            pgtype.UUID        `json:"tts_provider_id"`
	TtsModel                 string             `json:"tts_model"`
	ImageGenProviderID       pgtype.UUID        `json:"image_gen_provider_id"`
	ImageGenModel            string             `json:"image_gen_model"`
	EmbeddingProviderID      pgtype.UUID        `json:"embedding_provider_id"`
	EmbeddingModel           string             `json:"embedding_model"`
	SearchProviderID         pgtype.UUID        `json:"search_provider_id"`
	SearchModel              string             `json:"search_model"`
	SourceRef                string             `json:"source_ref"`
	ImageRef                 string             `json:"image_ref"`
	DbSchema                 string             `json:"db_schema"`
	DbPassword               string             `json:"db_password"`
	SdkVersion               string             `json:"sdk_version"`
	Config                   []byte             `json:"config"`
	Instructions             []byte             `json:"instructions"`
	ErrorMessage             string             `json:"error_message"`
	CreatedAt                pgtype.Timestamptz `json:"created_at"`
	UpdatedAt                pgtype.Timestamptz `json:"updated_at"`
	McpEnabled               bool               `json:"mcp_enabled"`
	AllowPublicMcp           bool               `json:"allow_public_mcp"`
	AllowPublicRoutes        bool               `json:"allow_public_routes"`
	ToolsHash                []byte             `json:"tools_hash"`
	Emoji                    string             `json:"emoji"`
	AllowOauthMcpPrompt      bool               `json:"allow_oauth_mcp_prompt"`
	AllowPublicMcpPrompt     bool               `json:"allow_public_mcp_prompt"`
	GitRemoteUrl             string             `json:"git_remote_url"`
	GitMode                  string             `json:"git_mode"`
	GitCredentialID          pgtype.UUID        `json:"git_credential_id"`
	GitDefaultBranch         string             `json:"git_default_branch"`
	GitWebhookSecret         string             `json:"git_webhook_secret"`
	GitLastSyncedRef         string             `json:"git_last_synced_ref"`
	AgentTokenVersion        int64              `json:"agent_token_version"`
	JobDispatchPausedBuildID pgtype.UUID        `json:"job_dispatch_paused_build_id"`
	JobDispatchPausedAt      pgtype.Timestamptz `json:"job_dispatch_paused_at"`
	JobDispatchPauseDeadline pgtype.Timestamptz `json:"job_dispatch_pause_deadline"`
}

func (q *Queries) PauseAgentJobDispatch(ctx context.Context, arg PauseAgentJobDispatchParams) (PauseAgentJobDispatchRow, error) {
	row := q.db.QueryRow(ctx, pauseAgentJobDispatch, arg.BuildID, arg.AgentID, arg.DeploymentToken)
	var i PauseAgentJobDispatchRow
	err := row.Scan(
		&i.ID,
		&i.OwnerPrincipalID,
		&i.Slug,
		&i.Name,
		&i.Description,
		&i.Status,
		&i.UpgradeStatus,
		&i.AutoFix,
		&i.BuildProviderID,
		&i.BuildModel,
		&i.ExecProviderID,
		&i.ExecModel,
		&i.SttProviderID,
		&i.SttModel,
		&i.VisionProviderID,
		&i.VisionModel,
		&i.TtsProviderID,
		&i.TtsModel,
		&i.ImageGenProviderID,
		&i.ImageGenModel,
		&i.EmbeddingProviderID,
		&i.EmbeddingModel,
		&i.SearchProviderID,
		&i.SearchModel,
		&i.SourceRef,
		&i.ImageRef,
		&i.DbSchema,
		&i.DbPassword,
		&i.SdkVersion,
		&i.Config,
		&i.Instructions,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.McpEnabled,
		&i.AllowPublicMcp,
		&i.AllowPublicRoutes,
		&i.ToolsHash,
		&i.Emoji,
		&i.AllowOauthMcpPrompt,
		&i.AllowPublicMcpPrompt,
		&i.GitRemoteUrl,
		&i.GitMode,
		&i.GitCredentialID,
		&i.GitDefaultBranch,
		&i.GitWebhookSecret,
		&i.GitLastSyncedRef,
		&i.AgentTokenVersion,
		&i.JobDispatchPausedBuildID,
		&i.JobDispatchPausedAt,
		&i.JobDispatchPauseDeadline,
	)
	return i, err
}

const pruneTerminalAgentJobs = `-- name: PruneTerminalAgentJobs :execrows
WITH candidates AS (
    SELECT candidate_job.id
    FROM agent_jobs candidate_job
    WHERE candidate_job.status IN ('succeeded', 'failed', 'cancelled')
      AND candidate_job.completed_at < $1
    ORDER BY candidate_job.completed_at, candidate_job.id
    FOR UPDATE SKIP LOCKED
    LIMIT LEAST($2::integer, 500)
)
DELETE FROM agent_jobs job
USING candidates
WHERE job.id = candidates.id
`

type PruneTerminalAgentJobsParams struct {
	Cutoff pgtype.Timestamptz `json:"cutoff"`
	Lim    int32              `json:"lim"`
}

func (q *Queries) PruneTerminalAgentJobs(ctx context.Context, arg PruneTerminalAgentJobsParams) (int64, error) {
	result, err := q.db.Exec(ctx, pruneTerminalAgentJobs, arg.Cutoff, arg.Lim)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const renewAgentJobAttemptLease = `-- name: RenewAgentJobAttemptLease :execrows
UPDATE agent_job_attempts
SET lease_expires_at = now() + make_interval(secs => $1::integer),
    updated_at = now()
WHERE job_id = $2
  AND attempt_number = $3
  AND lease_owner = $4
  AND lease_token = $5
  AND status IN ('leased', 'running')
  AND lease_expires_at > now()
`

type RenewAgentJobAttemptLeaseParams struct {
	LeaseSeconds  int32       `json:"lease_seconds"`
	JobID         pgtype.UUID `json:"job_id"`
	AttemptNumber int32       `json:"attempt_number"`
	LeaseOwner    pgtype.UUID `json:"lease_owner"`
	LeaseToken    pgtype.UUID `json:"lease_token"`
}

func (q *Queries) RenewAgentJobAttemptLease(ctx context.Context, arg RenewAgentJobAttemptLeaseParams) (int64, error) {
	result, err := q.db.Exec(ctx, renewAgentJobAttemptLease,
		arg.LeaseSeconds,
		arg.JobID,
		arg.AttemptNumber,
		arg.LeaseOwner,
		arg.LeaseToken,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const requestRunningAgentJobCancellation = `-- name: RequestRunningAgentJobCancellation :one
UPDATE agent_jobs
SET cancel_requested_at = now(),
    cancelled_by_user_id = $1,
    updated_at = now(),
    state_version = state_version + 1
WHERE id = $2
  AND agent_id = $3
  AND status = 'running'
  AND cancel_requested_at IS NULL
RETURNING id, agent_id, handler_name, handler_version, input_schema_hash, output_schema_hash, source_run_id, cron_id, cron_slug, initiator_kind, initiator_user_id, initiator_conversation_id, initiator_access, status, timeout_ms, max_attempts, attempt_limit, attempt_count, next_attempt_at, scheduled_at, input_payload, output_payload, progress_phase, progress_message, progress_completed, progress_total, progress_attempt, progress_updated_at, last_error, cancel_requested_at, cancelled_by_user_id, started_at, completed_at, state_version, created_at, updated_at
`

type RequestRunningAgentJobCancellationParams struct {
	CancelledByUserID pgtype.UUID `json:"cancelled_by_user_id"`
	ID                pgtype.UUID `json:"id"`
	AgentID           pgtype.UUID `json:"agent_id"`
}

func (q *Queries) RequestRunningAgentJobCancellation(ctx context.Context, arg RequestRunningAgentJobCancellationParams) (AgentJob, error) {
	row := q.db.QueryRow(ctx, requestRunningAgentJobCancellation, arg.CancelledByUserID, arg.ID, arg.AgentID)
	var i AgentJob
	err := row.Scan(
		&i.ID,
		&i.AgentID,
		&i.HandlerName,
		&i.HandlerVersion,
		&i.InputSchemaHash,
		&i.OutputSchemaHash,
		&i.SourceRunID,
		&i.CronID,
		&i.CronSlug,
		&i.InitiatorKind,
		&i.InitiatorUserID,
		&i.InitiatorConversationID,
		&i.InitiatorAccess,
		&i.Status,
		&i.TimeoutMs,
		&i.MaxAttempts,
		&i.AttemptLimit,
		&i.AttemptCount,
		&i.NextAttemptAt,
		&i.ScheduledAt,
		&i.InputPayload,
		&i.OutputPayload,
		&i.ProgressPhase,
		&i.ProgressMessage,
		&i.ProgressCompleted,
		&i.ProgressTotal,
		&i.ProgressAttempt,
		&i.ProgressUpdatedAt,
		&i.LastError,
		&i.CancelRequestedAt,
		&i.CancelledByUserID,
		&i.StartedAt,
		&i.CompletedAt,
		&i.StateVersion,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const resumeAgentJobDispatch = `-- name: ResumeAgentJobDispatch :one
UPDATE agents agent
SET job_dispatch_paused_build_id = NULL,
    job_dispatch_paused_at = NULL,
    job_dispatch_pause_deadline = NULL,
    updated_at = now()
FROM agent_builds build
WHERE agent.id = $1
  AND agent.job_dispatch_paused_build_id = $2
  AND build.id = $2
  AND build.agent_id = agent.id
  AND build.deployment_token = $3
RETURNING agent.id, agent.owner_principal_id, agent.slug, agent.name, agent.description, agent.status, agent.upgrade_status, agent.auto_fix, agent.build_provider_id, agent.build_model, agent.exec_provider_id, agent.exec_model, agent.stt_provider_id, agent.stt_model, agent.vision_provider_id, agent.vision_model, agent.tts_provider_id, agent.tts_model, agent.image_gen_provider_id, agent.image_gen_model, agent.embedding_provider_id, agent.embedding_model, agent.search_provider_id, agent.search_model, agent.source_ref, agent.image_ref, agent.db_schema, agent.db_password, agent.sdk_version, agent.config, agent.instructions, agent.error_message, agent.created_at, agent.updated_at, agent.mcp_enabled, agent.allow_public_mcp, agent.allow_public_routes, agent.tools_hash, agent.emoji, agent.allow_oauth_mcp_prompt, agent.allow_public_mcp_prompt, agent.git_remote_url, agent.git_mode, agent.git_credential_id, agent.git_default_branch, agent.git_webhook_secret, agent.git_last_synced_ref, agent.agent_token_version, agent.job_dispatch_paused_build_id, agent.job_dispatch_paused_at, agent.job_dispatch_pause_deadline
`

type ResumeAgentJobDispatchParams struct {
	AgentID         pgtype.UUID `json:"agent_id"`
	BuildID         pgtype.UUID `json:"build_id"`
	DeploymentToken pgtype.UUID `json:"deployment_token"`
}

func (q *Queries) ResumeAgentJobDispatch(ctx context.Context, arg ResumeAgentJobDispatchParams) (Agent, error) {
	row := q.db.QueryRow(ctx, resumeAgentJobDispatch, arg.AgentID, arg.BuildID, arg.DeploymentToken)
	var i Agent
	err := row.Scan(
		&i.ID,
		&i.OwnerPrincipalID,
		&i.Slug,
		&i.Name,
		&i.Description,
		&i.Status,
		&i.UpgradeStatus,
		&i.AutoFix,
		&i.BuildProviderID,
		&i.BuildModel,
		&i.ExecProviderID,
		&i.ExecModel,
		&i.SttProviderID,
		&i.SttModel,
		&i.VisionProviderID,
		&i.VisionModel,
		&i.TtsProviderID,
		&i.TtsModel,
		&i.ImageGenProviderID,
		&i.ImageGenModel,
		&i.EmbeddingProviderID,
		&i.EmbeddingModel,
		&i.SearchProviderID,
		&i.SearchModel,
		&i.SourceRef,
		&i.ImageRef,
		&i.DbSchema,
		&i.DbPassword,
		&i.SdkVersion,
		&i.Config,
		&i.Instructions,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.McpEnabled,
		&i.AllowPublicMcp,
		&i.AllowPublicRoutes,
		&i.ToolsHash,
		&i.Emoji,
		&i.AllowOauthMcpPrompt,
		&i.AllowPublicMcpPrompt,
		&i.GitRemoteUrl,
		&i.GitMode,
		&i.GitCredentialID,
		&i.GitDefaultBranch,
		&i.GitWebhookSecret,
		&i.GitLastSyncedRef,
		&i.AgentTokenVersion,
		&i.JobDispatchPausedBuildID,
		&i.JobDispatchPausedAt,
		&i.JobDispatchPauseDeadline,
	)
	return i, err
}

const retryAgentJob = `-- name: RetryAgentJob :execrows
UPDATE agent_jobs
SET last_error = $1,
    next_attempt_at = now() + make_interval(secs => $2::integer),
    updated_at = now(),
    state_version = state_version + 1
WHERE id = $3 AND status = 'running' AND cancel_requested_at IS NULL
`

type RetryAgentJobParams struct {
	LastError      pgtype.Text `json:"last_error"`
	BackoffSeconds int32       `json:"backoff_seconds"`
	ID             pgtype.UUID `json:"id"`
}

func (q *Queries) RetryAgentJob(ctx context.Context, arg RetryAgentJobParams) (int64, error) {
	result, err := q.db.Exec(ctx, retryAgentJob, arg.LastError, arg.BackoffSeconds, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const retryAgentJobAttempt = `-- name: RetryAgentJobAttempt :execrows
UPDATE agent_job_attempts
SET status = 'retryable',
    error_kind = 'platform',
    error_message = $1,
    completed_at = now(),
    updated_at = now()
WHERE job_id = $2
  AND attempt_number = $3
  AND lease_owner = $4
  AND lease_token = $5
  AND status IN ('leased', 'running')
  AND lease_expires_at > now()
`

type RetryAgentJobAttemptParams struct {
	ErrorMessage  pgtype.Text `json:"error_message"`
	JobID         pgtype.UUID `json:"job_id"`
	AttemptNumber int32       `json:"attempt_number"`
	LeaseOwner    pgtype.UUID `json:"lease_owner"`
	LeaseToken    pgtype.UUID `json:"lease_token"`
}

func (q *Queries) RetryAgentJobAttempt(ctx context.Context, arg RetryAgentJobAttemptParams) (int64, error) {
	result, err := q.db.Exec(ctx, retryAgentJobAttempt,
		arg.ErrorMessage,
		arg.JobID,
		arg.AttemptNumber,
		arg.LeaseOwner,
		arg.LeaseToken,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const retryAgentJobForDeployment = `-- name: RetryAgentJobForDeployment :execrows
UPDATE agent_jobs
SET attempt_limit = greatest(attempt_limit, attempt_count + 1),
    last_error = $1,
    next_attempt_at = now(),
    updated_at = now(),
    state_version = state_version + 1
WHERE id = $2 AND status = 'running' AND cancel_requested_at IS NULL
`

type RetryAgentJobForDeploymentParams struct {
	LastError pgtype.Text `json:"last_error"`
	ID        pgtype.UUID `json:"id"`
}

func (q *Queries) RetryAgentJobForDeployment(ctx context.Context, arg RetryAgentJobForDeploymentParams) (int64, error) {
	result, err := q.db.Exec(ctx, retryAgentJobForDeployment, arg.LastError, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const retryTerminalAgentJob = `-- name: RetryTerminalAgentJob :one
UPDATE agent_jobs job
SET status = 'queued',
    attempt_limit = CASE
        WHEN attempt_limit <= attempt_count THEN attempt_count + 1
        ELSE attempt_limit
    END,
    next_attempt_at = now(),
    output_payload = NULL,
    last_error = NULL,
    progress_phase = NULL,
    progress_message = NULL,
    progress_completed = NULL,
    progress_total = NULL,
    progress_attempt = NULL,
    progress_updated_at = NULL,
    cancel_requested_at = NULL,
    cancelled_by_user_id = NULL,
    started_at = NULL,
    completed_at = NULL,
    updated_at = now(),
    state_version = state_version + 1
WHERE job.id = $1
  AND job.status IN ('failed', 'cancelled')
  AND job.attempt_count < 100
  AND NOT EXISTS (
      SELECT 1
      FROM agent_job_attempts attempt
      WHERE attempt.job_id = job.id
        AND attempt.status IN ('leased', 'running')
  )
RETURNING job.id, job.agent_id, job.handler_name, job.handler_version, job.input_schema_hash, job.output_schema_hash, job.source_run_id, job.cron_id, job.cron_slug, job.initiator_kind, job.initiator_user_id, job.initiator_conversation_id, job.initiator_access, job.status, job.timeout_ms, job.max_attempts, job.attempt_limit, job.attempt_count, job.next_attempt_at, job.scheduled_at, job.input_payload, job.output_payload, job.progress_phase, job.progress_message, job.progress_completed, job.progress_total, job.progress_attempt, job.progress_updated_at, job.last_error, job.cancel_requested_at, job.cancelled_by_user_id, job.started_at, job.completed_at, job.state_version, job.created_at, job.updated_at
`

func (q *Queries) RetryTerminalAgentJob(ctx context.Context, id pgtype.UUID) (AgentJob, error) {
	row := q.db.QueryRow(ctx, retryTerminalAgentJob, id)
	var i AgentJob
	err := row.Scan(
		&i.ID,
		&i.AgentID,
		&i.HandlerName,
		&i.HandlerVersion,
		&i.InputSchemaHash,
		&i.OutputSchemaHash,
		&i.SourceRunID,
		&i.CronID,
		&i.CronSlug,
		&i.InitiatorKind,
		&i.InitiatorUserID,
		&i.InitiatorConversationID,
		&i.InitiatorAccess,
		&i.Status,
		&i.TimeoutMs,
		&i.MaxAttempts,
		&i.AttemptLimit,
		&i.AttemptCount,
		&i.NextAttemptAt,
		&i.ScheduledAt,
		&i.InputPayload,
		&i.OutputPayload,
		&i.ProgressPhase,
		&i.ProgressMessage,
		&i.ProgressCompleted,
		&i.ProgressTotal,
		&i.ProgressAttempt,
		&i.ProgressUpdatedAt,
		&i.LastError,
		&i.CancelRequestedAt,
		&i.CancelledByUserID,
		&i.StartedAt,
		&i.CompletedAt,
		&i.StateVersion,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const startAgentJobAttempt = `-- name: StartAgentJobAttempt :execrows
UPDATE agent_job_attempts
SET status = 'running',
    run_id = $1,
    started_at = now(),
    updated_at = now()
WHERE job_id = $2
  AND attempt_number = $3
  AND lease_owner = $4
  AND lease_token = $5
  AND status = 'leased'
  AND lease_expires_at > now()
  AND EXISTS (
      SELECT 1
      FROM agent_jobs job
      WHERE job.id = agent_job_attempts.job_id
        AND job.status = 'running'
        AND job.cancel_requested_at IS NULL
  )
`

type StartAgentJobAttemptParams struct {
	RunID         pgtype.UUID `json:"run_id"`
	JobID         pgtype.UUID `json:"job_id"`
	AttemptNumber int32       `json:"attempt_number"`
	LeaseOwner    pgtype.UUID `json:"lease_owner"`
	LeaseToken    pgtype.UUID `json:"lease_token"`
}

func (q *Queries) StartAgentJobAttempt(ctx context.Context, arg StartAgentJobAttemptParams) (int64, error) {
	result, err := q.db.Exec(ctx, startAgentJobAttempt,
		arg.RunID,
		arg.JobID,
		arg.AttemptNumber,
		arg.LeaseOwner,
		arg.LeaseToken,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const succeedAgentJob = `-- name: SucceedAgentJob :execrows
UPDATE agent_jobs
SET status = 'succeeded',
    output_payload = $1,
    last_error = NULL,
    completed_at = now(),
    updated_at = now(),
    state_version = state_version + 1
WHERE id = $2 AND status = 'running' AND cancel_requested_at IS NULL
`

type SucceedAgentJobParams struct {
	OutputPayload []byte      `json:"output_payload"`
	ID            pgtype.UUID `json:"id"`
}

func (q *Queries) SucceedAgentJob(ctx context.Context, arg SucceedAgentJobParams) (int64, error) {
	result, err := q.db.Exec(ctx, succeedAgentJob, arg.OutputPayload, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const succeedAgentJobAttempt = `-- name: SucceedAgentJobAttempt :execrows
UPDATE agent_job_attempts
SET status = 'succeeded',
    completed_at = now(),
    updated_at = now()
WHERE job_id = $1
  AND attempt_number = $2
  AND lease_owner = $3
  AND lease_token = $4
  AND status IN ('leased', 'running')
  AND lease_expires_at > now()
`

type SucceedAgentJobAttemptParams struct {
	JobID         pgtype.UUID `json:"job_id"`
	AttemptNumber int32       `json:"attempt_number"`
	LeaseOwner    pgtype.UUID `json:"lease_owner"`
	LeaseToken    pgtype.UUID `json:"lease_token"`
}

func (q *Queries) SucceedAgentJobAttempt(ctx context.Context, arg SucceedAgentJobAttemptParams) (int64, error) {
	result, err := q.db.Exec(ctx, succeedAgentJobAttempt,
		arg.JobID,
		arg.AttemptNumber,
		arg.LeaseOwner,
		arg.LeaseToken,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const summarizeAgentBuildBlockingJobs = `-- name: SummarizeAgentBuildBlockingJobs :many
SELECT job.handler_name,
       job.handler_version,
       job.input_schema_hash,
       job.output_schema_hash,
       count(*) FILTER (WHERE job.status = 'queued')::bigint AS queued_count,
       count(*) FILTER (WHERE job.status = 'running')::bigint AS running_count
FROM agent_jobs job
JOIN agent_builds build ON build.id = $1 AND build.agent_id = job.agent_id
WHERE job.agent_id = $2
  AND build.job_manifest_extracted_at IS NOT NULL
  AND job.status IN ('queued', 'running')
  AND NOT EXISTS (
      SELECT 1
      FROM agent_build_job_handlers candidate
      WHERE candidate.build_id = build.id
        AND candidate.name = job.handler_name
        AND candidate.version = job.handler_version
        AND candidate.input_schema_hash = job.input_schema_hash
        AND candidate.output_schema_hash = job.output_schema_hash
  )
GROUP BY job.handler_name, job.handler_version, job.input_schema_hash, job.output_schema_hash
ORDER BY job.handler_name, job.handler_version, job.input_schema_hash, job.output_schema_hash
`

type SummarizeAgentBuildBlockingJobsParams struct {
	BuildID pgtype.UUID `json:"build_id"`
	AgentID pgtype.UUID `json:"agent_id"`
}

type SummarizeAgentBuildBlockingJobsRow struct {
	HandlerName      string `json:"handler_name"`
	HandlerVersion   int32  `json:"handler_version"`
	InputSchemaHash  string `json:"input_schema_hash"`
	OutputSchemaHash string `json:"output_schema_hash"`
	QueuedCount      int64  `json:"queued_count"`
	RunningCount     int64  `json:"running_count"`
}

func (q *Queries) SummarizeAgentBuildBlockingJobs(ctx context.Context, arg SummarizeAgentBuildBlockingJobsParams) ([]SummarizeAgentBuildBlockingJobsRow, error) {
	rows, err := q.db.Query(ctx, summarizeAgentBuildBlockingJobs, arg.BuildID, arg.AgentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SummarizeAgentBuildBlockingJobsRow{}
	for rows.Next() {
		var i SummarizeAgentBuildBlockingJobsRow
		if err := rows.Scan(
			&i.HandlerName,
			&i.HandlerVersion,
			&i.InputSchemaHash,
			&i.OutputSchemaHash,
			&i.QueuedCount,
			&i.RunningCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAgentJobProgress = `-- name: UpdateAgentJobProgress :one
UPDATE agent_jobs job
SET progress_phase = $1,
    progress_message = $2,
    progress_completed = $3,
    progress_total = $4,
    progress_attempt = $5,
    progress_updated_at = now(),
    updated_at = now(),
    state_version = state_version + 1
FROM agent_job_attempts attempt, agents agent
WHERE job.id = $6
  AND job.agent_id = $7
  AND job.status = 'running'
  AND job.cancel_requested_at IS NULL
  AND agent.id = job.agent_id
  AND agent.agent_token_version = $8
  AND attempt.job_id = job.id
  AND attempt.attempt_number = $5
  AND attempt.runtime_generation = $8
  AND attempt.status = 'running'
  AND attempt.run_id = $9
  AND attempt.lease_token = $10
  AND attempt.lease_expires_at > now()
RETURNING job.id, job.agent_id, job.handler_name, job.handler_version, job.input_schema_hash, job.output_schema_hash, job.source_run_id, job.cron_id, job.cron_slug, job.initiator_kind, job.initiator_user_id, job.initiator_conversation_id, job.initiator_access, job.status, job.timeout_ms, job.max_attempts, job.attempt_limit, job.attempt_count, job.next_attempt_at, job.scheduled_at, job.input_payload, job.output_payload, job.progress_phase, job.progress_message, job.progress_completed, job.progress_total, job.progress_attempt, job.progress_updated_at, job.last_error, job.cancel_requested_at, job.cancelled_by_user_id, job.started_at, job.completed_at, job.state_version, job.created_at, job.updated_at
`

type UpdateAgentJobProgressParams struct {
	ProgressPhase     pgtype.Text `json:"progress_phase"`
	ProgressMessage   pgtype.Text `json:"progress_message"`
	ProgressCompleted pgtype.Int8 `json:"progress_completed"`
	ProgressTotal     pgtype.Int8 `json:"progress_total"`
	AttemptNumber     pgtype.Int4 `json:"attempt_number"`
	JobID             pgtype.UUID `json:"job_id"`
	AgentID           pgtype.UUID `json:"agent_id"`
	RuntimeGeneration int64       `json:"runtime_generation"`
	RunID             pgtype.UUID `json:"run_id"`
	LeaseToken        pgtype.UUID `json:"lease_token"`
}

func (q *Queries) UpdateAgentJobProgress(ctx context.Context, arg UpdateAgentJobProgressParams) (AgentJob, error) {
	row := q.db.QueryRow(ctx, updateAgentJobProgress,
		arg.ProgressPhase,
		arg.ProgressMessage,
		arg.ProgressCompleted,
		arg.ProgressTotal,
		arg.AttemptNumber,
		arg.JobID,
		arg.AgentID,
		arg.RuntimeGeneration,
		arg.RunID,
		arg.LeaseToken,
	)
	var i AgentJob
	err := row.Scan(
		&i.ID,
		&i.AgentID,
		&i.HandlerName,
		&i.HandlerVersion,
		&i.InputSchemaHash,
		&i.OutputSchemaHash,
		&i.SourceRunID,
		&i.CronID,
		&i.CronSlug,
		&i.InitiatorKind,
		&i.InitiatorUserID,
		&i.InitiatorConversationID,
		&i.InitiatorAccess,
		&i.Status,
		&i.TimeoutMs,
		&i.MaxAttempts,
		&i.AttemptLimit,
		&i.AttemptCount,
		&i.NextAttemptAt,
		&i.ScheduledAt,
		&i.InputPayload,
		&i.OutputPayload,
		&i.ProgressPhase,
		&i.ProgressMessage,
		&i.ProgressCompleted,
		&i.ProgressTotal,
		&i.ProgressAttempt,
		&i.ProgressUpdatedAt,
		&i.LastError,
		&i.CancelRequestedAt,
		&i.CancelledByUserID,
		&i.StartedAt,
		&i.CompletedAt,
		&i.StateVersion,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
