// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: attachment_url_cache.sql

package dbq

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getCachedAttachmentURL = `-- name: GetCachedAttachmentURL :one
SELECT url, expires_at
FROM attachment_url_cache
WHERE canonical_key = $1
  AND expires_at > now() + $2::interval
`

type GetCachedAttachmentURLParams struct {
	CanonicalKey string          `json:"canonical_key"`
	MinRemaining pgtype.Interval `json:"min_remaining"`
}

type GetCachedAttachmentURLRow struct {
	Url       string             `json:"url"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

// Returns the cached presigned URL only if it has at least @min_remaining left
// before expiry. Caller treats "no rows" as cache miss → mint fresh.
func (q *Queries) GetCachedAttachmentURL(ctx context.Context, arg GetCachedAttachmentURLParams) (GetCachedAttachmentURLRow, error) {
	row := q.db.QueryRow(ctx, getCachedAttachmentURL, arg.CanonicalKey, arg.MinRemaining)
	var i GetCachedAttachmentURLRow
	err := row.Scan(&i.Url, &i.ExpiresAt)
	return i, err
}

const pruneExpiredAttachmentURLs = `-- name: PruneExpiredAttachmentURLs :execrows
DELETE FROM attachment_url_cache WHERE expires_at < now() - interval '24 hours'
`

// Background pruner: delete URL cache rows that expired more than 24h ago.
// Stale rows aren't harmful (just unused) but bounded growth is nice.
func (q *Queries) PruneExpiredAttachmentURLs(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, pruneExpiredAttachmentURLs)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const upsertCachedAttachmentURL = `-- name: UpsertCachedAttachmentURL :exec
INSERT INTO attachment_url_cache (canonical_key, url, expires_at)
VALUES ($1, $2, $3)
ON CONFLICT (canonical_key) DO UPDATE SET
    url        = EXCLUDED.url,
    expires_at = EXCLUDED.expires_at
`

type UpsertCachedAttachmentURLParams struct {
	CanonicalKey string             `json:"canonical_key"`
	Url          string             `json:"url"`
	ExpiresAt    pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) UpsertCachedAttachmentURL(ctx context.Context, arg UpsertCachedAttachmentURLParams) error {
	_, err := q.db.Exec(ctx, upsertCachedAttachmentURL, arg.CanonicalKey, arg.Url, arg.ExpiresAt)
	return err
}
