// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: connector_artifacts.sql

package dbq

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const claimConnectorArtifactBlobDeletion = `-- name: ClaimConnectorArtifactBlobDeletion :one
WITH candidate AS (
    SELECT digest FROM connector_artifact_blobs
    WHERE deletion_state = 'pending'
       OR (deletion_state = 'deleting' AND deletion_lease_expires_at <= now())
    ORDER BY created_at, digest
    FOR UPDATE SKIP LOCKED
    LIMIT 1
)
UPDATE connector_artifact_blobs blob
SET deletion_state = 'deleting', deletion_token = gen_random_uuid(),
    deletion_lease_expires_at = now() + make_interval(secs => $1::integer),
    deletion_attempts = deletion_attempts + 1, deletion_error = NULL
FROM candidate
WHERE blob.digest = candidate.digest
RETURNING blob.digest, blob.object_key, blob.size_bytes, blob.media_type, blob.created_at, blob.deletion_state, blob.deletion_token, blob.deletion_lease_expires_at, blob.deletion_error, blob.deletion_attempts
`

func (q *Queries) ClaimConnectorArtifactBlobDeletion(ctx context.Context, leaseSeconds int32) (ConnectorArtifactBlob, error) {
	row := q.db.QueryRow(ctx, claimConnectorArtifactBlobDeletion, leaseSeconds)
	var i ConnectorArtifactBlob
	err := row.Scan(
		&i.Digest,
		&i.ObjectKey,
		&i.SizeBytes,
		&i.MediaType,
		&i.CreatedAt,
		&i.DeletionState,
		&i.DeletionToken,
		&i.DeletionLeaseExpiresAt,
		&i.DeletionError,
		&i.DeletionAttempts,
	)
	return i, err
}

const createConnectorArtifactFile = `-- name: CreateConnectorArtifactFile :one
INSERT INTO connector_artifact_files (
    artifact_set_id, platform, filename, digest, size_bytes,
    notices_digest, notices_size_bytes
) VALUES (
    $1, $2, $3, $4, $5,
    $6, $7
)
RETURNING id, artifact_set_id, platform, filename, digest, size_bytes, notices_digest, notices_size_bytes, created_at
`

type CreateConnectorArtifactFileParams struct {
	ArtifactSetID    pgtype.UUID `json:"artifact_set_id"`
	Platform         string      `json:"platform"`
	Filename         string      `json:"filename"`
	Digest           string      `json:"digest"`
	SizeBytes        int64       `json:"size_bytes"`
	NoticesDigest    string      `json:"notices_digest"`
	NoticesSizeBytes int64       `json:"notices_size_bytes"`
}

func (q *Queries) CreateConnectorArtifactFile(ctx context.Context, arg CreateConnectorArtifactFileParams) (ConnectorArtifactFile, error) {
	row := q.db.QueryRow(ctx, createConnectorArtifactFile,
		arg.ArtifactSetID,
		arg.Platform,
		arg.Filename,
		arg.Digest,
		arg.SizeBytes,
		arg.NoticesDigest,
		arg.NoticesSizeBytes,
	)
	var i ConnectorArtifactFile
	err := row.Scan(
		&i.ID,
		&i.ArtifactSetID,
		&i.Platform,
		&i.Filename,
		&i.Digest,
		&i.SizeBytes,
		&i.NoticesDigest,
		&i.NoticesSizeBytes,
		&i.CreatedAt,
	)
	return i, err
}

const createConnectorArtifactSet = `-- name: CreateConnectorArtifactSet :one
INSERT INTO connector_artifact_sets (
    agent_id, build_id, connector_slug, source_ref, kind, contract_id, name,
    description, artifact_version, artifact_digest, protocol_major, protocol_minor, features, service_mode,
    interface_descriptor, interface_hash, settings_schema
) VALUES (
    $1, $2, $3, $4, $5, $6, $7,
    $8, $9, $10, $11, $12, $13, $14,
    $15, $16, $17
)
RETURNING id, agent_id, build_id, connector_slug, source_ref, kind, contract_id, name, description, artifact_version, artifact_digest, protocol_major, protocol_minor, features, interface_descriptor, interface_hash, settings_schema, retired_at, created_at, service_mode
`

type CreateConnectorArtifactSetParams struct {
	AgentID             pgtype.UUID `json:"agent_id"`
	BuildID             pgtype.UUID `json:"build_id"`
	ConnectorSlug       string      `json:"connector_slug"`
	SourceRef           string      `json:"source_ref"`
	Kind                string      `json:"kind"`
	ContractID          string      `json:"contract_id"`
	Name                string      `json:"name"`
	Description         string      `json:"description"`
	ArtifactVersion     string      `json:"artifact_version"`
	ArtifactDigest      string      `json:"artifact_digest"`
	ProtocolMajor       int32       `json:"protocol_major"`
	ProtocolMinor       int32       `json:"protocol_minor"`
	Features            []string    `json:"features"`
	ServiceMode         pgtype.Text `json:"service_mode"`
	InterfaceDescriptor []byte      `json:"interface_descriptor"`
	InterfaceHash       string      `json:"interface_hash"`
	SettingsSchema      []byte      `json:"settings_schema"`
}

func (q *Queries) CreateConnectorArtifactSet(ctx context.Context, arg CreateConnectorArtifactSetParams) (ConnectorArtifactSet, error) {
	row := q.db.QueryRow(ctx, createConnectorArtifactSet,
		arg.AgentID,
		arg.BuildID,
		arg.ConnectorSlug,
		arg.SourceRef,
		arg.Kind,
		arg.ContractID,
		arg.Name,
		arg.Description,
		arg.ArtifactVersion,
		arg.ArtifactDigest,
		arg.ProtocolMajor,
		arg.ProtocolMinor,
		arg.Features,
		arg.ServiceMode,
		arg.InterfaceDescriptor,
		arg.InterfaceHash,
		arg.SettingsSchema,
	)
	var i ConnectorArtifactSet
	err := row.Scan(
		&i.ID,
		&i.AgentID,
		&i.BuildID,
		&i.ConnectorSlug,
		&i.SourceRef,
		&i.Kind,
		&i.ContractID,
		&i.Name,
		&i.Description,
		&i.ArtifactVersion,
		&i.ArtifactDigest,
		&i.ProtocolMajor,
		&i.ProtocolMinor,
		&i.Features,
		&i.InterfaceDescriptor,
		&i.InterfaceHash,
		&i.SettingsSchema,
		&i.RetiredAt,
		&i.CreatedAt,
		&i.ServiceMode,
	)
	return i, err
}

const deleteExpiredConnectorArtifactSets = `-- name: DeleteExpiredConnectorArtifactSets :execrows
DELETE FROM connector_artifact_sets
WHERE retired_at < now() - interval '30 days'
`

func (q *Queries) DeleteExpiredConnectorArtifactSets(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, deleteExpiredConnectorArtifactSets)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const finishConnectorArtifactBlobDeletion = `-- name: FinishConnectorArtifactBlobDeletion :execrows
DELETE FROM connector_artifact_blobs blob
WHERE blob.digest = $1 AND blob.deletion_state = 'deleting' AND blob.deletion_token = $2
  AND blob.deletion_lease_expires_at > now()
  AND NOT EXISTS (SELECT 1 FROM connector_artifact_files file WHERE file.digest = blob.digest)
  AND NOT EXISTS (SELECT 1 FROM connector_artifact_files file WHERE file.notices_digest = blob.digest)
`

type FinishConnectorArtifactBlobDeletionParams struct {
	Digest        string      `json:"digest"`
	DeletionToken pgtype.UUID `json:"deletion_token"`
}

func (q *Queries) FinishConnectorArtifactBlobDeletion(ctx context.Context, arg FinishConnectorArtifactBlobDeletionParams) (int64, error) {
	result, err := q.db.Exec(ctx, finishConnectorArtifactBlobDeletion, arg.Digest, arg.DeletionToken)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getCompatibleConnectorArtifactDownload = `-- name: GetCompatibleConnectorArtifactDownload :one
SELECT artifact_set.agent_id, artifact_set.connector_slug, artifact_set.source_ref,
       artifact_set.artifact_version, artifact_file.id, artifact_file.artifact_set_id, artifact_file.platform, artifact_file.filename, artifact_file.digest, artifact_file.size_bytes, artifact_file.notices_digest, artifact_file.notices_size_bytes, artifact_file.created_at, blob.object_key,
       notices_blob.object_key AS notices_object_key
FROM agent_resource_needs need
JOIN connector_artifact_sets artifact_set ON artifact_set.agent_id = need.agent_id
JOIN agent_builds build ON build.id = artifact_set.build_id
JOIN connector_artifact_files artifact_file ON artifact_file.artifact_set_id = artifact_set.id
JOIN connector_artifact_blobs blob ON blob.digest = artifact_file.digest
JOIN connector_artifact_blobs notices_blob ON notices_blob.digest = artifact_file.notices_digest
WHERE need.agent_id = $1
  AND need.type = 'connector'
  AND need.slug = $2
  AND need.deleted_at IS NULL
  AND artifact_file.id = $3
  AND build.status = 'complete'
  AND artifact_set.retired_at IS NULL
  AND connector_interface_satisfies_need(
      artifact_set.interface_descriptor,
      artifact_set.contract_id,
      need.spec
  )
`

type GetCompatibleConnectorArtifactDownloadParams struct {
	AgentID        pgtype.UUID `json:"agent_id"`
	NeedSlug       string      `json:"need_slug"`
	ArtifactFileID pgtype.UUID `json:"artifact_file_id"`
}

type GetCompatibleConnectorArtifactDownloadRow struct {
	AgentID          pgtype.UUID        `json:"agent_id"`
	ConnectorSlug    string             `json:"connector_slug"`
	SourceRef        string             `json:"source_ref"`
	ArtifactVersion  string             `json:"artifact_version"`
	ID               pgtype.UUID        `json:"id"`
	ArtifactSetID    pgtype.UUID        `json:"artifact_set_id"`
	Platform         string             `json:"platform"`
	Filename         string             `json:"filename"`
	Digest           string             `json:"digest"`
	SizeBytes        int64              `json:"size_bytes"`
	NoticesDigest    string             `json:"notices_digest"`
	NoticesSizeBytes int64              `json:"notices_size_bytes"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	ObjectKey        string             `json:"object_key"`
	NoticesObjectKey string             `json:"notices_object_key"`
}

func (q *Queries) GetCompatibleConnectorArtifactDownload(ctx context.Context, arg GetCompatibleConnectorArtifactDownloadParams) (GetCompatibleConnectorArtifactDownloadRow, error) {
	row := q.db.QueryRow(ctx, getCompatibleConnectorArtifactDownload, arg.AgentID, arg.NeedSlug, arg.ArtifactFileID)
	var i GetCompatibleConnectorArtifactDownloadRow
	err := row.Scan(
		&i.AgentID,
		&i.ConnectorSlug,
		&i.SourceRef,
		&i.ArtifactVersion,
		&i.ID,
		&i.ArtifactSetID,
		&i.Platform,
		&i.Filename,
		&i.Digest,
		&i.SizeBytes,
		&i.NoticesDigest,
		&i.NoticesSizeBytes,
		&i.CreatedAt,
		&i.ObjectKey,
		&i.NoticesObjectKey,
	)
	return i, err
}

const getConnectorArtifactStatus = `-- name: GetConnectorArtifactStatus :one
WITH installation AS (
    SELECT id, owner_principal_id, slug, kind, contract_id, name, display_name, description, protocol_major, protocol_minor, features, artifact_version, artifact_digest, interface_descriptor, interface_hash, readiness, readiness_message, labels, lifecycle, last_seen_at, last_ready_at, created_at, updated_at, storage_origins, activation_manifest, activation_manifest_hash, service_mode, artifact_set_id, host_id, rollback_artifact_set_id, inventory_revision, inventory_mutation_hash, active_provenance, rollback_provenance, active_observation_state, rollback_observation_state, observed_active_digest, observed_active_manifest, observed_active_manifest_hash, observed_rollback_digest, observed_rollback_manifest, observed_rollback_manifest_hash FROM connector_resources installation_resource WHERE installation_resource.id = $1
), installed_file AS (
    SELECT artifact_file.platform, artifact_file.artifact_set_id
    FROM installation
    JOIN connector_artifact_sets artifact_set ON artifact_set.id = installation.artifact_set_id
    JOIN connector_artifact_files artifact_file
      ON artifact_file.artifact_set_id = artifact_set.id
     AND artifact_file.digest = installation.artifact_digest
    JOIN agent_builds build ON build.id = artifact_set.build_id AND build.status = 'complete'
    ORDER BY artifact_set.created_at DESC, artifact_set.id DESC
    LIMIT 1
), latest_set AS (
    SELECT artifact_set.id, artifact_set.agent_id, artifact_set.build_id, artifact_set.connector_slug, artifact_set.source_ref, artifact_set.kind, artifact_set.contract_id, artifact_set.name, artifact_set.description, artifact_set.artifact_version, artifact_set.artifact_digest, artifact_set.protocol_major, artifact_set.protocol_minor, artifact_set.features, artifact_set.interface_descriptor, artifact_set.interface_hash, artifact_set.settings_schema, artifact_set.retired_at, artifact_set.created_at, artifact_set.service_mode
    FROM installation
    JOIN installed_file ON true
    JOIN connector_artifact_sets installed_set ON installed_set.id = installed_file.artifact_set_id
    JOIN connector_artifact_sets artifact_set
      ON artifact_set.agent_id = installed_set.agent_id
     AND artifact_set.connector_slug = installed_set.connector_slug
     AND artifact_set.kind = installation.kind
     AND artifact_set.contract_id = installation.contract_id
    JOIN agent_builds build ON build.id = artifact_set.build_id
    WHERE build.status = 'complete' AND artifact_set.retired_at IS NULL
    ORDER BY artifact_set.created_at DESC, artifact_set.id DESC
    LIMIT 1
)
SELECT latest_set.id, latest_set.artifact_version, latest_set.artifact_digest,
       latest_set.protocol_major, latest_set.protocol_minor,
       latest_set.interface_descriptor, latest_set.interface_hash, latest_set.created_at,
       installed_file.platform, installed_file.artifact_set_id AS installed_artifact_set_id,
       latest_file.digest AS latest_file_digest,
       connector_interface_satisfies_need(
           latest_set.interface_descriptor,
           latest_set.contract_id,
           installation.interface_descriptor
       ) AS interface_compatible
FROM latest_set
JOIN installation ON true
LEFT JOIN installed_file ON true
LEFT JOIN connector_artifact_files latest_file
  ON latest_file.artifact_set_id = latest_set.id
 AND latest_file.platform = installed_file.platform
`

type GetConnectorArtifactStatusRow struct {
	ID                     pgtype.UUID        `json:"id"`
	ArtifactVersion        string             `json:"artifact_version"`
	ArtifactDigest         string             `json:"artifact_digest"`
	ProtocolMajor          int32              `json:"protocol_major"`
	ProtocolMinor          int32              `json:"protocol_minor"`
	InterfaceDescriptor    []byte             `json:"interface_descriptor"`
	InterfaceHash          string             `json:"interface_hash"`
	CreatedAt              pgtype.Timestamptz `json:"created_at"`
	Platform               pgtype.Text        `json:"platform"`
	InstalledArtifactSetID pgtype.UUID        `json:"installed_artifact_set_id"`
	LatestFileDigest       pgtype.Text        `json:"latest_file_digest"`
	InterfaceCompatible    bool               `json:"interface_compatible"`
}

func (q *Queries) GetConnectorArtifactStatus(ctx context.Context, connectorID pgtype.UUID) (GetConnectorArtifactStatusRow, error) {
	row := q.db.QueryRow(ctx, getConnectorArtifactStatus, connectorID)
	var i GetConnectorArtifactStatusRow
	err := row.Scan(
		&i.ID,
		&i.ArtifactVersion,
		&i.ArtifactDigest,
		&i.ProtocolMajor,
		&i.ProtocolMinor,
		&i.InterfaceDescriptor,
		&i.InterfaceHash,
		&i.CreatedAt,
		&i.Platform,
		&i.InstalledArtifactSetID,
		&i.LatestFileDigest,
		&i.InterfaceCompatible,
	)
	return i, err
}

const listCompatibleConnectorArtifactFiles = `-- name: ListCompatibleConnectorArtifactFiles :many
SELECT artifact_set.id, artifact_set.agent_id, artifact_set.build_id, artifact_set.connector_slug, artifact_set.source_ref, artifact_set.kind, artifact_set.contract_id, artifact_set.name, artifact_set.description, artifact_set.artifact_version, artifact_set.artifact_digest, artifact_set.protocol_major, artifact_set.protocol_minor, artifact_set.features, artifact_set.interface_descriptor, artifact_set.interface_hash, artifact_set.settings_schema, artifact_set.retired_at, artifact_set.created_at, artifact_set.service_mode, artifact_file.id AS file_id, artifact_file.platform,
       artifact_file.filename, artifact_file.digest, artifact_file.size_bytes,
       artifact_file.notices_digest, artifact_file.notices_size_bytes
FROM agent_resource_needs need
JOIN connector_artifact_sets artifact_set ON artifact_set.agent_id = need.agent_id
JOIN agent_builds build ON build.id = artifact_set.build_id
JOIN connector_artifact_files artifact_file ON artifact_file.artifact_set_id = artifact_set.id
WHERE need.agent_id = $1
  AND need.type = 'connector'
  AND need.slug = $2
  AND need.deleted_at IS NULL
  AND build.status = 'complete'
  AND artifact_set.retired_at IS NULL
  AND connector_interface_satisfies_need(
      artifact_set.interface_descriptor,
      artifact_set.contract_id,
      need.spec
  )
ORDER BY artifact_set.created_at DESC, artifact_set.id DESC, artifact_file.platform
`

type ListCompatibleConnectorArtifactFilesParams struct {
	AgentID  pgtype.UUID `json:"agent_id"`
	NeedSlug string      `json:"need_slug"`
}

type ListCompatibleConnectorArtifactFilesRow struct {
	ID                  pgtype.UUID        `json:"id"`
	AgentID             pgtype.UUID        `json:"agent_id"`
	BuildID             pgtype.UUID        `json:"build_id"`
	ConnectorSlug       string             `json:"connector_slug"`
	SourceRef           string             `json:"source_ref"`
	Kind                string             `json:"kind"`
	ContractID          string             `json:"contract_id"`
	Name                string             `json:"name"`
	Description         string             `json:"description"`
	ArtifactVersion     string             `json:"artifact_version"`
	ArtifactDigest      string             `json:"artifact_digest"`
	ProtocolMajor       int32              `json:"protocol_major"`
	ProtocolMinor       int32              `json:"protocol_minor"`
	Features            []string           `json:"features"`
	InterfaceDescriptor []byte             `json:"interface_descriptor"`
	InterfaceHash       string             `json:"interface_hash"`
	SettingsSchema      []byte             `json:"settings_schema"`
	RetiredAt           pgtype.Timestamptz `json:"retired_at"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	ServiceMode         pgtype.Text        `json:"service_mode"`
	FileID              pgtype.UUID        `json:"file_id"`
	Platform            string             `json:"platform"`
	Filename            string             `json:"filename"`
	Digest              string             `json:"digest"`
	SizeBytes           int64              `json:"size_bytes"`
	NoticesDigest       string             `json:"notices_digest"`
	NoticesSizeBytes    int64              `json:"notices_size_bytes"`
}

func (q *Queries) ListCompatibleConnectorArtifactFiles(ctx context.Context, arg ListCompatibleConnectorArtifactFilesParams) ([]ListCompatibleConnectorArtifactFilesRow, error) {
	rows, err := q.db.Query(ctx, listCompatibleConnectorArtifactFiles, arg.AgentID, arg.NeedSlug)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCompatibleConnectorArtifactFilesRow{}
	for rows.Next() {
		var i ListCompatibleConnectorArtifactFilesRow
		if err := rows.Scan(
			&i.ID,
			&i.AgentID,
			&i.BuildID,
			&i.ConnectorSlug,
			&i.SourceRef,
			&i.Kind,
			&i.ContractID,
			&i.Name,
			&i.Description,
			&i.ArtifactVersion,
			&i.ArtifactDigest,
			&i.ProtocolMajor,
			&i.ProtocolMinor,
			&i.Features,
			&i.InterfaceDescriptor,
			&i.InterfaceHash,
			&i.SettingsSchema,
			&i.RetiredAt,
			&i.CreatedAt,
			&i.ServiceMode,
			&i.FileID,
			&i.Platform,
			&i.Filename,
			&i.Digest,
			&i.SizeBytes,
			&i.NoticesDigest,
			&i.NoticesSizeBytes,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const queueUnreferencedConnectorArtifactBlobs = `-- name: QueueUnreferencedConnectorArtifactBlobs :execrows
WITH deletable_sets AS (
    SELECT id FROM connector_artifact_sets WHERE retired_at < now() - interval '30 days'
), referenced AS (
    SELECT artifact_set_id, digest FROM connector_artifact_files
    UNION ALL
    SELECT artifact_set_id, notices_digest FROM connector_artifact_files
)
UPDATE connector_artifact_blobs blob
SET deletion_state = 'pending', deletion_token = NULL, deletion_lease_expires_at = NULL
WHERE blob.deletion_state = 'retained'
  AND ((
      NOT EXISTS (SELECT 1 FROM referenced ref WHERE ref.digest = blob.digest)
      AND blob.created_at < now() - interval '30 days'
  ) OR (
      EXISTS (SELECT 1 FROM referenced ref WHERE ref.digest = blob.digest AND ref.artifact_set_id IN (SELECT id FROM deletable_sets))
      AND NOT EXISTS (SELECT 1 FROM referenced ref WHERE ref.digest = blob.digest AND ref.artifact_set_id NOT IN (SELECT id FROM deletable_sets))
  ))
`

func (q *Queries) QueueUnreferencedConnectorArtifactBlobs(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, queueUnreferencedConnectorArtifactBlobs)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const refreshConnectorArtifactRetention = `-- name: RefreshConnectorArtifactRetention :exec
WITH ranked AS (
    SELECT artifact_set.id,
           dense_rank() OVER (
               PARTITION BY artifact_set.agent_id, artifact_set.connector_slug
               ORDER BY artifact_set.created_at DESC, artifact_set.id DESC
           ) AS recency
    FROM connector_artifact_sets artifact_set
    JOIN agent_builds build ON build.id = artifact_set.build_id
    WHERE build.status = 'complete'
), retained AS (
    SELECT ranked.id FROM ranked WHERE ranked.recency <= 3
    UNION
    SELECT artifact_set.id
    FROM connector_artifact_sets artifact_set
    JOIN connector_resources installation ON installation.artifact_set_id = artifact_set.id
    WHERE installation.lifecycle = 'active' OR installation.active_observation_state = 'known'
    UNION
    SELECT artifact_set.id
    FROM connector_artifact_sets artifact_set
    JOIN connector_resources installation ON installation.rollback_artifact_set_id = artifact_set.id
    WHERE installation.lifecycle = 'active' OR installation.rollback_observation_state = 'known'
    UNION
    SELECT artifact_file.artifact_set_id
    FROM host_management_jobs management_job
    JOIN connector_artifact_files artifact_file ON artifact_file.id = management_job.artifact_file_id
    UNION
    SELECT artifact_set.id
    FROM connector_artifact_sets artifact_set
    WHERE EXISTS (
        SELECT 1 FROM agent_builds rollback
        WHERE rollback.rollback_target_id = artifact_set.build_id
    )
), refreshed AS (
    UPDATE connector_artifact_sets artifact_set
    SET retired_at = NULL
    WHERE artifact_set.id IN (SELECT id FROM retained)
      AND artifact_set.retired_at IS NOT NULL
)
UPDATE connector_artifact_sets artifact_set
SET retired_at = now()
WHERE artifact_set.id NOT IN (SELECT id FROM retained)
  AND artifact_set.retired_at IS NULL
  AND EXISTS (
      SELECT 1 FROM agent_builds build
      WHERE build.id = artifact_set.build_id AND build.status <> 'building'
  )
`

func (q *Queries) RefreshConnectorArtifactRetention(ctx context.Context) error {
	_, err := q.db.Exec(ctx, refreshConnectorArtifactRetention)
	return err
}

const releaseConnectorArtifactBlobDeletion = `-- name: ReleaseConnectorArtifactBlobDeletion :execrows
UPDATE connector_artifact_blobs
SET deletion_state = 'pending', deletion_token = NULL, deletion_lease_expires_at = NULL,
    deletion_error = $1
WHERE digest = $2 AND deletion_state = 'deleting' AND deletion_token = $3
  AND deletion_lease_expires_at > now()
`

type ReleaseConnectorArtifactBlobDeletionParams struct {
	DeletionError pgtype.Text `json:"deletion_error"`
	Digest        string      `json:"digest"`
	DeletionToken pgtype.UUID `json:"deletion_token"`
}

func (q *Queries) ReleaseConnectorArtifactBlobDeletion(ctx context.Context, arg ReleaseConnectorArtifactBlobDeletionParams) (int64, error) {
	result, err := q.db.Exec(ctx, releaseConnectorArtifactBlobDeletion, arg.DeletionError, arg.Digest, arg.DeletionToken)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const upsertConnectorArtifactBlob = `-- name: UpsertConnectorArtifactBlob :one

INSERT INTO connector_artifact_blobs (digest, object_key, size_bytes, media_type, deletion_state, deletion_attempts)
VALUES ($1, $2, $3, $4, 'retained', 0)
ON CONFLICT (digest) DO UPDATE SET
    deletion_state = 'retained', deletion_token = NULL, deletion_lease_expires_at = NULL, deletion_error = NULL
WHERE connector_artifact_blobs.object_key = EXCLUDED.object_key
  AND connector_artifact_blobs.size_bytes = EXCLUDED.size_bytes
  AND connector_artifact_blobs.media_type = EXCLUDED.media_type
RETURNING digest, object_key, size_bytes, media_type, created_at, deletion_state, deletion_token, deletion_lease_expires_at, deletion_error, deletion_attempts
`

type UpsertConnectorArtifactBlobParams struct {
	Digest    string `json:"digest"`
	ObjectKey string `json:"object_key"`
	SizeBytes int64  `json:"size_bytes"`
	MediaType string `json:"media_type"`
}

// Connector artifact candidates, authorized downloads, and retention.
func (q *Queries) UpsertConnectorArtifactBlob(ctx context.Context, arg UpsertConnectorArtifactBlobParams) (ConnectorArtifactBlob, error) {
	row := q.db.QueryRow(ctx, upsertConnectorArtifactBlob,
		arg.Digest,
		arg.ObjectKey,
		arg.SizeBytes,
		arg.MediaType,
	)
	var i ConnectorArtifactBlob
	err := row.Scan(
		&i.Digest,
		&i.ObjectKey,
		&i.SizeBytes,
		&i.MediaType,
		&i.CreatedAt,
		&i.DeletionState,
		&i.DeletionToken,
		&i.DeletionLeaseExpiresAt,
		&i.DeletionError,
		&i.DeletionAttempts,
	)
	return i, err
}
