// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: conversations.sql

package dbq

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createA2AConversation = `-- name: CreateA2AConversation :one
INSERT INTO agent_conversations (agent_id, user_id, source, title, metadata, settings)
VALUES ($1, $2, 'a2a', $3, '{}'::jsonb, '{}'::jsonb)
RETURNING id, agent_id, bridge_id, user_id, source, external_id, title, metadata, settings, context_checkpoint_message_id, created_at, updated_at
`

type CreateA2AConversationParams struct {
	AgentID pgtype.UUID `json:"agent_id"`
	UserID  pgtype.UUID `json:"user_id"`
	Title   string      `json:"title"`
}

// A2A: each new context (caller passed no contextId) is its own
// conversation on the *called* agent, owned by the original user
// (user_id may be NULL for anonymous external-MCP callers). source is
// always 'a2a' so the partial DM index never collapses these. Plain
// INSERT — no upsert, every call without a contextId is a fresh thread.
func (q *Queries) CreateA2AConversation(ctx context.Context, arg CreateA2AConversationParams) (AgentConversation, error) {
	row := q.db.QueryRow(ctx, createA2AConversation, arg.AgentID, arg.UserID, arg.Title)
	var i AgentConversation
	err := row.Scan(
		&i.ID,
		&i.AgentID,
		&i.BridgeID,
		&i.UserID,
		&i.Source,
		&i.ExternalID,
		&i.Title,
		&i.Metadata,
		&i.Settings,
		&i.ContextCheckpointMessageID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createMCPA2AConversation = `-- name: CreateMCPA2AConversation :one
INSERT INTO agent_conversations (agent_id, user_id, source, title, metadata, settings)
VALUES ($1, $2, 'a2a', $3, $4, '{}'::jsonb)
RETURNING id, agent_id, bridge_id, user_id, source, external_id, title, metadata, settings, context_checkpoint_message_id, created_at, updated_at
`

type CreateMCPA2AConversationParams struct {
	AgentID  pgtype.UUID `json:"agent_id"`
	UserID   pgtype.UUID `json:"user_id"`
	Title    string      `json:"title"`
	Metadata []byte      `json:"metadata"`
}

// MCP continuations carry a server-generated principal binding in metadata.
// Callers cannot choose this value; subsequent context/task access must match it.
func (q *Queries) CreateMCPA2AConversation(ctx context.Context, arg CreateMCPA2AConversationParams) (AgentConversation, error) {
	row := q.db.QueryRow(ctx, createMCPA2AConversation,
		arg.AgentID,
		arg.UserID,
		arg.Title,
		arg.Metadata,
	)
	var i AgentConversation
	err := row.Scan(
		&i.ID,
		&i.AgentID,
		&i.BridgeID,
		&i.UserID,
		&i.Source,
		&i.ExternalID,
		&i.Title,
		&i.Metadata,
		&i.Settings,
		&i.ContextCheckpointMessageID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createWebConversation = `-- name: CreateWebConversation :one
INSERT INTO agent_conversations (agent_id, user_id, source, title, metadata, settings)
VALUES ($1, $2, 'web', $3, '{}'::jsonb, '{}'::jsonb)
RETURNING id, agent_id, bridge_id, user_id, source, external_id, title, metadata, settings, context_checkpoint_message_id, created_at, updated_at
`

type CreateWebConversationParams struct {
	AgentID pgtype.UUID `json:"agent_id"`
	UserID  pgtype.UUID `json:"user_id"`
	Title   string      `json:"title"`
}

// Web is multi-conversation: every call is a fresh thread owned by the
// user. Plain INSERT, no upsert — the row UUID is the identity and the
// client addresses one by id on each prompt.
func (q *Queries) CreateWebConversation(ctx context.Context, arg CreateWebConversationParams) (AgentConversation, error) {
	row := q.db.QueryRow(ctx, createWebConversation, arg.AgentID, arg.UserID, arg.Title)
	var i AgentConversation
	err := row.Scan(
		&i.ID,
		&i.AgentID,
		&i.BridgeID,
		&i.UserID,
		&i.Source,
		&i.ExternalID,
		&i.Title,
		&i.Metadata,
		&i.Settings,
		&i.ContextCheckpointMessageID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteConversation = `-- name: DeleteConversation :exec
DELETE FROM agent_conversations WHERE id = $1
`

func (q *Queries) DeleteConversation(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteConversation, id)
	return err
}

const deleteExpiredAnonA2AConversations = `-- name: DeleteExpiredAnonA2AConversations :execrows
DELETE FROM agent_conversations
WHERE user_id IS NULL
  AND source = 'a2a'
  AND updated_at < NOW() - make_interval(secs => $1::int)
`

// Sweeper: anonymous A2A conversations (no owning user, minted for
// unauthenticated external-MCP callers) have no UI to resume them and
// would otherwise grow unbounded. Drop any idle past the TTL; the row
// delete cascades to agent_messages via FK. (user_id IS NULL AND
// source='a2a') is the precise anon-A2A key — authed A2A convs and
// bridge convs are untouched.
func (q *Queries) DeleteExpiredAnonA2AConversations(ctx context.Context, ttlSeconds int32) (int64, error) {
	result, err := q.db.Exec(ctx, deleteExpiredAnonA2AConversations, ttlSeconds)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getConversationByID = `-- name: GetConversationByID :one
SELECT id, agent_id, bridge_id, user_id, source, external_id, title, metadata, settings, context_checkpoint_message_id, created_at, updated_at FROM agent_conversations WHERE id = $1
`

func (q *Queries) GetConversationByID(ctx context.Context, id pgtype.UUID) (AgentConversation, error) {
	row := q.db.QueryRow(ctx, getConversationByID, id)
	var i AgentConversation
	err := row.Scan(
		&i.ID,
		&i.AgentID,
		&i.BridgeID,
		&i.UserID,
		&i.Source,
		&i.ExternalID,
		&i.Title,
		&i.Metadata,
		&i.Settings,
		&i.ContextCheckpointMessageID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getConversationByIDAndAgent = `-- name: GetConversationByIDAndAgent :one
SELECT id, agent_id, bridge_id, user_id, source, external_id, title, metadata, settings, context_checkpoint_message_id, created_at, updated_at FROM agent_conversations
WHERE id = $1 AND agent_id = $2
`

type GetConversationByIDAndAgentParams struct {
	ID      pgtype.UUID `json:"id"`
	AgentID pgtype.UUID `json:"agent_id"`
}

func (q *Queries) GetConversationByIDAndAgent(ctx context.Context, arg GetConversationByIDAndAgentParams) (AgentConversation, error) {
	row := q.db.QueryRow(ctx, getConversationByIDAndAgent, arg.ID, arg.AgentID)
	var i AgentConversation
	err := row.Scan(
		&i.ID,
		&i.AgentID,
		&i.BridgeID,
		&i.UserID,
		&i.Source,
		&i.ExternalID,
		&i.Title,
		&i.Metadata,
		&i.Settings,
		&i.ContextCheckpointMessageID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getConversationByIDAndAgentForUpdate = `-- name: GetConversationByIDAndAgentForUpdate :one
SELECT id, agent_id, bridge_id, user_id, source, external_id, title, metadata, settings, context_checkpoint_message_id, created_at, updated_at FROM agent_conversations
WHERE id = $1 AND agent_id = $2
FOR UPDATE
`

type GetConversationByIDAndAgentForUpdateParams struct {
	ID      pgtype.UUID `json:"id"`
	AgentID pgtype.UUID `json:"agent_id"`
}

// Session writes lock the parent row before inspecting context state. Child
// inserts take a foreign-key key-share lock, so this also orders every message
// insert against checkpoint advancement across replicas.
func (q *Queries) GetConversationByIDAndAgentForUpdate(ctx context.Context, arg GetConversationByIDAndAgentForUpdateParams) (AgentConversation, error) {
	row := q.db.QueryRow(ctx, getConversationByIDAndAgentForUpdate, arg.ID, arg.AgentID)
	var i AgentConversation
	err := row.Scan(
		&i.ID,
		&i.AgentID,
		&i.BridgeID,
		&i.UserID,
		&i.Source,
		&i.ExternalID,
		&i.Title,
		&i.Metadata,
		&i.Settings,
		&i.ContextCheckpointMessageID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getConversationBySource = `-- name: GetConversationBySource :one
SELECT id, agent_id, bridge_id, user_id, source, external_id, title, metadata, settings, context_checkpoint_message_id, created_at, updated_at FROM agent_conversations
WHERE agent_id = $1 AND user_id = $2 AND source = $3
`

type GetConversationBySourceParams struct {
	AgentID pgtype.UUID `json:"agent_id"`
	UserID  pgtype.UUID `json:"user_id"`
	Source  string      `json:"source"`
}

// Non-creating lookup used by the bridge manager when it needs to read
// per-chat settings before any new conversation row would be created.
func (q *Queries) GetConversationBySource(ctx context.Context, arg GetConversationBySourceParams) (AgentConversation, error) {
	row := q.db.QueryRow(ctx, getConversationBySource, arg.AgentID, arg.UserID, arg.Source)
	var i AgentConversation
	err := row.Scan(
		&i.ID,
		&i.AgentID,
		&i.BridgeID,
		&i.UserID,
		&i.Source,
		&i.ExternalID,
		&i.Title,
		&i.Metadata,
		&i.Settings,
		&i.ContextCheckpointMessageID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getOrCreateBridgeAuthedConversation = `-- name: GetOrCreateBridgeAuthedConversation :one
INSERT INTO agent_conversations (agent_id, user_id, source, title, bridge_id, external_id, metadata, settings)
VALUES ($1, $2, 'bridge', $3, $4, $5, '{}'::jsonb, '{}'::jsonb)
ON CONFLICT (agent_id, user_id, source, external_id, bridge_id) WHERE user_id IS NOT NULL AND external_id IS NOT NULL DO UPDATE
    SET updated_at = now()
RETURNING id, agent_id, bridge_id, user_id, source, external_id, title, metadata, settings, context_checkpoint_message_id, created_at, updated_at
`

type GetOrCreateBridgeAuthedConversationParams struct {
	AgentID    pgtype.UUID `json:"agent_id"`
	UserID     pgtype.UUID `json:"user_id"`
	Title      string      `json:"title"`
	BridgeID   pgtype.UUID `json:"bridge_id"`
	ExternalID pgtype.Text `json:"external_id"`
}

// Authed bridge: one thread per (agent, user, bridge, external_id) —
// the same user reaching the same agent through a different bridge is
// a different conversation, and the same user in a different chat is
// also a different conversation (external_id covers that axis).
// Upserts on idx_conversations_bridge_authed; conflict target must
// match the partial index's keys + predicate so Postgres infers it.
func (q *Queries) GetOrCreateBridgeAuthedConversation(ctx context.Context, arg GetOrCreateBridgeAuthedConversationParams) (AgentConversation, error) {
	row := q.db.QueryRow(ctx, getOrCreateBridgeAuthedConversation,
		arg.AgentID,
		arg.UserID,
		arg.Title,
		arg.BridgeID,
		arg.ExternalID,
	)
	var i AgentConversation
	err := row.Scan(
		&i.ID,
		&i.AgentID,
		&i.BridgeID,
		&i.UserID,
		&i.Source,
		&i.ExternalID,
		&i.Title,
		&i.Metadata,
		&i.Settings,
		&i.ContextCheckpointMessageID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAllWebConversationsByUser = `-- name: ListAllWebConversationsByUser :many
SELECT id, agent_id, bridge_id, user_id, source, external_id, title, metadata, settings, context_checkpoint_message_id, created_at, updated_at FROM agent_conversations
WHERE user_id = $1 AND source = 'web'
ORDER BY updated_at DESC
`

// Every web conversation the user owns, across all agents — backs the
// global sidebar list. Only source='web' (bridge is delivered over the
// bridge, a2a is sibling transport); the row carries agent_id so the UI
// can label each entry with its agent's name.
func (q *Queries) ListAllWebConversationsByUser(ctx context.Context, userID pgtype.UUID) ([]AgentConversation, error) {
	rows, err := q.db.Query(ctx, listAllWebConversationsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AgentConversation{}
	for rows.Next() {
		var i AgentConversation
		if err := rows.Scan(
			&i.ID,
			&i.AgentID,
			&i.BridgeID,
			&i.UserID,
			&i.Source,
			&i.ExternalID,
			&i.Title,
			&i.Metadata,
			&i.Settings,
			&i.ContextCheckpointMessageID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listConversationFeed = `-- name: ListConversationFeed :many
SELECT kind, id, agent_id, title, updated_at, status FROM (
    SELECT 'agent'::text AS kind, ac.id, ac.agent_id, ac.title, ac.updated_at, ''::text AS status
    FROM agent_conversations ac
    WHERE ac.user_id = $1 AND ac.source = 'web'
      AND (ac.updated_at < $2 OR (ac.updated_at = $2 AND ac.id < $3))
    UNION ALL
    SELECT 'system'::text AS kind, sc.id, NULL::uuid AS agent_id, sc.title, sc.updated_at, sc.status
    FROM system_conversations sc
    WHERE sc.user_id = $1 AND sc.source = 'web'
      AND (sc.updated_at < $2 OR (sc.updated_at = $2 AND sc.id < $3))
) feed
ORDER BY 5 DESC, 2 DESC
LIMIT $4
`

type ListConversationFeedParams struct {
	UserID        pgtype.UUID        `json:"user_id"`
	CursorUpdated pgtype.Timestamptz `json:"cursor_updated"`
	CursorID      pgtype.UUID        `json:"cursor_id"`
	Lim           int32              `json:"lim"`
}

type ListConversationFeedRow struct {
	Kind      string             `json:"kind"`
	ID        pgtype.UUID        `json:"id"`
	AgentID   pgtype.UUID        `json:"agent_id"`
	Title     string             `json:"title"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
	Status    string             `json:"status"`
}

// Merged sidebar feed: the user's web agent-conversations + system
// conversations as one stream, keyset-paginated by (updated_at, id) DESC so
// the windowed sidebar can page without loading everything. The first page
// passes cursor_updated='infinity' and cursor_id = the max uuid.
func (q *Queries) ListConversationFeed(ctx context.Context, arg ListConversationFeedParams) ([]ListConversationFeedRow, error) {
	rows, err := q.db.Query(ctx, listConversationFeed,
		arg.UserID,
		arg.CursorUpdated,
		arg.CursorID,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListConversationFeedRow{}
	for rows.Next() {
		var i ListConversationFeedRow
		if err := rows.Scan(
			&i.Kind,
			&i.ID,
			&i.AgentID,
			&i.Title,
			&i.UpdatedAt,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listConversationsByAgent = `-- name: ListConversationsByAgent :many
SELECT id, agent_id, bridge_id, user_id, source, external_id, title, metadata, settings, context_checkpoint_message_id, created_at, updated_at FROM agent_conversations
WHERE agent_id = $1 AND user_id = $2 AND source <> 'a2a'
ORDER BY updated_at DESC
`

type ListConversationsByAgentParams struct {
	AgentID pgtype.UUID `json:"agent_id"`
	UserID  pgtype.UUID `json:"user_id"`
}

// Returns conversations for the given agent visible to the given user in
// the web UI. source='a2a' rows are a sibling-call transport detail (the
// called agent never "chats" them) and are excluded — surfacing them
// would also expose a delegated suspension as an actionable card here.
func (q *Queries) ListConversationsByAgent(ctx context.Context, arg ListConversationsByAgentParams) ([]AgentConversation, error) {
	rows, err := q.db.Query(ctx, listConversationsByAgent, arg.AgentID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AgentConversation{}
	for rows.Next() {
		var i AgentConversation
		if err := rows.Scan(
			&i.ID,
			&i.AgentID,
			&i.BridgeID,
			&i.UserID,
			&i.Source,
			&i.ExternalID,
			&i.Title,
			&i.Metadata,
			&i.Settings,
			&i.ContextCheckpointMessageID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateConversationSettings = `-- name: UpdateConversationSettings :exec
UPDATE agent_conversations
SET settings = settings || $1::jsonb,
    updated_at = now()
WHERE id = $2
`

type UpdateConversationSettingsParams struct {
	Patch []byte      `json:"patch"`
	ID    pgtype.UUID `json:"id"`
}

// Merges a JSONB patch into agent_conversations.settings. Used by the
// /echo slash command and any future per-chat preferences.
func (q *Queries) UpdateConversationSettings(ctx context.Context, arg UpdateConversationSettingsParams) error {
	_, err := q.db.Exec(ctx, updateConversationSettings, arg.Patch, arg.ID)
	return err
}
