// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: webauthn.sql

package dbq

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const consumeCeremony = `-- name: ConsumeCeremony :one
DELETE FROM webauthn_ceremonies
WHERE id = $1 AND expires_at > now()
RETURNING id, user_id, kind, session_data, created_at, expires_at
`

func (q *Queries) ConsumeCeremony(ctx context.Context, id pgtype.UUID) (WebauthnCeremony, error) {
	row := q.db.QueryRow(ctx, consumeCeremony, id)
	var i WebauthnCeremony
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Kind,
		&i.SessionData,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const countCredentialsByUserID = `-- name: CountCredentialsByUserID :one
SELECT count(*) FROM webauthn_credentials WHERE user_id = $1
`

func (q *Queries) CountCredentialsByUserID(ctx context.Context, userID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countCredentialsByUserID, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createCeremony = `-- name: CreateCeremony :one
INSERT INTO webauthn_ceremonies (user_id, kind, session_data, expires_at)
VALUES ($1, $2, $3, now() + interval '5 minutes')
RETURNING id
`

type CreateCeremonyParams struct {
	UserID      pgtype.UUID `json:"user_id"`
	Kind        string      `json:"kind"`
	SessionData []byte      `json:"session_data"`
}

func (q *Queries) CreateCeremony(ctx context.Context, arg CreateCeremonyParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, createCeremony, arg.UserID, arg.Kind, arg.SessionData)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const createCredential = `-- name: CreateCredential :one
INSERT INTO webauthn_credentials (
    user_id, credential_id, public_key, attestation_type, aaguid,
    sign_count, transports, backup_eligible, backup_state, clone_warning,
    friendly_name
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
RETURNING id, user_id, credential_id, public_key, attestation_type, aaguid, sign_count, transports, backup_eligible, backup_state, clone_warning, friendly_name, created_at, last_used_at
`

type CreateCredentialParams struct {
	UserID          pgtype.UUID `json:"user_id"`
	CredentialID    []byte      `json:"credential_id"`
	PublicKey       []byte      `json:"public_key"`
	AttestationType string      `json:"attestation_type"`
	Aaguid          []byte      `json:"aaguid"`
	SignCount       int64       `json:"sign_count"`
	Transports      []string    `json:"transports"`
	BackupEligible  bool        `json:"backup_eligible"`
	BackupState     bool        `json:"backup_state"`
	CloneWarning    bool        `json:"clone_warning"`
	FriendlyName    string      `json:"friendly_name"`
}

func (q *Queries) CreateCredential(ctx context.Context, arg CreateCredentialParams) (WebauthnCredential, error) {
	row := q.db.QueryRow(ctx, createCredential,
		arg.UserID,
		arg.CredentialID,
		arg.PublicKey,
		arg.AttestationType,
		arg.Aaguid,
		arg.SignCount,
		arg.Transports,
		arg.BackupEligible,
		arg.BackupState,
		arg.CloneWarning,
		arg.FriendlyName,
	)
	var i WebauthnCredential
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CredentialID,
		&i.PublicKey,
		&i.AttestationType,
		&i.Aaguid,
		&i.SignCount,
		&i.Transports,
		&i.BackupEligible,
		&i.BackupState,
		&i.CloneWarning,
		&i.FriendlyName,
		&i.CreatedAt,
		&i.LastUsedAt,
	)
	return i, err
}

const deleteCredential = `-- name: DeleteCredential :exec
DELETE FROM webauthn_credentials WHERE id = $1 AND user_id = $2
`

type DeleteCredentialParams struct {
	ID     pgtype.UUID `json:"id"`
	UserID pgtype.UUID `json:"user_id"`
}

func (q *Queries) DeleteCredential(ctx context.Context, arg DeleteCredentialParams) error {
	_, err := q.db.Exec(ctx, deleteCredential, arg.ID, arg.UserID)
	return err
}

const deleteExpiredCeremonies = `-- name: DeleteExpiredCeremonies :exec
DELETE FROM webauthn_ceremonies WHERE expires_at <= now()
`

func (q *Queries) DeleteExpiredCeremonies(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteExpiredCeremonies)
	return err
}

const getUserByCredentialID = `-- name: GetUserByCredentialID :one
SELECT users.id, users.email, users.display_name, users.tenant_role, users.password_hash, users.oidc_sub, users.must_change_password, users.created_at, users.updated_at, users.auth_epoch FROM users
JOIN webauthn_credentials c ON c.user_id = users.id
WHERE c.credential_id = $1
`

// Resolve the owning user from a credential id — used by discoverable login to
// fetch the live user row after the assertion verifies.
func (q *Queries) GetUserByCredentialID(ctx context.Context, credentialID []byte) (User, error) {
	row := q.db.QueryRow(ctx, getUserByCredentialID, credentialID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.DisplayName,
		&i.TenantRole,
		&i.PasswordHash,
		&i.OidcSub,
		&i.MustChangePassword,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AuthEpoch,
	)
	return i, err
}

const listCredentialsByUserID = `-- name: ListCredentialsByUserID :many
SELECT id, user_id, credential_id, public_key, attestation_type, aaguid, sign_count, transports, backup_eligible, backup_state, clone_warning, friendly_name, created_at, last_used_at FROM webauthn_credentials WHERE user_id = $1 ORDER BY created_at
`

func (q *Queries) ListCredentialsByUserID(ctx context.Context, userID pgtype.UUID) ([]WebauthnCredential, error) {
	rows, err := q.db.Query(ctx, listCredentialsByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WebauthnCredential{}
	for rows.Next() {
		var i WebauthnCredential
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.CredentialID,
			&i.PublicKey,
			&i.AttestationType,
			&i.Aaguid,
			&i.SignCount,
			&i.Transports,
			&i.BackupEligible,
			&i.BackupState,
			&i.CloneWarning,
			&i.FriendlyName,
			&i.CreatedAt,
			&i.LastUsedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const renameCredential = `-- name: RenameCredential :exec
UPDATE webauthn_credentials SET friendly_name = $1
WHERE id = $2 AND user_id = $3
`

type RenameCredentialParams struct {
	FriendlyName string      `json:"friendly_name"`
	ID           pgtype.UUID `json:"id"`
	UserID       pgtype.UUID `json:"user_id"`
}

func (q *Queries) RenameCredential(ctx context.Context, arg RenameCredentialParams) error {
	_, err := q.db.Exec(ctx, renameCredential, arg.FriendlyName, arg.ID, arg.UserID)
	return err
}

const updateCredentialSignCount = `-- name: UpdateCredentialSignCount :exec
UPDATE webauthn_credentials
SET sign_count = $1, clone_warning = $2,
    backup_state = $3, last_used_at = now()
WHERE credential_id = $4
`

type UpdateCredentialSignCountParams struct {
	SignCount    int64  `json:"sign_count"`
	CloneWarning bool   `json:"clone_warning"`
	BackupState  bool   `json:"backup_state"`
	CredentialID []byte `json:"credential_id"`
}

func (q *Queries) UpdateCredentialSignCount(ctx context.Context, arg UpdateCredentialSignCountParams) error {
	_, err := q.db.Exec(ctx, updateCredentialSignCount,
		arg.SignCount,
		arg.CloneWarning,
		arg.BackupState,
		arg.CredentialID,
	)
	return err
}
