// Package scaffold materializes agent project templates.
package scaffold

import (
	"embed"
	"fmt"
	"os"
	"path/filepath"
	"text/template"
)

//go:embed templates/*
var templates embed.FS

// ScaffoldData holds values substituted into templates.
type ScaffoldData struct {
	AgentID         string // UUID
	Module          string // Go module name for the agent (typically "agent")
	GoVersion       string // e.g., "1.24"
	AgentSDKVersion string // displayed in the agent's go.mod require line (informational — replace directives are unconditional)
	AgentBaseImage  string // runtime base image referenced by the agent's Dockerfile (FROM line). Threaded from cfg.AgentBaseImage so operators can pin it (typically a versioned ghcr ref).
}

// templateFile maps a template name to its output path relative to the target directory.
type templateFile struct {
	Template string // path within embedded FS
	Output   string // output path relative to target dir
}

var templateFiles = []templateFile{
	{"templates/main.go.tmpl", "main.go"},
	{"templates/scaffold_gen.go.tmpl", "scaffold_gen.go"},
	{"templates/go.mod.tmpl", "go.mod"},
	{"templates/sqlc.yaml.tmpl", "sqlc.yaml"},
	{"templates/layout.templ.tmpl", "views/layout.templ"},
	{"templates/index.templ.tmpl", "views/index.templ"},
	// views/viewmodel.go holds the view-model types templ files render
	// over (HomeView and any others the LLM adds). The convention in
	// the package doc keeps templates free of domain imports — see
	// the MVC split notes in agentsdk/llms.md.
	{"templates/views_viewmodel.go.tmpl", "views/viewmodel.go"},
	// views/assets.go holds the //go:embed for the compiled Tailwind
	// stylesheet plus the content-hashed URL the layout references.
	{"templates/views_assets.go.tmpl", "views/assets.go"},
	// handlers/home.go is the controller layer — it imports views and
	// (eventually) domain packages, converts model types to view-models,
	// and renders. Domain packages never import handlers or views, so
	// no cycle can form.
	{"templates/handlers_home.go.tmpl", "handlers/home.go"},
	// AGENTS.md is the scaffold's "how this agent is built" doc —
	// workspace structure, MVC cycle rule, build chain, short UI
	// section. Airlock-managed: rendered here at scaffold time and
	// regenerated by build housekeeping (builder.runHousekeeping) so
	// previously built agents pick up doc updates. The agentsdk API
	// reference (/libs/agentsdk/llms.md) is the orthogonal half: this
	// file says how to wire things together, llms.md says what the SDK
	// gives you.
	{"templates/AGENTS.md.tmpl", "AGENTS.md"},
	// styles/app.css is the Tailwind source. The build runs
	//   tailwindcss -i styles/app.css -o views/static/app.css --minify
	// and the agent embeds the output via views/assets.go.
	{"templates/app.css.tmpl", "styles/app.css"},
	// views/static/app.css is a placeholder so views/assets.go's
	// //go:embed compiles on a fresh checkout. The Docker build's
	// tailwindcss step overwrites it before `go build` runs.
	{"templates/views_static_app.css.tmpl", "views/static/app.css"},
	{"templates/db_migrations_doc.go.tmpl", "db/migrations/doc.go"},
	// Dockerfile is committed so users can `docker build .` locally
	// after cloning. Airlock-side builds regenerate it into a temp dir
	// and use `docker build -f` so the committed copy never drifts due
	// to airlock-template changes mid-build.
	{"templates/Dockerfile.tmpl", "Dockerfile"},
	// Template is named without a leading dot because go:embed glob
	// patterns skip dotfiles; the output file is .gitignore.
	{"templates/gitignore.tmpl", ".gitignore"},
}

// staticFiles are copied verbatim into the agent (NOT template-rendered). Their
// content may contain text that isn't valid text/template syntax (license bodies
// can include "{{"), so they must bypass ParseFS.
var staticFiles = []templateFile{
	// THIRD_PARTY_NOTICES.md attributes the open-source the agent bundles (its
	// Go deps + the Tailwind/DaisyUI CSS compiled into the served stylesheet).
	// Generated by scripts/gen-notices.sh; required by those licenses to travel
	// with the distributed agent binary.
	{"templates/THIRD_PARTY_NOTICES.md", "THIRD_PARTY_NOTICES.md"},
}

// emptyDirs are created with a .gitkeep file so they survive git operations.
var emptyDirs = []string{
	"db/queries",
}

// GenerateDockerfile renders the Dockerfile template into dir/Dockerfile.
// Called by the build pipeline before every docker build so agents always
// get the latest Dockerfile — even on upgrades of previously-built agents.
func GenerateDockerfile(dir string, data ScaffoldData) error {
	if data.AgentSDKVersion == "" {
		return fmt.Errorf("scaffold: AgentSDKVersion is required")
	}
	if data.AgentBaseImage == "" {
		return fmt.Errorf("scaffold: AgentBaseImage is required")
	}
	tmpl, err := template.New("Dockerfile.tmpl").
		Option("missingkey=error").
		ParseFS(templates, "templates/Dockerfile.tmpl")
	if err != nil {
		return fmt.Errorf("parse Dockerfile template: %w", err)
	}

	outPath := filepath.Join(dir, "Dockerfile")
	f, err := os.Create(outPath)
	if err != nil {
		return fmt.Errorf("create Dockerfile: %w", err)
	}
	defer f.Close()

	if err := tmpl.Execute(f, data); err != nil {
		return fmt.Errorf("render Dockerfile: %w", err)
	}
	return nil
}

// GenerateAgentsMD renders the AGENTS.md template into dir/AGENTS.md.
// Called at scaffold time and by the build pipeline's housekeeping so
// previously built agents pick up doc updates — AGENTS.md is
// airlock-managed, not agent-owned. The template carries no substitutions
// today, but it's rendered (not copied) so future {{.Field}} additions Just
// Work.
func GenerateAgentsMD(dir string, data ScaffoldData) error {
	tmpl, err := template.New("AGENTS.md.tmpl").
		Option("missingkey=error").
		ParseFS(templates, "templates/AGENTS.md.tmpl")
	if err != nil {
		return fmt.Errorf("parse AGENTS.md template: %w", err)
	}

	outPath := filepath.Join(dir, "AGENTS.md")
	f, err := os.Create(outPath)
	if err != nil {
		return fmt.Errorf("create AGENTS.md: %w", err)
	}
	defer f.Close()

	if err := tmpl.Execute(f, data); err != nil {
		return fmt.Errorf("render AGENTS.md: %w", err)
	}
	return nil
}

// Materialize renders all scaffold templates into dir using data.
// Panics if a template references a missing field in data.
func Materialize(dir string, data ScaffoldData) error {
	if data.AgentSDKVersion == "" {
		return fmt.Errorf("scaffold: AgentSDKVersion is required (callers should pass agentsdk.Version with v prefix)")
	}
	tmpl, err := template.New("").
		Option("missingkey=error").
		ParseFS(templates, "templates/*.tmpl")
	if err != nil {
		return fmt.Errorf("parse templates: %w", err)
	}

	// Create empty directories with .gitkeep so they survive git operations.
	for _, d := range emptyDirs {
		dirPath := filepath.Join(dir, d)
		if err := os.MkdirAll(dirPath, 0o755); err != nil {
			return fmt.Errorf("mkdir %s: %w", d, err)
		}
		if err := os.WriteFile(filepath.Join(dirPath, ".gitkeep"), nil, 0o644); err != nil {
			return fmt.Errorf("gitkeep %s: %w", d, err)
		}
	}

	// Render each template
	for _, tf := range templateFiles {
		outPath := filepath.Join(dir, tf.Output)

		if err := os.MkdirAll(filepath.Dir(outPath), 0o755); err != nil {
			return fmt.Errorf("mkdir for %s: %w", tf.Output, err)
		}

		f, err := os.Create(outPath)
		if err != nil {
			return fmt.Errorf("create %s: %w", tf.Output, err)
		}

		t := tmpl.Lookup(filepath.Base(tf.Template))
		if t == nil {
			f.Close()
			return fmt.Errorf("template %s not found", tf.Template)
		}

		if err := t.Execute(f, data); err != nil {
			f.Close()
			return fmt.Errorf("render %s: %w", tf.Output, err)
		}

		if err := f.Close(); err != nil {
			return fmt.Errorf("close %s: %w", tf.Output, err)
		}
	}

	// Copy static (non-rendered) files verbatim.
	for _, sf := range staticFiles {
		outPath := filepath.Join(dir, sf.Output)
		if err := os.MkdirAll(filepath.Dir(outPath), 0o755); err != nil {
			return fmt.Errorf("mkdir for %s: %w", sf.Output, err)
		}
		b, err := templates.ReadFile(sf.Template)
		if err != nil {
			return fmt.Errorf("read static %s: %w", sf.Template, err)
		}
		if err := os.WriteFile(outPath, b, 0o644); err != nil {
			return fmt.Errorf("write %s: %w", sf.Output, err)
		}
	}

	return nil
}
