// licenses.mjs — frontend third-party license gate + notices generator.
//
//   node scripts/licenses.mjs check   exit non-zero if any production dependency
//                                      carries a non-allowlisted license.
//   node scripts/licenses.mjs gen      write public/THIRD_PARTY_NOTICES.md with
//                                      each prod dep's license text (shipped in
//                                      dist/ → served by Caddy, satisfying the
//                                      MIT/BSD/Apache attribution requirement).
//
// Source of truth is `pnpm licenses list --prod --json`. Fails closed: a license
// id that isn't recognised as permissive is a failure until vetted.
import { execSync } from 'node:child_process'
import { readFileSync, writeFileSync, existsSync, mkdirSync } from 'node:fs'
import { join } from 'node:path'

const ALLOW = new Set([
  'MIT', 'ISC', '0BSD', 'BSD', 'BSD-2-Clause', 'BSD-3-Clause',
  'Apache-2.0', 'Unlicense', 'CC0-1.0', 'BlueOak-1.0.0', 'Python-2.0',
])
const ALLOW_EXPRESSIONS = new Set([
  // DOMPurify offers Apache-2.0 as a permissive licensing option.
  '(MPL-2.0 OR Apache-2.0)',
])

// An SPDX expression is allowed only if every component is on the allowlist.
function allowed(expr) {
  if (ALLOW_EXPRESSIONS.has(expr)) return true
  const parts = expr.split(/\s+(?:AND|OR)\s+|[()]/).map(s => s.trim()).filter(Boolean)
  return parts.length > 0 && parts.every(p => ALLOW.has(p))
}

const mode = process.argv[2] || 'check'
const raw = execSync('pnpm licenses list --prod --json', { encoding: 'utf8', stdio: ['ignore', 'pipe', 'inherit'] })
const data = JSON.parse(raw) // { "<spdx>": [ { name, versions[], paths[], license, author, homepage }, ... ] }

const pkgs = []
for (const [license, entries] of Object.entries(data)) {
  for (const e of entries) pkgs.push({ name: e.name, versions: e.versions || [], paths: e.paths || [], license })
}
pkgs.sort((a, b) => a.name.localeCompare(b.name))

if (mode === 'check') {
  const bad = pkgs.filter(p => !allowed(p.license))
  if (bad.length) {
    console.error('ERROR: disallowed/unrecognised frontend dependency licenses:')
    for (const p of bad) console.error(`  ${p.name}@${p.versions.join(',')} — ${p.license}`)
    console.error('\nPermissive only. If genuinely permissive, add the SPDX id to ALLOW in scripts/licenses.mjs.')
    process.exit(1)
  }
  console.log(`frontend licenses: OK (${pkgs.length} production dependencies)`)
  process.exit(0)
}

if (mode === 'gen') {
  const LIC_NAMES = ['LICENSE', 'LICENSE.md', 'LICENSE.txt', 'license', 'LICENCE', 'LICENCE.md', 'LICENSE-MIT', 'COPYING']
  let out = '# Third-Party Notices — airlock frontend\n\n'
  out += 'Generated by scripts/licenses.mjs (pnpm licenses) — do not edit by hand.\n'
  out += 'Re-run via `pnpm run notices`. Lists the open-source bundled into the SPA.\n\n'
  for (const p of pkgs) {
    out += '='.repeat(80) + '\n'
    out += `${p.name} ${p.versions.join(', ')} (${p.license})\n`
    out += '='.repeat(80) + '\n'
    let text = ''
    const dir = p.paths[0]
    if (dir) {
      for (const fn of LIC_NAMES) {
        const f = join(dir, fn)
        if (existsSync(f)) { text = readFileSync(f, 'utf8').trimEnd(); break }
      }
    }
    out += (text || `(no license file in package; SPDX: ${p.license})`) + '\n\n'
  }
  const outURL = new URL('../public/THIRD_PARTY_NOTICES.md', import.meta.url)
  mkdirSync(new URL('../public/', import.meta.url), { recursive: true })
  writeFileSync(outURL, out)
  console.log(`wrote public/THIRD_PARTY_NOTICES.md (${pkgs.length} dependencies)`)
  process.exit(0)
}

console.error(`unknown mode ${mode} (use: check | gen)`)
process.exit(2)
