// Code generated by airlock scaffold. DO NOT EDIT.
//
// This file holds blank imports and other glue that the scaffold needs to
// wire into the agent binary. Future generated initialization can also live
// here. The agent author should not edit it — changes will be overwritten on
// the next scaffold run.
package main

import (
	_ "agent/db/migrations" // auto-register Go migrations
)
