#!/usr/bin/env bash
# gen-notices.sh — regenerate THIRD_PARTY_NOTICES files from the Go module graph.
#
# Produces two files, one per distributed binary:
#   airlock/THIRD_PARTY_NOTICES.md
#       — every module compiled into the airlock server binary.
#   airlock/scaffold/templates/THIRD_PARTY_NOTICES.md
#       — every module compiled into an agent binary (agentsdk + its deps),
#         plus Tailwind CSS + DaisyUI (their compiled CSS ships in the agent).
#       The scaffold materializes this into each generated agent verbatim.
#
# Permissive licenses (MIT/BSD/ISC) require the copyright + permission notice
# to travel with the binary; Apache-2.0 additionally requires reproducing each
# dependency's NOTICE file. This concatenates LICENSE + NOTICE per module so the
# distributed artifact carries them. Re-run after dependency or version bumps.
#
# No external tooling: resolves module dirs from `go list` + the module cache.
set -euo pipefail

AIRLOCK="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
HQ="$(cd "$AIRLOCK/.." && pwd)"

# mit_block NAME VERSION COPYRIGHT — emit a canonical MIT license stanza. Used
# for the build-time CSS tools whose compiled output ships in the agent but
# which aren't Go modules (so they're not in the module graph).
mit_block() {
	cat <<EOF
================================================================================
$1 $2
================================================================================
MIT License

Copyright (c) $3

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.

EOF
}

# gen_go LISTDIR PKGS SKIPMODULE OUT TITLE — write the header + a stanza per Go
# module compiled into PKGS (LICENSE, then any NOTICE). SKIPMODULE drops the
# binary's own first-party module from its own notices file.
gen_go() {
	local listdir="$1" pkgs="$2" skip="$3" out="$4" title="$5"
	{
		echo "# Third-Party Notices — $title"
		echo
		echo "Generated by airlock/scripts/gen-notices.sh — do not edit by hand."
		echo "Re-run after dependency or pinned-version bumps."
		echo
		echo "This lists the open-source software bundled in the distributed binary"
		echo "and reproduces each component's license (and NOTICE, where required)."
		echo
	} >"$out"

	local missing=0
	# Resolve each compiled dependency module to its on-disk source dir.
	(cd "$listdir" && go list -deps -f '{{with .Module}}{{.Path}}|{{.Version}}|{{.Dir}}{{end}}' $pkgs) |
		sort -u | awk -F'|' 'NF==3 && $3!=""' | {
		while IFS='|' read -r path ver dir; do
			[ "$path" = "$skip" ] && continue
			local lic
			lic=$(ls "$dir"/LICENSE* "$dir"/COPYING* "$dir"/LICENCE* 2>/dev/null | head -1 || true)
			{
				echo "================================================================================"
				echo "$path${ver:+ $ver}"
				echo "================================================================================"
				if [ -n "$lic" ]; then
					cat "$lic"
				else
					echo "(no license file found in module source)"
					echo "WARNING: no license file for $path" >&2
					missing=1
				fi
				local n
				for n in "$dir"/NOTICE*; do
					[ -f "$n" ] || continue
					echo
					echo "--- NOTICE ---"
					cat "$n"
				done
				echo
				echo
			} >>"$out"
		done
		[ "$missing" = 0 ] || echo "gen-notices: some modules had no license file (see warnings)" >&2
	}
	echo "wrote $out"
}

# --- airlock server binary ---
gen_go "$AIRLOCK" "./cmd/airlock" "github.com/airlockrun/airlock" \
	"$AIRLOCK/THIRD_PARTY_NOTICES.md" "airlock"

# --- agent binary (baseline: the scaffold's fixed dep set via agentsdk) ---
# Only when the agentsdk source is checked out alongside airlock (local dev /
# the full monorepo). In an airlock-only checkout (CI) it's absent — the
# committed scaffold notices stand, regenerated wherever agentsdk is present.
AGENT_OUT="$AIRLOCK/scaffold/templates/THIRD_PARTY_NOTICES.md"
if [ -d "$HQ/agentsdk" ]; then
	gen_go "$HQ/agentsdk" "./..." "" "$AGENT_OUT" "airlock agent"

	# Append the build-time CSS tooling whose compiled output is embedded +
	# served by the agent (versions pinned in the scaffold Dockerfile).
	TAILWIND_VERSION=$(grep -oE 'ARG TAILWIND_VERSION=\S+' "$AIRLOCK/scaffold/templates/Dockerfile.tmpl" | cut -d= -f2)
	DAISYUI_VERSION=$(grep -oE 'ARG DAISYUI_VERSION=\S+' "$AIRLOCK/scaffold/templates/Dockerfile.tmpl" | cut -d= -f2)
	{
		echo "The agent's stylesheet is compiled with the following tools; their"
		echo "authored CSS is embedded in the compiled output the agent serves."
		echo
		mit_block "Tailwind CSS" "$TAILWIND_VERSION" "Tailwind Labs, Inc."
		mit_block "DaisyUI" "$DAISYUI_VERSION" "Pouya Saadeghi"
	} >>"$AGENT_OUT"
	echo "appended Tailwind $TAILWIND_VERSION + DaisyUI $DAISYUI_VERSION to $AGENT_OUT"
else
	echo "skip: $HQ/agentsdk not present — scaffold notices left as committed" >&2
fi
