// Package builder implements the agent build and upgrade pipeline.
package builder

import (
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"strings"

	"github.com/airlockrun/airlock/scaffold"
)

// InitMonorepo initializes a bare git repo at path if it doesn't exist.
func InitMonorepo(path string) error {
	if _, err := os.Stat(filepath.Join(path, ".git")); err == nil {
		return nil // already initialized
	}

	if err := os.MkdirAll(path, 0o755); err != nil {
		return fmt.Errorf("mkdir %s: %w", path, err)
	}

	if err := git(path, "init"); err != nil {
		return fmt.Errorf("git init: %w", err)
	}

	// Configure git user for commits
	if err := git(path, "config", "user.email", "airlock@localhost"); err != nil {
		return fmt.Errorf("git config email: %w", err)
	}
	if err := git(path, "config", "user.name", "Airlock"); err != nil {
		return fmt.Errorf("git config name: %w", err)
	}

	// Allow pushes into checked-out branch (sparse checkouts push back here)
	if err := git(path, "config", "receive.denyCurrentBranch", "updateInstead"); err != nil {
		return fmt.Errorf("git config receive: %w", err)
	}

	// AGENT_SPEC.md and Dockerfile are generated by Airlock before each
	// build/upgrade and should not be committed to the agent source tree.
	if err := os.WriteFile(filepath.Join(path, ".gitignore"), []byte("AGENT_SPEC.md\nDockerfile\n"), 0o644); err != nil {
		return fmt.Errorf("write .gitignore: %w", err)
	}

	if err := git(path, "add", ".gitignore"); err != nil {
		return fmt.Errorf("git add .gitignore: %w", err)
	}

	if err := git(path, "commit", "-m", "init"); err != nil {
		return fmt.Errorf("git initial commit: %w", err)
	}

	return nil
}

// CommitScaffold creates branch build/{agentID}/init, materializes scaffold, commits.
// Returns the commit hash. Safe to call on retry — deletes a stale branch if it exists.
func CommitScaffold(repoPath, agentID string, data scaffold.ScaffoldData) (string, error) {
	branch := fmt.Sprintf("build/%s/init", agentID)

	// Clean up stale branch from a previous failed build attempt.
	// Must switch away from it first — can't delete the checked-out branch.
	_ = git(repoPath, "checkout", "master")
	_ = git(repoPath, "branch", "-D", branch)

	if err := git(repoPath, "checkout", "-b", branch); err != nil {
		return "", fmt.Errorf("git checkout -b %s: %w", branch, err)
	}

	// Materialize scaffold into the agent directory
	agentDir := filepath.Join(repoPath, "agents", agentID)
	if err := scaffold.Materialize(agentDir, data); err != nil {
		return "", fmt.Errorf("materialize scaffold: %w", err)
	}

	// Stage and commit
	if err := git(repoPath, "add", "agents/"+agentID); err != nil {
		return "", fmt.Errorf("git add: %w", err)
	}

	// Retry safety: a previous build may have already merged the same
	// scaffold to master. Since we just re-created the build branch from
	// master, the materialized files match what's already committed and
	// there's nothing to stage. Treat that as success and return current
	// HEAD — MergeBranch is a no-op when the branch is already merged.
	status, err := gitOutput(repoPath, "status", "--porcelain")
	if err != nil {
		return "", fmt.Errorf("git status: %w", err)
	}
	if status == "" {
		hash, err := gitOutput(repoPath, "rev-parse", "HEAD")
		if err != nil {
			return "", fmt.Errorf("git rev-parse: %w", err)
		}
		return hash, nil
	}

	if err := git(repoPath, "commit", "-m", fmt.Sprintf("scaffold agent %s", agentID)); err != nil {
		return "", fmt.Errorf("git commit: %w", err)
	}

	hash, err := gitOutput(repoPath, "rev-parse", "HEAD")
	if err != nil {
		return "", fmt.Errorf("git rev-parse: %w", err)
	}

	return hash, nil
}

// CreateBranch creates a new branch from main/master.
func CreateBranch(repoPath, branch string) error {
	if err := git(repoPath, "checkout", "main"); err != nil {
		if err2 := git(repoPath, "checkout", "master"); err2 != nil {
			return fmt.Errorf("git checkout main: %w", err)
		}
	}

	// Clean up stale branch from a previous failed attempt.
	_ = git(repoPath, "branch", "-D", branch)

	if err := git(repoPath, "checkout", "-b", branch); err != nil {
		return fmt.Errorf("git checkout -b %s: %w", branch, err)
	}

	return nil
}

// CreateUpgradeBranch creates branch upgrade/{agentID}/{runID} from main.
func CreateUpgradeBranch(repoPath, agentID, runID string) error {
	branch := fmt.Sprintf("upgrade/%s/%s", agentID, runID)

	if err := git(repoPath, "checkout", "main"); err != nil {
		// Try master if main doesn't exist
		if err2 := git(repoPath, "checkout", "master"); err2 != nil {
			return fmt.Errorf("git checkout main: %w", err)
		}
	}

	if err := git(repoPath, "checkout", "-b", branch); err != nil {
		return fmt.Errorf("git checkout -b %s: %w", branch, err)
	}

	return nil
}

// SparseCheckout clones the repo into targetDir with only agents/{agentID}/ checked out.
func SparseCheckout(repoPath, branch, agentID, targetDir string) error {
	if err := os.MkdirAll(targetDir, 0o755); err != nil {
		return fmt.Errorf("mkdir %s: %w", targetDir, err)
	}

	if err := runGit(targetDir, "clone", "--filter=blob:none", "--sparse", "--branch", branch, repoPath, "."); err != nil {
		return fmt.Errorf("git clone --sparse: %w", err)
	}

	agentPath := fmt.Sprintf("agents/%s", agentID)
	if err := git(targetDir, "sparse-checkout", "set", agentPath); err != nil {
		return fmt.Errorf("git sparse-checkout set: %w", err)
	}

	// Mark the workspace as safe for both host path and container mount path.
	if err := git(targetDir, "config", "safe.directory", targetDir); err != nil {
		return fmt.Errorf("git config safe.directory: %w", err)
	}
	// The toolserver container mounts this dir at /workspace.
	_ = git(targetDir, "config", "--add", "safe.directory", "/workspace")

	// Configure git user for commits in the clone
	if err := git(targetDir, "config", "user.email", "airlock@localhost"); err != nil {
		return fmt.Errorf("git config email: %w", err)
	}
	if err := git(targetDir, "config", "user.name", "Airlock"); err != nil {
		return fmt.Errorf("git config name: %w", err)
	}

	return nil
}

// CommitAndPush commits all changes on the current branch in workDir,
// pushes to origin. Returns commit hash.
func CommitAndPush(workDir, message string) (string, error) {
	if err := git(workDir, "add", "-A"); err != nil {
		return "", fmt.Errorf("git add: %w", err)
	}

	// If there are no changes, skip commit + push and return current HEAD.
	status, err := gitOutput(workDir, "status", "--porcelain")
	if err != nil {
		return "", fmt.Errorf("git status: %w", err)
	}
	if status == "" {
		hash, err := gitOutput(workDir, "rev-parse", "HEAD")
		if err != nil {
			return "", fmt.Errorf("git rev-parse: %w", err)
		}
		return hash, nil
	}

	if err := git(workDir, "commit", "-m", message); err != nil {
		return "", fmt.Errorf("git commit: %w", err)
	}

	hash, err := gitOutput(workDir, "rev-parse", "HEAD")
	if err != nil {
		return "", fmt.Errorf("git rev-parse: %w", err)
	}

	if err := git(workDir, "push", "origin", "HEAD"); err != nil {
		return "", fmt.Errorf("git push: %w", err)
	}

	return hash, nil
}

// MergeBranch fast-forward merges branch into main, rebasing the branch
// onto current main first if a parallel build advanced main while this
// branch's work was running. Cross-agent rebases never conflict (each
// agent lives under its own agents/<id>/), and the per-agent build lock
// prevents same-agent races, so the rebase is safe in practice.
func MergeBranch(repoPath, branch string) error {
	mainBranch := "main"
	if err := git(repoPath, "checkout", "main"); err != nil {
		if err2 := git(repoPath, "checkout", "master"); err2 != nil {
			return fmt.Errorf("git checkout main: %w", err)
		}
		mainBranch = "master"
	}

	if err := git(repoPath, "merge", "--ff-only", branch); err == nil {
		return nil
	}

	// Diverged from main — replay the branch's commits on top of current
	// main, then ff-merge. Abort the rebase on conflict so we don't leave
	// the repo in a half-rebased state.
	if err := git(repoPath, "rebase", mainBranch, branch); err != nil {
		_ = git(repoPath, "rebase", "--abort")
		_ = git(repoPath, "checkout", mainBranch)
		return fmt.Errorf("git rebase %s onto %s: %w", branch, mainBranch, err)
	}
	if err := git(repoPath, "checkout", mainBranch); err != nil {
		return fmt.Errorf("git checkout %s after rebase: %w", mainBranch, err)
	}
	if err := git(repoPath, "merge", "--ff-only", branch); err != nil {
		return fmt.Errorf("git merge --ff-only %s after rebase: %w", branch, err)
	}
	return nil
}

// RemoveAgentCode deletes the agent directory from the monorepo and commits.
func RemoveAgentCode(repoPath, agentID string) error {
	agentDir := filepath.Join(repoPath, "agents", agentID)
	if _, err := os.Stat(agentDir); os.IsNotExist(err) {
		return nil // nothing to remove
	}

	if err := os.RemoveAll(agentDir); err != nil {
		return fmt.Errorf("remove agent dir: %w", err)
	}

	// Checkout main before committing.
	if err := git(repoPath, "checkout", "main"); err != nil {
		_ = git(repoPath, "checkout", "master")
	}

	if err := git(repoPath, "add", "-A"); err != nil {
		return fmt.Errorf("git add: %w", err)
	}

	if err := git(repoPath, "commit", "-m", fmt.Sprintf("remove agent %s", agentID)); err != nil {
		// Nothing to commit (already removed) is fine.
		return nil
	}

	return nil
}

// git runs a git command in the given directory.
func git(dir string, args ...string) error {
	return runGit(dir, args...)
}

// runGit runs a git command in the given directory.
func runGit(dir string, args ...string) error {
	cmd := exec.Command("git", args...)
	cmd.Dir = dir
	cmd.Env = append(gitCleanEnv(), "GIT_TERMINAL_PROMPT=0")
	out, err := cmd.CombinedOutput()
	if err != nil {
		return fmt.Errorf("%s: %s", err, strings.TrimSpace(string(out)))
	}
	return nil
}

// gitOutput runs a git command and returns its stdout.
func gitOutput(dir string, args ...string) (string, error) {
	cmd := exec.Command("git", args...)
	cmd.Dir = dir
	cmd.Env = append(gitCleanEnv(), "GIT_TERMINAL_PROMPT=0")
	out, err := cmd.Output()
	if err != nil {
		if ee, ok := err.(*exec.ExitError); ok {
			return "", fmt.Errorf("%s: %s", err, strings.TrimSpace(string(ee.Stderr)))
		}
		return "", err
	}
	return strings.TrimSpace(string(out)), nil
}

// gitCleanEnv returns os.Environ() with git-context vars stripped. These
// leak in when builder tests run inside a pre-commit hook (git sets
// GIT_INDEX_FILE and friends pointing at the parent repo's in-flight
// index, which breaks any git subprocess that tries to use its own repo).
func gitCleanEnv() []string {
	env := os.Environ()
	out := env[:0]
	for _, kv := range env {
		eq := strings.IndexByte(kv, '=')
		if eq < 0 {
			out = append(out, kv)
			continue
		}
		k := kv[:eq]
		if strings.HasPrefix(k, "GIT_") {
			continue
		}
		out = append(out, kv)
	}
	return out
}
