'use client';
import { FormEvent, useEffect, useState } from 'react';
import { listComputers } from '@/lib/computer-api';
import { useComputerSelection } from '@/lib/computer-selection';
import type { Computer } from '@/lib/types';
export function TerminalApp() {
  const [computers, setComputers] = useState<Computer[]>([]), [command, setCommand] = useState('hostname'), [lines, setLines] = useState<string[]>([]);
  const computerId = useComputerSelection(s => s.computerId), selectComputer = useComputerSelection(s => s.selectComputer), computer = computers.find(item => item.id === computerId);
  useEffect(() => { void listComputers().then(result => setComputers((result.data ?? []).filter(item => item.capabilities.includes('files') && item.capabilities.includes('terminal')))); }, []);
  async function run(event: FormEvent) { event.preventDefault(); if (!computerId || !command) return; setLines(old => [...old, `${computer?.name ?? 'cloudos'} $ ${command}`]); const response = await fetch('/api/computer/processes', { method: 'POST', headers: {'Content-Type':'application/json'}, body: JSON.stringify({operation:'processes.exec', computer: computerId, session:'cloudos-ui', command}) }); const payload = await response.json(), result = payload.data; setLines(old => [...old, result?.stdout || result?.stderr || result?.detail || payload.error || 'Command failed.']); }
  return <section className="h-full overflow-auto bg-[#101215] p-5 font-mono text-sm text-emerald-300"><div className="flex items-center justify-between border-b border-white/10 pb-3"><div><p className="font-semibold">{computer ? `user@${computer.name}:~` : 'CloudOS terminal'}</p><p className="mt-1 text-xs text-slate-400">Enabled: hostname, whoami, pwd, ls, dir.</p></div><select aria-label="Connected computer" value={computerId} onChange={event => selectComputer(event.target.value)} className="rounded bg-slate-800 px-2 py-1 text-sm text-white"><option value="">Choose computer…</option>{computers.map(item => <option key={item.id} value={item.id}>{item.name}</option>)}</select></div><pre className="mt-4 min-h-24 whitespace-pre-wrap text-slate-200">{lines.join('\n')}</pre><form onSubmit={run} className="mt-4 flex gap-2"><span className="py-2 text-violet-300">{computer ? '$' : '·'}</span><input aria-label="Command" value={command} onChange={event => setCommand(event.target.value)} className="min-w-0 flex-1 rounded bg-slate-900 px-3 py-2 text-white"/><button disabled={!computerId} className="rounded bg-violet-500 px-3 py-2 font-sans text-white disabled:opacity-40">Run</button></form></section>;
}
