// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: agent_schedule_handlers.sql

package dbq

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteScheduleHandlersByAgentExcept = `-- name: DeleteScheduleHandlersByAgentExcept :exec
DELETE FROM agent_schedule_handlers
WHERE agent_id = $1 AND slug != ALL($2::text[])
`

type DeleteScheduleHandlersByAgentExceptParams struct {
	AgentID pgtype.UUID `json:"agent_id"`
	Slugs   []string    `json:"slugs"`
}

func (q *Queries) DeleteScheduleHandlersByAgentExcept(ctx context.Context, arg DeleteScheduleHandlersByAgentExceptParams) error {
	_, err := q.db.Exec(ctx, deleteScheduleHandlersByAgentExcept, arg.AgentID, arg.Slugs)
	return err
}

const getScheduleHandler = `-- name: GetScheduleHandler :one
SELECT id, agent_id, slug, kind, recurrence, enabled, timeout_ms, description, last_fired_at, created_at, updated_at FROM agent_schedule_handlers WHERE agent_id = $1 AND slug = $2
`

type GetScheduleHandlerParams struct {
	AgentID pgtype.UUID `json:"agent_id"`
	Slug    string      `json:"slug"`
}

func (q *Queries) GetScheduleHandler(ctx context.Context, arg GetScheduleHandlerParams) (AgentScheduleHandler, error) {
	row := q.db.QueryRow(ctx, getScheduleHandler, arg.AgentID, arg.Slug)
	var i AgentScheduleHandler
	err := row.Scan(
		&i.ID,
		&i.AgentID,
		&i.Slug,
		&i.Kind,
		&i.Recurrence,
		&i.Enabled,
		&i.TimeoutMs,
		&i.Description,
		&i.LastFiredAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listEnabledCronHandlers = `-- name: ListEnabledCronHandlers :many
SELECT h.id, h.agent_id, h.slug, h.kind, h.recurrence, h.enabled, h.timeout_ms, h.description, h.last_fired_at, h.created_at, h.updated_at FROM agent_schedule_handlers h
JOIN agents a ON a.id = h.agent_id
WHERE h.kind = 'cron' AND h.enabled = true AND a.status = 'active'
`

func (q *Queries) ListEnabledCronHandlers(ctx context.Context) ([]AgentScheduleHandler, error) {
	rows, err := q.db.Query(ctx, listEnabledCronHandlers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AgentScheduleHandler{}
	for rows.Next() {
		var i AgentScheduleHandler
		if err := rows.Scan(
			&i.ID,
			&i.AgentID,
			&i.Slug,
			&i.Kind,
			&i.Recurrence,
			&i.Enabled,
			&i.TimeoutMs,
			&i.Description,
			&i.LastFiredAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listScheduleHandlersByAgent = `-- name: ListScheduleHandlersByAgent :many
SELECT id, agent_id, slug, kind, recurrence, enabled, timeout_ms, description, last_fired_at, created_at, updated_at FROM agent_schedule_handlers WHERE agent_id = $1 ORDER BY slug
`

func (q *Queries) ListScheduleHandlersByAgent(ctx context.Context, agentID pgtype.UUID) ([]AgentScheduleHandler, error) {
	rows, err := q.db.Query(ctx, listScheduleHandlersByAgent, agentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AgentScheduleHandler{}
	for rows.Next() {
		var i AgentScheduleHandler
		if err := rows.Scan(
			&i.ID,
			&i.AgentID,
			&i.Slug,
			&i.Kind,
			&i.Recurrence,
			&i.Enabled,
			&i.TimeoutMs,
			&i.Description,
			&i.LastFiredAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listScheduleHandlersByAgentKind = `-- name: ListScheduleHandlersByAgentKind :many
SELECT id, agent_id, slug, kind, recurrence, enabled, timeout_ms, description, last_fired_at, created_at, updated_at FROM agent_schedule_handlers WHERE agent_id = $1 AND kind = $2 ORDER BY slug
`

type ListScheduleHandlersByAgentKindParams struct {
	AgentID pgtype.UUID `json:"agent_id"`
	Kind    string      `json:"kind"`
}

func (q *Queries) ListScheduleHandlersByAgentKind(ctx context.Context, arg ListScheduleHandlersByAgentKindParams) ([]AgentScheduleHandler, error) {
	rows, err := q.db.Query(ctx, listScheduleHandlersByAgentKind, arg.AgentID, arg.Kind)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AgentScheduleHandler{}
	for rows.Next() {
		var i AgentScheduleHandler
		if err := rows.Scan(
			&i.ID,
			&i.AgentID,
			&i.Slug,
			&i.Kind,
			&i.Recurrence,
			&i.Enabled,
			&i.TimeoutMs,
			&i.Description,
			&i.LastFiredAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSchedulesWithNextFire = `-- name: ListSchedulesWithNextFire :many
SELECT h.id, h.agent_id, h.slug, h.kind, h.recurrence, h.enabled, h.timeout_ms, h.description, h.last_fired_at, h.created_at, h.updated_at, f.next_fire_at::timestamptz AS next_fire_at
FROM agent_schedule_handlers h
LEFT JOIN (
    SELECT agent_id, slug, MIN(fire_at) AS next_fire_at
    FROM agent_scheduled_fires
    WHERE status = 'pending'
    GROUP BY agent_id, slug
) f ON f.agent_id = h.agent_id AND f.slug = h.slug
WHERE h.agent_id = $1
ORDER BY h.slug
`

type ListSchedulesWithNextFireRow struct {
	ID          pgtype.UUID        `json:"id"`
	AgentID     pgtype.UUID        `json:"agent_id"`
	Slug        string             `json:"slug"`
	Kind        string             `json:"kind"`
	Recurrence  string             `json:"recurrence"`
	Enabled     bool               `json:"enabled"`
	TimeoutMs   int64              `json:"timeout_ms"`
	Description string             `json:"description"`
	LastFiredAt pgtype.Timestamptz `json:"last_fired_at"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	NextFireAt  pgtype.Timestamptz `json:"next_fire_at"`
}

// One row per handler (cron + schedule) with the earliest pending fire time.
func (q *Queries) ListSchedulesWithNextFire(ctx context.Context, agentID pgtype.UUID) ([]ListSchedulesWithNextFireRow, error) {
	rows, err := q.db.Query(ctx, listSchedulesWithNextFire, agentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSchedulesWithNextFireRow{}
	for rows.Next() {
		var i ListSchedulesWithNextFireRow
		if err := rows.Scan(
			&i.ID,
			&i.AgentID,
			&i.Slug,
			&i.Kind,
			&i.Recurrence,
			&i.Enabled,
			&i.TimeoutMs,
			&i.Description,
			&i.LastFiredAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.NextFireAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateScheduleHandlerLastFired = `-- name: UpdateScheduleHandlerLastFired :exec
UPDATE agent_schedule_handlers SET last_fired_at = now()
WHERE agent_id = $1 AND slug = $2
`

type UpdateScheduleHandlerLastFiredParams struct {
	AgentID pgtype.UUID `json:"agent_id"`
	Slug    string      `json:"slug"`
}

func (q *Queries) UpdateScheduleHandlerLastFired(ctx context.Context, arg UpdateScheduleHandlerLastFiredParams) error {
	_, err := q.db.Exec(ctx, updateScheduleHandlerLastFired, arg.AgentID, arg.Slug)
	return err
}

const upsertScheduleHandler = `-- name: UpsertScheduleHandler :exec
INSERT INTO agent_schedule_handlers (agent_id, slug, kind, recurrence, timeout_ms, description)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (agent_id, slug) DO UPDATE SET
    kind = EXCLUDED.kind,
    recurrence = EXCLUDED.recurrence,
    timeout_ms = EXCLUDED.timeout_ms,
    description = EXCLUDED.description,
    updated_at = now()
`

type UpsertScheduleHandlerParams struct {
	AgentID     pgtype.UUID `json:"agent_id"`
	Slug        string      `json:"slug"`
	Kind        string      `json:"kind"`
	Recurrence  string      `json:"recurrence"`
	TimeoutMs   int64       `json:"timeout_ms"`
	Description string      `json:"description"`
}

// enabled defaults true on insert, preserved on conflict (operator toggle).
// last_fired_at is preserved on conflict.
func (q *Queries) UpsertScheduleHandler(ctx context.Context, arg UpsertScheduleHandlerParams) error {
	_, err := q.db.Exec(ctx, upsertScheduleHandler,
		arg.AgentID,
		arg.Slug,
		arg.Kind,
		arg.Recurrence,
		arg.TimeoutMs,
		arg.Description,
	)
	return err
}
