// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: agents.sql

package dbq

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAgent = `-- name: CreateAgent :one
INSERT INTO agents (
    name, slug, user_id, description, config, status,
    upgrade_status, auto_fix,
    build_model, exec_model, stt_model, vision_model,
    tts_model, image_gen_model, embedding_model, search_model,
    source_ref, image_ref, db_schema, db_password, sdk_version,
    extra_prompts, error_message
)
VALUES (
    $1, $2, $3, $4, $5, 'draft',
    'idle', true,
    '', '', '', '',
    '', '', '', '',
    '', '', '', '', '',
    '[]'::jsonb, ''
)
RETURNING id, user_id, slug, name, description, status, upgrade_status, auto_fix, build_model, exec_model, stt_model, vision_model, tts_model, image_gen_model, embedding_model, search_model, source_ref, image_ref, db_schema, db_password, sdk_version, config, extra_prompts, error_message, created_at, updated_at
`

type CreateAgentParams struct {
	Name        string      `json:"name"`
	Slug        string      `json:"slug"`
	UserID      pgtype.UUID `json:"user_id"`
	Description string      `json:"description"`
	Config      []byte      `json:"config"`
}

// Initial-row INSERT. All "starts empty" string fields are passed
// explicitly as ” rather than relying on column defaults (per AGENTS.md
// "no fake defaults" rule). Status starts 'draft', upgrade_status 'idle',
// auto_fix true, extra_prompts empty array.
func (q *Queries) CreateAgent(ctx context.Context, arg CreateAgentParams) (Agent, error) {
	row := q.db.QueryRow(ctx, createAgent,
		arg.Name,
		arg.Slug,
		arg.UserID,
		arg.Description,
		arg.Config,
	)
	var i Agent
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Slug,
		&i.Name,
		&i.Description,
		&i.Status,
		&i.UpgradeStatus,
		&i.AutoFix,
		&i.BuildModel,
		&i.ExecModel,
		&i.SttModel,
		&i.VisionModel,
		&i.TtsModel,
		&i.ImageGenModel,
		&i.EmbeddingModel,
		&i.SearchModel,
		&i.SourceRef,
		&i.ImageRef,
		&i.DbSchema,
		&i.DbPassword,
		&i.SdkVersion,
		&i.Config,
		&i.ExtraPrompts,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteAgent = `-- name: DeleteAgent :exec
DELETE FROM agents WHERE id = $1
`

func (q *Queries) DeleteAgent(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteAgent, id)
	return err
}

const getAgentByID = `-- name: GetAgentByID :one
SELECT id, user_id, slug, name, description, status, upgrade_status, auto_fix, build_model, exec_model, stt_model, vision_model, tts_model, image_gen_model, embedding_model, search_model, source_ref, image_ref, db_schema, db_password, sdk_version, config, extra_prompts, error_message, created_at, updated_at FROM agents WHERE id = $1
`

func (q *Queries) GetAgentByID(ctx context.Context, id pgtype.UUID) (Agent, error) {
	row := q.db.QueryRow(ctx, getAgentByID, id)
	var i Agent
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Slug,
		&i.Name,
		&i.Description,
		&i.Status,
		&i.UpgradeStatus,
		&i.AutoFix,
		&i.BuildModel,
		&i.ExecModel,
		&i.SttModel,
		&i.VisionModel,
		&i.TtsModel,
		&i.ImageGenModel,
		&i.EmbeddingModel,
		&i.SearchModel,
		&i.SourceRef,
		&i.ImageRef,
		&i.DbSchema,
		&i.DbPassword,
		&i.SdkVersion,
		&i.Config,
		&i.ExtraPrompts,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAgentBySlug = `-- name: GetAgentBySlug :one
SELECT id, user_id, slug, name, description, status, upgrade_status, auto_fix, build_model, exec_model, stt_model, vision_model, tts_model, image_gen_model, embedding_model, search_model, source_ref, image_ref, db_schema, db_password, sdk_version, config, extra_prompts, error_message, created_at, updated_at FROM agents WHERE slug = $1
`

func (q *Queries) GetAgentBySlug(ctx context.Context, slug string) (Agent, error) {
	row := q.db.QueryRow(ctx, getAgentBySlug, slug)
	var i Agent
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Slug,
		&i.Name,
		&i.Description,
		&i.Status,
		&i.UpgradeStatus,
		&i.AutoFix,
		&i.BuildModel,
		&i.ExecModel,
		&i.SttModel,
		&i.VisionModel,
		&i.TtsModel,
		&i.ImageGenModel,
		&i.EmbeddingModel,
		&i.SearchModel,
		&i.SourceRef,
		&i.ImageRef,
		&i.DbSchema,
		&i.DbPassword,
		&i.SdkVersion,
		&i.Config,
		&i.ExtraPrompts,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAgentForUpgrade = `-- name: GetAgentForUpgrade :one
SELECT id, upgrade_status FROM agents WHERE id = $1 FOR UPDATE
`

type GetAgentForUpgradeRow struct {
	ID            pgtype.UUID `json:"id"`
	UpgradeStatus string      `json:"upgrade_status"`
}

func (q *Queries) GetAgentForUpgrade(ctx context.Context, id pgtype.UUID) (GetAgentForUpgradeRow, error) {
	row := q.db.QueryRow(ctx, getAgentForUpgrade, id)
	var i GetAgentForUpgradeRow
	err := row.Scan(&i.ID, &i.UpgradeStatus)
	return i, err
}

const listAgents = `-- name: ListAgents :many
SELECT id, user_id, slug, name, description, status, upgrade_status, auto_fix, build_model, exec_model, stt_model, vision_model, tts_model, image_gen_model, embedding_model, search_model, source_ref, image_ref, db_schema, db_password, sdk_version, config, extra_prompts, error_message, created_at, updated_at FROM agents ORDER BY created_at DESC
`

func (q *Queries) ListAgents(ctx context.Context) ([]Agent, error) {
	rows, err := q.db.Query(ctx, listAgents)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Agent{}
	for rows.Next() {
		var i Agent
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Slug,
			&i.Name,
			&i.Description,
			&i.Status,
			&i.UpgradeStatus,
			&i.AutoFix,
			&i.BuildModel,
			&i.ExecModel,
			&i.SttModel,
			&i.VisionModel,
			&i.TtsModel,
			&i.ImageGenModel,
			&i.EmbeddingModel,
			&i.SearchModel,
			&i.SourceRef,
			&i.ImageRef,
			&i.DbSchema,
			&i.DbPassword,
			&i.SdkVersion,
			&i.Config,
			&i.ExtraPrompts,
			&i.ErrorMessage,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAgentsByUser = `-- name: ListAgentsByUser :many
SELECT id, user_id, slug, name, description, status, upgrade_status, auto_fix, build_model, exec_model, stt_model, vision_model, tts_model, image_gen_model, embedding_model, search_model, source_ref, image_ref, db_schema, db_password, sdk_version, config, extra_prompts, error_message, created_at, updated_at FROM agents WHERE user_id = $1 ORDER BY created_at DESC
`

func (q *Queries) ListAgentsByUser(ctx context.Context, userID pgtype.UUID) ([]Agent, error) {
	rows, err := q.db.Query(ctx, listAgentsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Agent{}
	for rows.Next() {
		var i Agent
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Slug,
			&i.Name,
			&i.Description,
			&i.Status,
			&i.UpgradeStatus,
			&i.AutoFix,
			&i.BuildModel,
			&i.ExecModel,
			&i.SttModel,
			&i.VisionModel,
			&i.TtsModel,
			&i.ImageGenModel,
			&i.EmbeddingModel,
			&i.SearchModel,
			&i.SourceRef,
			&i.ImageRef,
			&i.DbSchema,
			&i.DbPassword,
			&i.SdkVersion,
			&i.Config,
			&i.ExtraPrompts,
			&i.ErrorMessage,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAgentsByUserID = `-- name: ListAgentsByUserID :many
SELECT id, user_id, slug, name, description, status, upgrade_status, auto_fix, build_model, exec_model, stt_model, vision_model, tts_model, image_gen_model, embedding_model, search_model, source_ref, image_ref, db_schema, db_password, sdk_version, config, extra_prompts, error_message, created_at, updated_at FROM agents WHERE user_id = $1 ORDER BY created_at DESC
`

func (q *Queries) ListAgentsByUserID(ctx context.Context, userID pgtype.UUID) ([]Agent, error) {
	rows, err := q.db.Query(ctx, listAgentsByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Agent{}
	for rows.Next() {
		var i Agent
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Slug,
			&i.Name,
			&i.Description,
			&i.Status,
			&i.UpgradeStatus,
			&i.AutoFix,
			&i.BuildModel,
			&i.ExecModel,
			&i.SttModel,
			&i.VisionModel,
			&i.TtsModel,
			&i.ImageGenModel,
			&i.EmbeddingModel,
			&i.SearchModel,
			&i.SourceRef,
			&i.ImageRef,
			&i.DbSchema,
			&i.DbPassword,
			&i.SdkVersion,
			&i.Config,
			&i.ExtraPrompts,
			&i.ErrorMessage,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const resetStuckBuilds = `-- name: ResetStuckBuilds :exec
UPDATE agents SET status = 'failed', error_message = $1, updated_at = now()
WHERE status = 'building'
`

func (q *Queries) ResetStuckBuilds(ctx context.Context, errorMessage string) error {
	_, err := q.db.Exec(ctx, resetStuckBuilds, errorMessage)
	return err
}

const resetStuckUpgrades = `-- name: ResetStuckUpgrades :exec
UPDATE agents SET upgrade_status = 'failed', updated_at = now()
WHERE upgrade_status IN ('queued', 'building')
`

func (q *Queries) ResetStuckUpgrades(ctx context.Context) error {
	_, err := q.db.Exec(ctx, resetStuckUpgrades)
	return err
}

const updateAgentConfig = `-- name: UpdateAgentConfig :exec
UPDATE agents SET config = $1, updated_at = now() WHERE id = $2
`

type UpdateAgentConfigParams struct {
	Config []byte      `json:"config"`
	ID     pgtype.UUID `json:"id"`
}

func (q *Queries) UpdateAgentConfig(ctx context.Context, arg UpdateAgentConfigParams) error {
	_, err := q.db.Exec(ctx, updateAgentConfig, arg.Config, arg.ID)
	return err
}

const updateAgentDBPassword = `-- name: UpdateAgentDBPassword :exec
UPDATE agents SET db_password = $1, updated_at = now() WHERE id = $2
`

type UpdateAgentDBPasswordParams struct {
	DbPassword string      `json:"db_password"`
	ID         pgtype.UUID `json:"id"`
}

// Set the encrypted DB password for the agent's per-schema role. Called by
// the builder once createAgentSchema has provisioned the role.
func (q *Queries) UpdateAgentDBPassword(ctx context.Context, arg UpdateAgentDBPasswordParams) error {
	_, err := q.db.Exec(ctx, updateAgentDBPassword, arg.DbPassword, arg.ID)
	return err
}

const updateAgentDescription = `-- name: UpdateAgentDescription :exec
UPDATE agents SET description = $1, updated_at = now() WHERE id = $2
`

type UpdateAgentDescriptionParams struct {
	Description string      `json:"description"`
	ID          pgtype.UUID `json:"id"`
}

func (q *Queries) UpdateAgentDescription(ctx context.Context, arg UpdateAgentDescriptionParams) error {
	_, err := q.db.Exec(ctx, updateAgentDescription, arg.Description, arg.ID)
	return err
}

const updateAgentErrorMessage = `-- name: UpdateAgentErrorMessage :exec
UPDATE agents SET error_message = $1, updated_at = now() WHERE id = $2
`

type UpdateAgentErrorMessageParams struct {
	ErrorMessage string      `json:"error_message"`
	ID           pgtype.UUID `json:"id"`
}

func (q *Queries) UpdateAgentErrorMessage(ctx context.Context, arg UpdateAgentErrorMessageParams) error {
	_, err := q.db.Exec(ctx, updateAgentErrorMessage, arg.ErrorMessage, arg.ID)
	return err
}

const updateAgentExtraPrompts = `-- name: UpdateAgentExtraPrompts :exec
UPDATE agents SET extra_prompts = $1, updated_at = now() WHERE id = $2
`

type UpdateAgentExtraPromptsParams struct {
	ExtraPrompts []byte      `json:"extra_prompts"`
	ID           pgtype.UUID `json:"id"`
}

func (q *Queries) UpdateAgentExtraPrompts(ctx context.Context, arg UpdateAgentExtraPromptsParams) error {
	_, err := q.db.Exec(ctx, updateAgentExtraPrompts, arg.ExtraPrompts, arg.ID)
	return err
}

const updateAgentFields = `-- name: UpdateAgentFields :one
UPDATE agents SET
    auto_fix = $1,
    updated_at = now()
WHERE id = $2
RETURNING id, user_id, slug, name, description, status, upgrade_status, auto_fix, build_model, exec_model, stt_model, vision_model, tts_model, image_gen_model, embedding_model, search_model, source_ref, image_ref, db_schema, db_password, sdk_version, config, extra_prompts, error_message, created_at, updated_at
`

type UpdateAgentFieldsParams struct {
	AutoFix bool        `json:"auto_fix"`
	ID      pgtype.UUID `json:"id"`
}

func (q *Queries) UpdateAgentFields(ctx context.Context, arg UpdateAgentFieldsParams) (Agent, error) {
	row := q.db.QueryRow(ctx, updateAgentFields, arg.AutoFix, arg.ID)
	var i Agent
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Slug,
		&i.Name,
		&i.Description,
		&i.Status,
		&i.UpgradeStatus,
		&i.AutoFix,
		&i.BuildModel,
		&i.ExecModel,
		&i.SttModel,
		&i.VisionModel,
		&i.TtsModel,
		&i.ImageGenModel,
		&i.EmbeddingModel,
		&i.SearchModel,
		&i.SourceRef,
		&i.ImageRef,
		&i.DbSchema,
		&i.DbPassword,
		&i.SdkVersion,
		&i.Config,
		&i.ExtraPrompts,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateAgentModels = `-- name: UpdateAgentModels :exec
UPDATE agents SET
    build_model     = $1,
    exec_model      = $2,
    stt_model       = $3,
    vision_model    = $4,
    tts_model       = $5,
    image_gen_model = $6,
    embedding_model = $7,
    search_model    = $8,
    updated_at = now()
WHERE id = $9
`

type UpdateAgentModelsParams struct {
	BuildModel     string      `json:"build_model"`
	ExecModel      string      `json:"exec_model"`
	SttModel       string      `json:"stt_model"`
	VisionModel    string      `json:"vision_model"`
	TtsModel       string      `json:"tts_model"`
	ImageGenModel  string      `json:"image_gen_model"`
	EmbeddingModel string      `json:"embedding_model"`
	SearchModel    string      `json:"search_model"`
	ID             pgtype.UUID `json:"id"`
}

// Atomic replace of all eight per-agent model override columns.
// Empty strings mean "inherit the corresponding system default".
func (q *Queries) UpdateAgentModels(ctx context.Context, arg UpdateAgentModelsParams) error {
	_, err := q.db.Exec(ctx, updateAgentModels,
		arg.BuildModel,
		arg.ExecModel,
		arg.SttModel,
		arg.VisionModel,
		arg.TtsModel,
		arg.ImageGenModel,
		arg.EmbeddingModel,
		arg.SearchModel,
		arg.ID,
	)
	return err
}

const updateAgentRefs = `-- name: UpdateAgentRefs :exec
UPDATE agents SET source_ref = $1, image_ref = $2, updated_at = now() WHERE id = $3
`

type UpdateAgentRefsParams struct {
	SourceRef string      `json:"source_ref"`
	ImageRef  string      `json:"image_ref"`
	ID        pgtype.UUID `json:"id"`
}

func (q *Queries) UpdateAgentRefs(ctx context.Context, arg UpdateAgentRefsParams) error {
	_, err := q.db.Exec(ctx, updateAgentRefs, arg.SourceRef, arg.ImageRef, arg.ID)
	return err
}

const updateAgentSDKVersion = `-- name: UpdateAgentSDKVersion :exec
UPDATE agents SET sdk_version = $1, updated_at = now() WHERE id = $2
`

type UpdateAgentSDKVersionParams struct {
	SdkVersion string      `json:"sdk_version"`
	ID         pgtype.UUID `json:"id"`
}

func (q *Queries) UpdateAgentSDKVersion(ctx context.Context, arg UpdateAgentSDKVersionParams) error {
	_, err := q.db.Exec(ctx, updateAgentSDKVersion, arg.SdkVersion, arg.ID)
	return err
}

const updateAgentStatus = `-- name: UpdateAgentStatus :exec
UPDATE agents SET status = $1, error_message = $2, updated_at = now() WHERE id = $3
`

type UpdateAgentStatusParams struct {
	Status       string      `json:"status"`
	ErrorMessage string      `json:"error_message"`
	ID           pgtype.UUID `json:"id"`
}

func (q *Queries) UpdateAgentStatus(ctx context.Context, arg UpdateAgentStatusParams) error {
	_, err := q.db.Exec(ctx, updateAgentStatus, arg.Status, arg.ErrorMessage, arg.ID)
	return err
}

const updateAgentUpgradeStatus = `-- name: UpdateAgentUpgradeStatus :exec
UPDATE agents SET upgrade_status = $1, error_message = $2, updated_at = now() WHERE id = $3
`

type UpdateAgentUpgradeStatusParams struct {
	UpgradeStatus string      `json:"upgrade_status"`
	ErrorMessage  string      `json:"error_message"`
	ID            pgtype.UUID `json:"id"`
}

func (q *Queries) UpdateAgentUpgradeStatus(ctx context.Context, arg UpdateAgentUpgradeStatusParams) error {
	_, err := q.db.Exec(ctx, updateAgentUpgradeStatus, arg.UpgradeStatus, arg.ErrorMessage, arg.ID)
	return err
}
