// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: agent_job_crons.sql

package dbq

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const advanceAgentJobCron = `-- name: AdvanceAgentJobCron :execrows
UPDATE agent_job_crons
SET next_fire_at = $1,
    last_fired_at = $2,
    updated_at = now()
WHERE id = $3
  AND next_fire_at = $4
`

type AdvanceAgentJobCronParams struct {
	NextFireAt      pgtype.Timestamptz `json:"next_fire_at"`
	OccurrenceAt    pgtype.Timestamptz `json:"occurrence_at"`
	CronID          pgtype.UUID        `json:"cron_id"`
	PriorNextFireAt pgtype.Timestamptz `json:"prior_next_fire_at"`
}

func (q *Queries) AdvanceAgentJobCron(ctx context.Context, arg AdvanceAgentJobCronParams) (int64, error) {
	result, err := q.db.Exec(ctx, advanceAgentJobCron,
		arg.NextFireAt,
		arg.OccurrenceAt,
		arg.CronID,
		arg.PriorNextFireAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteAgentJobCronsByAgentExcept = `-- name: DeleteAgentJobCronsByAgentExcept :exec
DELETE FROM agent_job_crons
WHERE agent_id = $1 AND slug != ALL($2::text[])
`

type DeleteAgentJobCronsByAgentExceptParams struct {
	AgentID pgtype.UUID `json:"agent_id"`
	Slugs   []string    `json:"slugs"`
}

func (q *Queries) DeleteAgentJobCronsByAgentExcept(ctx context.Context, arg DeleteAgentJobCronsByAgentExceptParams) error {
	_, err := q.db.Exec(ctx, deleteAgentJobCronsByAgentExcept, arg.AgentID, arg.Slugs)
	return err
}

const getAgentJobCron = `-- name: GetAgentJobCron :one
SELECT id, agent_id, slug, schedule, description, handler_name, handler_version, input_schema_hash, output_schema_hash, input_payload, agent_token_version, enabled, next_fire_at, last_fired_at, created_at, updated_at FROM agent_job_crons WHERE agent_id = $1 AND slug = $2
`

type GetAgentJobCronParams struct {
	AgentID pgtype.UUID `json:"agent_id"`
	Slug    string      `json:"slug"`
}

func (q *Queries) GetAgentJobCron(ctx context.Context, arg GetAgentJobCronParams) (AgentJobCron, error) {
	row := q.db.QueryRow(ctx, getAgentJobCron, arg.AgentID, arg.Slug)
	var i AgentJobCron
	err := row.Scan(
		&i.ID,
		&i.AgentID,
		&i.Slug,
		&i.Schedule,
		&i.Description,
		&i.HandlerName,
		&i.HandlerVersion,
		&i.InputSchemaHash,
		&i.OutputSchemaHash,
		&i.InputPayload,
		&i.AgentTokenVersion,
		&i.Enabled,
		&i.NextFireAt,
		&i.LastFiredAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertAgentJobFromCron = `-- name: InsertAgentJobFromCron :one
INSERT INTO agent_jobs (
    id, agent_id, handler_name, handler_version, input_schema_hash,
    output_schema_hash, source_run_id, cron_id, cron_slug, scheduled_at,
    initiator_kind, initiator_user_id, initiator_conversation_id,
    initiator_access, status, timeout_ms, max_attempts, attempt_limit, attempt_count,
    next_attempt_at, input_payload, state_version
)
SELECT
    $1, c.agent_id, c.handler_name, c.handler_version,
    c.input_schema_hash, c.output_schema_hash, NULL, c.id, c.slug,
    $2, $3, $4,
    $5, $6, 'queued', h.timeout_ms,
    h.max_attempts, h.max_attempts, 0, $2, c.input_payload, 1
FROM agent_job_crons c
JOIN agents a ON a.id = c.agent_id
JOIN agent_job_handlers h
  ON h.agent_id = c.agent_id
 AND h.name = c.handler_name
 AND h.version = c.handler_version
WHERE c.id = $7
  AND c.next_fire_at = $2
  AND c.enabled
  AND a.status = 'active'
  AND a.job_dispatch_paused_build_id IS NULL
  AND a.agent_token_version = c.agent_token_version
  AND h.active
  AND h.agent_token_version = c.agent_token_version
  AND h.input_schema_hash = c.input_schema_hash
  AND h.output_schema_hash = c.output_schema_hash
RETURNING agent_jobs.id, agent_jobs.agent_id, agent_jobs.handler_name, agent_jobs.handler_version, agent_jobs.input_schema_hash, agent_jobs.output_schema_hash, agent_jobs.source_run_id, agent_jobs.cron_id, agent_jobs.cron_slug, agent_jobs.initiator_kind, agent_jobs.initiator_user_id, agent_jobs.initiator_conversation_id, agent_jobs.initiator_access, agent_jobs.status, agent_jobs.timeout_ms, agent_jobs.max_attempts, agent_jobs.attempt_limit, agent_jobs.attempt_count, agent_jobs.next_attempt_at, agent_jobs.scheduled_at, agent_jobs.input_payload, agent_jobs.output_payload, agent_jobs.progress_phase, agent_jobs.progress_message, agent_jobs.progress_completed, agent_jobs.progress_total, agent_jobs.progress_attempt, agent_jobs.progress_updated_at, agent_jobs.last_error, agent_jobs.cancel_requested_at, agent_jobs.cancelled_by_user_id, agent_jobs.started_at, agent_jobs.completed_at, agent_jobs.state_version, agent_jobs.created_at, agent_jobs.updated_at
`

type InsertAgentJobFromCronParams struct {
	JobID                   pgtype.UUID        `json:"job_id"`
	ScheduledAt             pgtype.Timestamptz `json:"scheduled_at"`
	InitiatorKind           string             `json:"initiator_kind"`
	InitiatorUserID         pgtype.UUID        `json:"initiator_user_id"`
	InitiatorConversationID pgtype.UUID        `json:"initiator_conversation_id"`
	InitiatorAccess         string             `json:"initiator_access"`
	CronID                  pgtype.UUID        `json:"cron_id"`
}

func (q *Queries) InsertAgentJobFromCron(ctx context.Context, arg InsertAgentJobFromCronParams) (AgentJob, error) {
	row := q.db.QueryRow(ctx, insertAgentJobFromCron,
		arg.JobID,
		arg.ScheduledAt,
		arg.InitiatorKind,
		arg.InitiatorUserID,
		arg.InitiatorConversationID,
		arg.InitiatorAccess,
		arg.CronID,
	)
	var i AgentJob
	err := row.Scan(
		&i.ID,
		&i.AgentID,
		&i.HandlerName,
		&i.HandlerVersion,
		&i.InputSchemaHash,
		&i.OutputSchemaHash,
		&i.SourceRunID,
		&i.CronID,
		&i.CronSlug,
		&i.InitiatorKind,
		&i.InitiatorUserID,
		&i.InitiatorConversationID,
		&i.InitiatorAccess,
		&i.Status,
		&i.TimeoutMs,
		&i.MaxAttempts,
		&i.AttemptLimit,
		&i.AttemptCount,
		&i.NextAttemptAt,
		&i.ScheduledAt,
		&i.InputPayload,
		&i.OutputPayload,
		&i.ProgressPhase,
		&i.ProgressMessage,
		&i.ProgressCompleted,
		&i.ProgressTotal,
		&i.ProgressAttempt,
		&i.ProgressUpdatedAt,
		&i.LastError,
		&i.CancelRequestedAt,
		&i.CancelledByUserID,
		&i.StartedAt,
		&i.CompletedAt,
		&i.StateVersion,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertManualAgentJobFromCron = `-- name: InsertManualAgentJobFromCron :one
INSERT INTO agent_jobs (
    id, agent_id, handler_name, handler_version, input_schema_hash,
    output_schema_hash, source_run_id, cron_id, cron_slug, scheduled_at,
    initiator_kind, initiator_user_id, initiator_conversation_id,
    initiator_access, status, timeout_ms, max_attempts, attempt_limit, attempt_count,
    next_attempt_at, input_payload, state_version
)
SELECT
    $1, c.agent_id, c.handler_name, c.handler_version,
    c.input_schema_hash, c.output_schema_hash, NULL, c.id, c.slug,
    $2, 'user', $3, NULL, 'admin', 'queued',
    h.timeout_ms, h.max_attempts, h.max_attempts, 0, $2, c.input_payload, 1
FROM agent_job_crons c
JOIN agents a ON a.id = c.agent_id
JOIN agent_job_handlers h
  ON h.agent_id = c.agent_id
 AND h.name = c.handler_name
 AND h.version = c.handler_version
WHERE c.id = $4
  AND c.enabled
  AND a.status = 'active'
  AND a.job_dispatch_paused_build_id IS NULL
  AND a.agent_token_version = c.agent_token_version
  AND h.active
  AND h.agent_token_version = c.agent_token_version
  AND h.input_schema_hash = c.input_schema_hash
  AND h.output_schema_hash = c.output_schema_hash
RETURNING agent_jobs.id, agent_jobs.agent_id, agent_jobs.handler_name, agent_jobs.handler_version, agent_jobs.input_schema_hash, agent_jobs.output_schema_hash, agent_jobs.source_run_id, agent_jobs.cron_id, agent_jobs.cron_slug, agent_jobs.initiator_kind, agent_jobs.initiator_user_id, agent_jobs.initiator_conversation_id, agent_jobs.initiator_access, agent_jobs.status, agent_jobs.timeout_ms, agent_jobs.max_attempts, agent_jobs.attempt_limit, agent_jobs.attempt_count, agent_jobs.next_attempt_at, agent_jobs.scheduled_at, agent_jobs.input_payload, agent_jobs.output_payload, agent_jobs.progress_phase, agent_jobs.progress_message, agent_jobs.progress_completed, agent_jobs.progress_total, agent_jobs.progress_attempt, agent_jobs.progress_updated_at, agent_jobs.last_error, agent_jobs.cancel_requested_at, agent_jobs.cancelled_by_user_id, agent_jobs.started_at, agent_jobs.completed_at, agent_jobs.state_version, agent_jobs.created_at, agent_jobs.updated_at
`

type InsertManualAgentJobFromCronParams struct {
	JobID           pgtype.UUID        `json:"job_id"`
	ScheduledAt     pgtype.Timestamptz `json:"scheduled_at"`
	InitiatorUserID pgtype.UUID        `json:"initiator_user_id"`
	CronID          pgtype.UUID        `json:"cron_id"`
}

func (q *Queries) InsertManualAgentJobFromCron(ctx context.Context, arg InsertManualAgentJobFromCronParams) (AgentJob, error) {
	row := q.db.QueryRow(ctx, insertManualAgentJobFromCron,
		arg.JobID,
		arg.ScheduledAt,
		arg.InitiatorUserID,
		arg.CronID,
	)
	var i AgentJob
	err := row.Scan(
		&i.ID,
		&i.AgentID,
		&i.HandlerName,
		&i.HandlerVersion,
		&i.InputSchemaHash,
		&i.OutputSchemaHash,
		&i.SourceRunID,
		&i.CronID,
		&i.CronSlug,
		&i.InitiatorKind,
		&i.InitiatorUserID,
		&i.InitiatorConversationID,
		&i.InitiatorAccess,
		&i.Status,
		&i.TimeoutMs,
		&i.MaxAttempts,
		&i.AttemptLimit,
		&i.AttemptCount,
		&i.NextAttemptAt,
		&i.ScheduledAt,
		&i.InputPayload,
		&i.OutputPayload,
		&i.ProgressPhase,
		&i.ProgressMessage,
		&i.ProgressCompleted,
		&i.ProgressTotal,
		&i.ProgressAttempt,
		&i.ProgressUpdatedAt,
		&i.LastError,
		&i.CancelRequestedAt,
		&i.CancelledByUserID,
		&i.StartedAt,
		&i.CompletedAt,
		&i.StateVersion,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAgentJobCronsByAgent = `-- name: ListAgentJobCronsByAgent :many
SELECT id, agent_id, slug, schedule, description, handler_name, handler_version, input_schema_hash, output_schema_hash, input_payload, agent_token_version, enabled, next_fire_at, last_fired_at, created_at, updated_at FROM agent_job_crons WHERE agent_id = $1 ORDER BY slug
`

func (q *Queries) ListAgentJobCronsByAgent(ctx context.Context, agentID pgtype.UUID) ([]AgentJobCron, error) {
	rows, err := q.db.Query(ctx, listAgentJobCronsByAgent, agentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AgentJobCron{}
	for rows.Next() {
		var i AgentJobCron
		if err := rows.Scan(
			&i.ID,
			&i.AgentID,
			&i.Slug,
			&i.Schedule,
			&i.Description,
			&i.HandlerName,
			&i.HandlerVersion,
			&i.InputSchemaHash,
			&i.OutputSchemaHash,
			&i.InputPayload,
			&i.AgentTokenVersion,
			&i.Enabled,
			&i.NextFireAt,
			&i.LastFiredAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSchedulesWithNextFire = `-- name: ListSchedulesWithNextFire :many
SELECT id, agent_id, slug, schedule AS recurrence, handler_name, handler_version,
       enabled, description, last_fired_at, next_fire_at, created_at
FROM agent_job_crons
WHERE agent_id = $1
ORDER BY slug
`

type ListSchedulesWithNextFireRow struct {
	ID             pgtype.UUID        `json:"id"`
	AgentID        pgtype.UUID        `json:"agent_id"`
	Slug           string             `json:"slug"`
	Recurrence     string             `json:"recurrence"`
	HandlerName    string             `json:"handler_name"`
	HandlerVersion int32              `json:"handler_version"`
	Enabled        bool               `json:"enabled"`
	Description    string             `json:"description"`
	LastFiredAt    pgtype.Timestamptz `json:"last_fired_at"`
	NextFireAt     pgtype.Timestamptz `json:"next_fire_at"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) ListSchedulesWithNextFire(ctx context.Context, agentID pgtype.UUID) ([]ListSchedulesWithNextFireRow, error) {
	rows, err := q.db.Query(ctx, listSchedulesWithNextFire, agentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSchedulesWithNextFireRow{}
	for rows.Next() {
		var i ListSchedulesWithNextFireRow
		if err := rows.Scan(
			&i.ID,
			&i.AgentID,
			&i.Slug,
			&i.Recurrence,
			&i.HandlerName,
			&i.HandlerVersion,
			&i.Enabled,
			&i.Description,
			&i.LastFiredAt,
			&i.NextFireAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const selectDueAgentJobCrons = `-- name: SelectDueAgentJobCrons :many
SELECT c.id, c.agent_id, c.slug, c.schedule, c.description, c.handler_name, c.handler_version, c.input_schema_hash, c.output_schema_hash, c.input_payload, c.agent_token_version, c.enabled, c.next_fire_at, c.last_fired_at, c.created_at, c.updated_at
FROM agent_job_crons c
JOIN agents a ON a.id = c.agent_id
JOIN agent_job_handlers h
  ON h.agent_id = c.agent_id
 AND h.name = c.handler_name
 AND h.version = c.handler_version
WHERE c.enabled
  AND c.next_fire_at <= now()
  AND a.status = 'active'
  AND a.job_dispatch_paused_build_id IS NULL
  AND a.agent_token_version = c.agent_token_version
  AND h.active
  AND h.agent_token_version = c.agent_token_version
  AND h.input_schema_hash = c.input_schema_hash
  AND h.output_schema_hash = c.output_schema_hash
ORDER BY c.next_fire_at, c.id
LIMIT $1
FOR UPDATE OF a, c SKIP LOCKED
`

func (q *Queries) SelectDueAgentJobCrons(ctx context.Context, batchSize int32) ([]AgentJobCron, error) {
	rows, err := q.db.Query(ctx, selectDueAgentJobCrons, batchSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AgentJobCron{}
	for rows.Next() {
		var i AgentJobCron
		if err := rows.Scan(
			&i.ID,
			&i.AgentID,
			&i.Slug,
			&i.Schedule,
			&i.Description,
			&i.HandlerName,
			&i.HandlerVersion,
			&i.InputSchemaHash,
			&i.OutputSchemaHash,
			&i.InputPayload,
			&i.AgentTokenVersion,
			&i.Enabled,
			&i.NextFireAt,
			&i.LastFiredAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertAgentJobCron = `-- name: UpsertAgentJobCron :one
INSERT INTO agent_job_crons (
    agent_id, slug, schedule, description, handler_name, handler_version,
    input_schema_hash, output_schema_hash, input_payload, agent_token_version,
    enabled, next_fire_at
)
VALUES (
    $1, $2, $3, $4, $5, $6,
    $7, $8, $9, $10,
    true, $11
)
ON CONFLICT (agent_id, slug) DO UPDATE SET
    schedule = EXCLUDED.schedule,
    description = EXCLUDED.description,
    handler_name = EXCLUDED.handler_name,
    handler_version = EXCLUDED.handler_version,
    input_schema_hash = EXCLUDED.input_schema_hash,
    output_schema_hash = EXCLUDED.output_schema_hash,
    input_payload = EXCLUDED.input_payload,
    agent_token_version = EXCLUDED.agent_token_version,
    next_fire_at = CASE WHEN
        agent_job_crons.schedule = EXCLUDED.schedule
        AND agent_job_crons.handler_name = EXCLUDED.handler_name
        AND agent_job_crons.handler_version = EXCLUDED.handler_version
        AND agent_job_crons.input_schema_hash = EXCLUDED.input_schema_hash
        AND agent_job_crons.output_schema_hash = EXCLUDED.output_schema_hash
        AND agent_job_crons.input_payload = EXCLUDED.input_payload
        THEN agent_job_crons.next_fire_at
        ELSE EXCLUDED.next_fire_at
    END,
    updated_at = now()
RETURNING id, agent_id, slug, schedule, description, handler_name, handler_version, input_schema_hash, output_schema_hash, input_payload, agent_token_version, enabled, next_fire_at, last_fired_at, created_at, updated_at
`

type UpsertAgentJobCronParams struct {
	AgentID           pgtype.UUID        `json:"agent_id"`
	Slug              string             `json:"slug"`
	Schedule          string             `json:"schedule"`
	Description       string             `json:"description"`
	HandlerName       string             `json:"handler_name"`
	HandlerVersion    int32              `json:"handler_version"`
	InputSchemaHash   string             `json:"input_schema_hash"`
	OutputSchemaHash  string             `json:"output_schema_hash"`
	InputPayload      []byte             `json:"input_payload"`
	AgentTokenVersion int64              `json:"agent_token_version"`
	NextFireAt        pgtype.Timestamptz `json:"next_fire_at"`
}

func (q *Queries) UpsertAgentJobCron(ctx context.Context, arg UpsertAgentJobCronParams) (AgentJobCron, error) {
	row := q.db.QueryRow(ctx, upsertAgentJobCron,
		arg.AgentID,
		arg.Slug,
		arg.Schedule,
		arg.Description,
		arg.HandlerName,
		arg.HandlerVersion,
		arg.InputSchemaHash,
		arg.OutputSchemaHash,
		arg.InputPayload,
		arg.AgentTokenVersion,
		arg.NextFireAt,
	)
	var i AgentJobCron
	err := row.Scan(
		&i.ID,
		&i.AgentID,
		&i.Slug,
		&i.Schedule,
		&i.Description,
		&i.HandlerName,
		&i.HandlerVersion,
		&i.InputSchemaHash,
		&i.OutputSchemaHash,
		&i.InputPayload,
		&i.AgentTokenVersion,
		&i.Enabled,
		&i.NextFireAt,
		&i.LastFiredAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
