// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: agent_members.sql

package dbq

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addAgentMember = `-- name: AddAgentMember :exec
INSERT INTO agent_members (agent_id, user_id, role)
VALUES ($1, $2, $3)
ON CONFLICT (agent_id, user_id) DO UPDATE SET role = EXCLUDED.role
`

type AddAgentMemberParams struct {
	AgentID pgtype.UUID `json:"agent_id"`
	UserID  pgtype.UUID `json:"user_id"`
	Role    string      `json:"role"`
}

func (q *Queries) AddAgentMember(ctx context.Context, arg AddAgentMemberParams) error {
	_, err := q.db.Exec(ctx, addAgentMember, arg.AgentID, arg.UserID, arg.Role)
	return err
}

const getAgentMember = `-- name: GetAgentMember :one
SELECT agent_id, user_id, role, created_at FROM agent_members WHERE agent_id = $1 AND user_id = $2
`

type GetAgentMemberParams struct {
	AgentID pgtype.UUID `json:"agent_id"`
	UserID  pgtype.UUID `json:"user_id"`
}

func (q *Queries) GetAgentMember(ctx context.Context, arg GetAgentMemberParams) (AgentMember, error) {
	row := q.db.QueryRow(ctx, getAgentMember, arg.AgentID, arg.UserID)
	var i AgentMember
	err := row.Scan(
		&i.AgentID,
		&i.UserID,
		&i.Role,
		&i.CreatedAt,
	)
	return i, err
}

const hasAgentAccess = `-- name: HasAgentAccess :one
SELECT EXISTS(
    SELECT 1 FROM agent_members
    WHERE agent_id = $1 AND user_id = $2
) AS has_access
`

type HasAgentAccessParams struct {
	AgentID pgtype.UUID `json:"agent_id"`
	UserID  pgtype.UUID `json:"user_id"`
}

func (q *Queries) HasAgentAccess(ctx context.Context, arg HasAgentAccessParams) (bool, error) {
	row := q.db.QueryRow(ctx, hasAgentAccess, arg.AgentID, arg.UserID)
	var has_access bool
	err := row.Scan(&has_access)
	return has_access, err
}

const listAgentIDsByMember = `-- name: ListAgentIDsByMember :many
SELECT agent_id FROM agent_members WHERE user_id = $1
`

// Used by the WS upgrade handler to auto-subscribe a fresh connection to
// every agent the user has access to. The WS connection receives events
// for all these topics; the client filters by topic/conversation before
// rendering.
func (q *Queries) ListAgentIDsByMember(ctx context.Context, userID pgtype.UUID) ([]pgtype.UUID, error) {
	rows, err := q.db.Query(ctx, listAgentIDsByMember, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []pgtype.UUID{}
	for rows.Next() {
		var agent_id pgtype.UUID
		if err := rows.Scan(&agent_id); err != nil {
			return nil, err
		}
		items = append(items, agent_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAgentMembers = `-- name: ListAgentMembers :many
SELECT am.agent_id, am.user_id, am.role, am.created_at,
       u.email, u.display_name
FROM agent_members am
JOIN users u ON u.id = am.user_id
WHERE am.agent_id = $1
ORDER BY am.created_at
`

type ListAgentMembersRow struct {
	AgentID     pgtype.UUID        `json:"agent_id"`
	UserID      pgtype.UUID        `json:"user_id"`
	Role        string             `json:"role"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	Email       string             `json:"email"`
	DisplayName string             `json:"display_name"`
}

func (q *Queries) ListAgentMembers(ctx context.Context, agentID pgtype.UUID) ([]ListAgentMembersRow, error) {
	rows, err := q.db.Query(ctx, listAgentMembers, agentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAgentMembersRow{}
	for rows.Next() {
		var i ListAgentMembersRow
		if err := rows.Scan(
			&i.AgentID,
			&i.UserID,
			&i.Role,
			&i.CreatedAt,
			&i.Email,
			&i.DisplayName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserAgentMemberships = `-- name: ListUserAgentMemberships :many
SELECT a.id, a.slug, a.name, am.role, am.created_at
FROM agent_members am
JOIN agents a ON a.id = am.agent_id
WHERE am.user_id = $1
ORDER BY a.slug
`

type ListUserAgentMembershipsRow struct {
	ID        pgtype.UUID        `json:"id"`
	Slug      string             `json:"slug"`
	Name      string             `json:"name"`
	Role      string             `json:"role"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

// For sysagent's whoami tool: one row per agent the user is a member
// of, with role + the agent's slug/name. Lets the LLM ground itself
// on what the user can do across agents in one call rather than
// per-agent lookups.
func (q *Queries) ListUserAgentMemberships(ctx context.Context, userID pgtype.UUID) ([]ListUserAgentMembershipsRow, error) {
	rows, err := q.db.Query(ctx, listUserAgentMemberships, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUserAgentMembershipsRow{}
	for rows.Next() {
		var i ListUserAgentMembershipsRow
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Name,
			&i.Role,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeAgentMember = `-- name: RemoveAgentMember :exec
DELETE FROM agent_members WHERE agent_id = $1 AND user_id = $2
`

type RemoveAgentMemberParams struct {
	AgentID pgtype.UUID `json:"agent_id"`
	UserID  pgtype.UUID `json:"user_id"`
}

func (q *Queries) RemoveAgentMember(ctx context.Context, arg RemoveAgentMemberParams) error {
	_, err := q.db.Exec(ctx, removeAgentMember, arg.AgentID, arg.UserID)
	return err
}
