// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: agent_builds.sql

package dbq

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAgentBuild = `-- name: CreateAgentBuild :one
INSERT INTO agent_builds (
    agent_id, type, status, instructions,
    source_ref, image_ref, sol_log, docker_log, log_seq, error_message,
    llm_calls, llm_tokens_in, llm_tokens_out, llm_tokens_cached, llm_cost_estimate,
    rollback_target_id, sdk_version, todos, exit_status, exit_message
)
VALUES (
    $1, $2, 'building', $3,
    '', '', '', '', 0, '',
    0, 0, 0, 0, 0,
    $4, '', '[]', '', ''
)
RETURNING id, agent_id, type, status, instructions, source_ref, image_ref, sol_log, docker_log, log_seq, error_message, started_at, finished_at, llm_calls, llm_tokens_in, llm_tokens_out, llm_tokens_cached, llm_cost_estimate, rollback_target_id, sdk_version, todos, exit_status, exit_message, failure_kind
`

type CreateAgentBuildParams struct {
	AgentID          pgtype.UUID `json:"agent_id"`
	Type             string      `json:"type"`
	Instructions     string      `json:"instructions"`
	RollbackTargetID pgtype.UUID `json:"rollback_target_id"`
}

// Initial-row INSERT. Status starts 'building'; output fields start empty
// and are filled by UpdateAgentBuildComplete / UpdateAgentBuildLogs. LLM
// telemetry starts at 0 (no codegen spend yet) — set explicitly per the
// "no fake defaults" rule, mirroring CreateRun; UpdateBuildLLMStats fills
// it from the llm_usage ledger when codegen finishes.
func (q *Queries) CreateAgentBuild(ctx context.Context, arg CreateAgentBuildParams) (AgentBuild, error) {
	row := q.db.QueryRow(ctx, createAgentBuild,
		arg.AgentID,
		arg.Type,
		arg.Instructions,
		arg.RollbackTargetID,
	)
	var i AgentBuild
	err := row.Scan(
		&i.ID,
		&i.AgentID,
		&i.Type,
		&i.Status,
		&i.Instructions,
		&i.SourceRef,
		&i.ImageRef,
		&i.SolLog,
		&i.DockerLog,
		&i.LogSeq,
		&i.ErrorMessage,
		&i.StartedAt,
		&i.FinishedAt,
		&i.LlmCalls,
		&i.LlmTokensIn,
		&i.LlmTokensOut,
		&i.LlmTokensCached,
		&i.LlmCostEstimate,
		&i.RollbackTargetID,
		&i.SdkVersion,
		&i.Todos,
		&i.ExitStatus,
		&i.ExitMessage,
		&i.FailureKind,
	)
	return i, err
}

const getAgentBuild = `-- name: GetAgentBuild :one
SELECT id, agent_id, type, status, instructions, source_ref, image_ref, sol_log, docker_log, log_seq, error_message, started_at, finished_at, llm_calls, llm_tokens_in, llm_tokens_out, llm_tokens_cached, llm_cost_estimate, rollback_target_id, sdk_version, todos, exit_status, exit_message, failure_kind FROM agent_builds WHERE id = $1
`

func (q *Queries) GetAgentBuild(ctx context.Context, id pgtype.UUID) (AgentBuild, error) {
	row := q.db.QueryRow(ctx, getAgentBuild, id)
	var i AgentBuild
	err := row.Scan(
		&i.ID,
		&i.AgentID,
		&i.Type,
		&i.Status,
		&i.Instructions,
		&i.SourceRef,
		&i.ImageRef,
		&i.SolLog,
		&i.DockerLog,
		&i.LogSeq,
		&i.ErrorMessage,
		&i.StartedAt,
		&i.FinishedAt,
		&i.LlmCalls,
		&i.LlmTokensIn,
		&i.LlmTokensOut,
		&i.LlmTokensCached,
		&i.LlmCostEstimate,
		&i.RollbackTargetID,
		&i.SdkVersion,
		&i.Todos,
		&i.ExitStatus,
		&i.ExitMessage,
		&i.FailureKind,
	)
	return i, err
}

const getLatestBuildForAgent = `-- name: GetLatestBuildForAgent :one
SELECT id, agent_id, type, status, instructions, source_ref, image_ref, sol_log, docker_log, log_seq, error_message, started_at, finished_at, llm_calls, llm_tokens_in, llm_tokens_out, llm_tokens_cached, llm_cost_estimate, rollback_target_id, sdk_version, todos, exit_status, exit_message, failure_kind FROM agent_builds WHERE agent_id = $1 ORDER BY started_at DESC LIMIT 1
`

func (q *Queries) GetLatestBuildForAgent(ctx context.Context, agentID pgtype.UUID) (AgentBuild, error) {
	row := q.db.QueryRow(ctx, getLatestBuildForAgent, agentID)
	var i AgentBuild
	err := row.Scan(
		&i.ID,
		&i.AgentID,
		&i.Type,
		&i.Status,
		&i.Instructions,
		&i.SourceRef,
		&i.ImageRef,
		&i.SolLog,
		&i.DockerLog,
		&i.LogSeq,
		&i.ErrorMessage,
		&i.StartedAt,
		&i.FinishedAt,
		&i.LlmCalls,
		&i.LlmTokensIn,
		&i.LlmTokensOut,
		&i.LlmTokensCached,
		&i.LlmCostEstimate,
		&i.RollbackTargetID,
		&i.SdkVersion,
		&i.Todos,
		&i.ExitStatus,
		&i.ExitMessage,
		&i.FailureKind,
	)
	return i, err
}

const listAgentBuildsByAgent = `-- name: ListAgentBuildsByAgent :many
SELECT id, agent_id, type, status, instructions, error_message, source_ref, image_ref, started_at, finished_at,
       llm_calls, llm_tokens_in, llm_tokens_out, llm_tokens_cached, llm_cost_estimate,
       rollback_target_id, sdk_version, exit_status, exit_message, failure_kind
FROM agent_builds
WHERE agent_id = $1
ORDER BY started_at DESC
LIMIT 50
`

type ListAgentBuildsByAgentRow struct {
	ID               pgtype.UUID        `json:"id"`
	AgentID          pgtype.UUID        `json:"agent_id"`
	Type             string             `json:"type"`
	Status           string             `json:"status"`
	Instructions     string             `json:"instructions"`
	ErrorMessage     string             `json:"error_message"`
	SourceRef        string             `json:"source_ref"`
	ImageRef         string             `json:"image_ref"`
	StartedAt        pgtype.Timestamptz `json:"started_at"`
	FinishedAt       pgtype.Timestamptz `json:"finished_at"`
	LlmCalls         int32              `json:"llm_calls"`
	LlmTokensIn      int32              `json:"llm_tokens_in"`
	LlmTokensOut     int32              `json:"llm_tokens_out"`
	LlmTokensCached  int32              `json:"llm_tokens_cached"`
	LlmCostEstimate  float64            `json:"llm_cost_estimate"`
	RollbackTargetID pgtype.UUID        `json:"rollback_target_id"`
	SdkVersion       string             `json:"sdk_version"`
	ExitStatus       string             `json:"exit_status"`
	ExitMessage      string             `json:"exit_message"`
	FailureKind      string             `json:"failure_kind"`
}

func (q *Queries) ListAgentBuildsByAgent(ctx context.Context, agentID pgtype.UUID) ([]ListAgentBuildsByAgentRow, error) {
	rows, err := q.db.Query(ctx, listAgentBuildsByAgent, agentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAgentBuildsByAgentRow{}
	for rows.Next() {
		var i ListAgentBuildsByAgentRow
		if err := rows.Scan(
			&i.ID,
			&i.AgentID,
			&i.Type,
			&i.Status,
			&i.Instructions,
			&i.ErrorMessage,
			&i.SourceRef,
			&i.ImageRef,
			&i.StartedAt,
			&i.FinishedAt,
			&i.LlmCalls,
			&i.LlmTokensIn,
			&i.LlmTokensOut,
			&i.LlmTokensCached,
			&i.LlmCostEstimate,
			&i.RollbackTargetID,
			&i.SdkVersion,
			&i.ExitStatus,
			&i.ExitMessage,
			&i.FailureKind,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const resetStuckAgentBuilds = `-- name: ResetStuckAgentBuilds :exec
UPDATE agent_builds SET
    status = 'failed',
    error_message = 'interrupted by Airlock restart',
    finished_at = now()
WHERE status = 'building'
`

func (q *Queries) ResetStuckAgentBuilds(ctx context.Context) error {
	_, err := q.db.Exec(ctx, resetStuckAgentBuilds)
	return err
}

const updateAgentBuildComplete = `-- name: UpdateAgentBuildComplete :exec
UPDATE agent_builds SET
    status = $1,
    error_message = COALESCE($2, ''),
    source_ref = COALESCE($3, ''),
    image_ref = COALESCE($4, ''),
    sdk_version = COALESCE($5, ''),
    exit_status = COALESCE($6, ''),
    exit_message = COALESCE($7, ''),
    failure_kind = COALESCE($8, ''),
    finished_at = now()
WHERE id = $9
`

type UpdateAgentBuildCompleteParams struct {
	Status       string      `json:"status"`
	ErrorMessage string      `json:"error_message"`
	SourceRef    string      `json:"source_ref"`
	ImageRef     string      `json:"image_ref"`
	SdkVersion   string      `json:"sdk_version"`
	ExitStatus   string      `json:"exit_status"`
	ExitMessage  string      `json:"exit_message"`
	FailureKind  string      `json:"failure_kind"`
	ID           pgtype.UUID `json:"id"`
}

func (q *Queries) UpdateAgentBuildComplete(ctx context.Context, arg UpdateAgentBuildCompleteParams) error {
	_, err := q.db.Exec(ctx, updateAgentBuildComplete,
		arg.Status,
		arg.ErrorMessage,
		arg.SourceRef,
		arg.ImageRef,
		arg.SdkVersion,
		arg.ExitStatus,
		arg.ExitMessage,
		arg.FailureKind,
		arg.ID,
	)
	return err
}

const updateAgentBuildLogs = `-- name: UpdateAgentBuildLogs :exec
UPDATE agent_builds SET sol_log = $1, docker_log = $2, log_seq = $3 WHERE id = $4
`

type UpdateAgentBuildLogsParams struct {
	SolLog    string      `json:"sol_log"`
	DockerLog string      `json:"docker_log"`
	LogSeq    int64       `json:"log_seq"`
	ID        pgtype.UUID `json:"id"`
}

func (q *Queries) UpdateAgentBuildLogs(ctx context.Context, arg UpdateAgentBuildLogsParams) error {
	_, err := q.db.Exec(ctx, updateAgentBuildLogs,
		arg.SolLog,
		arg.DockerLog,
		arg.LogSeq,
		arg.ID,
	)
	return err
}

const updateAgentBuildTodos = `-- name: UpdateAgentBuildTodos :exec
UPDATE agent_builds SET todos = $1 WHERE id = $2
`

type UpdateAgentBuildTodosParams struct {
	Todos []byte      `json:"todos"`
	ID    pgtype.UUID `json:"id"`
}

// Persists the agent's current task list (jsonb) as it rewrites it during
// codegen. Separate from UpdateAgentBuildLogs so the todo write cadence is
// independent of the 1s log flush.
func (q *Queries) UpdateAgentBuildTodos(ctx context.Context, arg UpdateAgentBuildTodosParams) error {
	_, err := q.db.Exec(ctx, updateAgentBuildTodos, arg.Todos, arg.ID)
	return err
}

const updateBuildLLMStats = `-- name: UpdateBuildLLMStats :exec
UPDATE agent_builds
SET llm_calls = stats.calls,
    llm_tokens_in = stats.tokens_in,
    llm_tokens_out = stats.tokens_out,
    llm_tokens_cached = stats.tokens_cached,
    llm_cost_estimate = stats.cost
FROM (
    SELECT
        COUNT(*)::integer                        AS calls,
        COALESCE(SUM(tokens_in), 0)::integer     AS tokens_in,
        COALESCE(SUM(tokens_out), 0)::integer    AS tokens_out,
        COALESCE(SUM(tokens_cached), 0)::integer AS tokens_cached,
        COALESCE(SUM(cost_total), 0)::float8     AS cost
    FROM llm_usage
    WHERE build_id = $1
) stats
WHERE agent_builds.id = $1
`

// Build-side parity with UpdateRunLLMStats: aggregates the build's
// token/call/cost totals from the llm_usage ledger (rows the build
// codegen runner wrote with build_id; cost already computed per-row).
// Idempotent — recomputes the SUM each call. A build with no ledger
// rows zeroes out (correct — no codegen spend recorded).
func (q *Queries) UpdateBuildLLMStats(ctx context.Context, buildID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, updateBuildLLMStats, buildID)
	return err
}
