// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: agent_siblings.sql

package dbq

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addSiblingIfAllowed = `-- name: AddSiblingIfAllowed :execrows
INSERT INTO agent_siblings (parent_agent_id, sibling_agent_id)
SELECT $1, $2
WHERE EXISTS (
    SELECT 1 FROM agent_grants
    WHERE agent_grants.agent_id = $2
      AND agent_grants.grantee_id = $3
) OR EXISTS (
    SELECT 1 FROM agents
    WHERE agents.id = $2 AND agents.allow_non_member_mcp = true
)
`

type AddSiblingIfAllowedParams struct {
	ParentAgentID  pgtype.UUID `json:"parent_agent_id"`
	SiblingAgentID pgtype.UUID `json:"sibling_agent_id"`
	UserID         pgtype.UUID `json:"user_id"`
}

// Atomic add: the row only lands if the user is either a member of the
// sibling, OR the sibling has allow_non_member_mcp = true. Encoded as
// INSERT ... SELECT ... WHERE EXISTS so there is no separate
// check-then-act race. Caller reads RowsAffected: 0 → 403,
// 1 → success, PK violation → 409 (already present).
func (q *Queries) AddSiblingIfAllowed(ctx context.Context, arg AddSiblingIfAllowedParams) (int64, error) {
	result, err := q.db.Exec(ctx, addSiblingIfAllowed, arg.ParentAgentID, arg.SiblingAgentID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const isUserAllowedAddSibling = `-- name: IsUserAllowedAddSibling :one
SELECT (EXISTS (
    SELECT 1 FROM agent_grants
    WHERE agent_grants.agent_id = $1
      AND agent_grants.grantee_id = $2
) OR EXISTS (
    SELECT 1 FROM agents
    WHERE agents.id = $1 AND agents.allow_non_member_mcp = true
)) AS allowed
`

type IsUserAllowedAddSiblingParams struct {
	SiblingAgentID pgtype.UUID `json:"sibling_agent_id"`
	UserID         pgtype.UUID `json:"user_id"`
}

// Read-side helper for the "addable agents" picker. True iff the user
// is a member of the candidate sibling OR the candidate sibling has
// allow_non_member_mcp = true. Not used by the mutation (which
// inlines the predicate atomically) — only by GET /siblings/addable.
func (q *Queries) IsUserAllowedAddSibling(ctx context.Context, arg IsUserAllowedAddSiblingParams) (pgtype.Bool, error) {
	row := q.db.QueryRow(ctx, isUserAllowedAddSibling, arg.SiblingAgentID, arg.UserID)
	var allowed pgtype.Bool
	err := row.Scan(&allowed)
	return allowed, err
}

const listAddableSiblings = `-- name: ListAddableSiblings :many
SELECT a.id, a.slug, a.name, a.description, a.allow_non_member_mcp,
       EXISTS (
           SELECT 1 FROM agent_grants
           WHERE agent_grants.agent_id = a.id
             AND agent_grants.grantee_id = $1
       ) AS is_member
FROM agents a
WHERE a.id <> $2
  AND NOT EXISTS (
      SELECT 1 FROM agent_siblings
      WHERE agent_siblings.parent_agent_id = $2
        AND agent_siblings.sibling_agent_id = a.id
  )
  AND (
      EXISTS (
          SELECT 1 FROM agent_grants
          WHERE agent_grants.agent_id = a.id
            AND agent_grants.grantee_id = $1
      )
      OR a.allow_non_member_mcp = true
  )
ORDER BY is_member DESC, a.created_at DESC
`

type ListAddableSiblingsParams struct {
	UserID        pgtype.UUID `json:"user_id"`
	ParentAgentID pgtype.UUID `json:"parent_agent_id"`
}

type ListAddableSiblingsRow struct {
	ID                pgtype.UUID `json:"id"`
	Slug              string      `json:"slug"`
	Name              string      `json:"name"`
	Description       string      `json:"description"`
	AllowNonMemberMcp bool        `json:"allow_non_member_mcp"`
	IsMember          bool        `json:"is_member"`
}

// The set of agents the editing user MAY add as siblings of @parent_agent_id,
// excluding the parent itself and any already-added siblings. Order:
// members first, then non-member-open agents; within each, by recency.
func (q *Queries) ListAddableSiblings(ctx context.Context, arg ListAddableSiblingsParams) ([]ListAddableSiblingsRow, error) {
	rows, err := q.db.Query(ctx, listAddableSiblings, arg.UserID, arg.ParentAgentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAddableSiblingsRow{}
	for rows.Next() {
		var i ListAddableSiblingsRow
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Name,
			&i.Description,
			&i.AllowNonMemberMcp,
			&i.IsMember,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSiblings = `-- name: ListSiblings :many
SELECT a.id, a.slug, a.name, a.description,
       a.allow_non_member_mcp, a.allow_public_mcp,
       s.created_at
FROM agent_siblings s
JOIN agents a ON a.id = s.sibling_agent_id
WHERE s.parent_agent_id = $1
ORDER BY s.created_at
`

type ListSiblingsRow struct {
	ID                pgtype.UUID        `json:"id"`
	Slug              string             `json:"slug"`
	Name              string             `json:"name"`
	Description       string             `json:"description"`
	AllowNonMemberMcp bool               `json:"allow_non_member_mcp"`
	AllowPublicMcp    bool               `json:"allow_public_mcp"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
}

// Returns every agent on the caller's address book with the data the
// prompt renderer needs (id, slug, name, description). Tool schemas
// come from a separate ListAgentTools call per sibling — kept
// separate to keep this query stable as agent_tools evolves.
func (q *Queries) ListSiblings(ctx context.Context, parentAgentID pgtype.UUID) ([]ListSiblingsRow, error) {
	rows, err := q.db.Query(ctx, listSiblings, parentAgentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSiblingsRow{}
	for rows.Next() {
		var i ListSiblingsRow
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Name,
			&i.Description,
			&i.AllowNonMemberMcp,
			&i.AllowPublicMcp,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVisibleSiblings = `-- name: ListVisibleSiblings :many
SELECT a.id
FROM agent_siblings s
JOIN agents a ON a.id = s.sibling_agent_id
WHERE s.parent_agent_id = $1
  AND (
      a.allow_non_member_mcp = true
      OR EXISTS (
          SELECT 1 FROM agent_grants
          WHERE agent_grants.agent_id = a.id
            AND agent_grants.grantee_id = $2
      )
  )
`

type ListVisibleSiblingsParams struct {
	ParentAgentID pgtype.UUID `json:"parent_agent_id"`
	UserID        pgtype.UUID `json:"user_id"`
}

// Used by the dispatcher at run dispatch time to compute the set of
// siblings this run's user can call. Returns the sibling agent IDs
// that pass the access ladder for the supplied user:
//   - user is a member of the sibling, OR
//   - the sibling has allow_non_member_mcp = true.
//
// For anonymous runs (no user), pass uuid_nil as @user_id; the
// EXISTS check on agent_grants fails, leaving only the
// non-member-open siblings.
func (q *Queries) ListVisibleSiblings(ctx context.Context, arg ListVisibleSiblingsParams) ([]pgtype.UUID, error) {
	rows, err := q.db.Query(ctx, listVisibleSiblings, arg.ParentAgentID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []pgtype.UUID{}
	for rows.Next() {
		var id pgtype.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeSibling = `-- name: RemoveSibling :exec
DELETE FROM agent_siblings
WHERE parent_agent_id = $1 AND sibling_agent_id = $2
`

type RemoveSiblingParams struct {
	ParentAgentID  pgtype.UUID `json:"parent_agent_id"`
	SiblingAgentID pgtype.UUID `json:"sibling_agent_id"`
}

func (q *Queries) RemoveSibling(ctx context.Context, arg RemoveSiblingParams) error {
	_, err := q.db.Exec(ctx, removeSibling, arg.ParentAgentID, arg.SiblingAgentID)
	return err
}
