// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: bridges.sql

package dbq

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createBridge = `-- name: CreateBridge :one
INSERT INTO bridges (type, name, bot_token_ref, bot_username, agent_id, owner_id, is_system, managed, telegram_bot_user_id, status, config, settings)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, 'active', '{}'::jsonb, '{}'::jsonb)
RETURNING id, agent_id, owner_id, type, name, bot_username, status, is_system, config, settings, bot_token_ref, last_polled_at, created_at, updated_at, managed, telegram_bot_user_id
`

type CreateBridgeParams struct {
	Type              string      `json:"type"`
	Name              string      `json:"name"`
	BotTokenRef       string      `json:"bot_token_ref"`
	BotUsername       string      `json:"bot_username"`
	AgentID           pgtype.UUID `json:"agent_id"`
	OwnerID           pgtype.UUID `json:"owner_id"`
	IsSystem          bool        `json:"is_system"`
	Managed           bool        `json:"managed"`
	TelegramBotUserID pgtype.Int8 `json:"telegram_bot_user_id"`
}

func (q *Queries) CreateBridge(ctx context.Context, arg CreateBridgeParams) (Bridge, error) {
	row := q.db.QueryRow(ctx, createBridge,
		arg.Type,
		arg.Name,
		arg.BotTokenRef,
		arg.BotUsername,
		arg.AgentID,
		arg.OwnerID,
		arg.IsSystem,
		arg.Managed,
		arg.TelegramBotUserID,
	)
	var i Bridge
	err := row.Scan(
		&i.ID,
		&i.AgentID,
		&i.OwnerID,
		&i.Type,
		&i.Name,
		&i.BotUsername,
		&i.Status,
		&i.IsSystem,
		&i.Config,
		&i.Settings,
		&i.BotTokenRef,
		&i.LastPolledAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Managed,
		&i.TelegramBotUserID,
	)
	return i, err
}

const deleteBridge = `-- name: DeleteBridge :exec
DELETE FROM bridges WHERE id = $1
`

func (q *Queries) DeleteBridge(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteBridge, id)
	return err
}

const getBridgeByAgentID = `-- name: GetBridgeByAgentID :one
SELECT id, agent_id, owner_id, type, name, bot_username, status, is_system, config, settings, bot_token_ref, last_polled_at, created_at, updated_at, managed, telegram_bot_user_id FROM bridges WHERE agent_id = $1
`

// Find the bridge bound to a specific agent
func (q *Queries) GetBridgeByAgentID(ctx context.Context, agentID pgtype.UUID) (Bridge, error) {
	row := q.db.QueryRow(ctx, getBridgeByAgentID, agentID)
	var i Bridge
	err := row.Scan(
		&i.ID,
		&i.AgentID,
		&i.OwnerID,
		&i.Type,
		&i.Name,
		&i.BotUsername,
		&i.Status,
		&i.IsSystem,
		&i.Config,
		&i.Settings,
		&i.BotTokenRef,
		&i.LastPolledAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Managed,
		&i.TelegramBotUserID,
	)
	return i, err
}

const getBridgeByID = `-- name: GetBridgeByID :one
SELECT id, agent_id, owner_id, type, name, bot_username, status, is_system, config, settings, bot_token_ref, last_polled_at, created_at, updated_at, managed, telegram_bot_user_id FROM bridges WHERE id = $1
`

func (q *Queries) GetBridgeByID(ctx context.Context, id pgtype.UUID) (Bridge, error) {
	row := q.db.QueryRow(ctx, getBridgeByID, id)
	var i Bridge
	err := row.Scan(
		&i.ID,
		&i.AgentID,
		&i.OwnerID,
		&i.Type,
		&i.Name,
		&i.BotUsername,
		&i.Status,
		&i.IsSystem,
		&i.Config,
		&i.Settings,
		&i.BotTokenRef,
		&i.LastPolledAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Managed,
		&i.TelegramBotUserID,
	)
	return i, err
}

const getBridgeByTelegramBotUserID = `-- name: GetBridgeByTelegramBotUserID :one
SELECT id, agent_id, owner_id, type, name, bot_username, status, is_system, config, settings, bot_token_ref, last_polled_at, created_at, updated_at, managed, telegram_bot_user_id FROM bridges WHERE telegram_bot_user_id = $1 LIMIT 1
`

// Lookup a Telegram bridge by the bot's stable Telegram user_id.
// The manager-bot poller uses this for idempotency: a duplicate
// ManagedBotCreated for the same bot.id (paranoid backstop) no-ops
// instead of inserting a second row.
func (q *Queries) GetBridgeByTelegramBotUserID(ctx context.Context, telegramBotUserID pgtype.Int8) (Bridge, error) {
	row := q.db.QueryRow(ctx, getBridgeByTelegramBotUserID, telegramBotUserID)
	var i Bridge
	err := row.Scan(
		&i.ID,
		&i.AgentID,
		&i.OwnerID,
		&i.Type,
		&i.Name,
		&i.BotUsername,
		&i.Status,
		&i.IsSystem,
		&i.Config,
		&i.Settings,
		&i.BotTokenRef,
		&i.LastPolledAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Managed,
		&i.TelegramBotUserID,
	)
	return i, err
}

const getSystemBridge = `-- name: GetSystemBridge :one
SELECT id, agent_id, owner_id, type, name, bot_username, status, is_system, config, settings, bot_token_ref, last_polled_at, created_at, updated_at, managed, telegram_bot_user_id FROM bridges WHERE is_system LIMIT 1
`

// The system bridge — there should be at most one
func (q *Queries) GetSystemBridge(ctx context.Context) (Bridge, error) {
	row := q.db.QueryRow(ctx, getSystemBridge)
	var i Bridge
	err := row.Scan(
		&i.ID,
		&i.AgentID,
		&i.OwnerID,
		&i.Type,
		&i.Name,
		&i.BotUsername,
		&i.Status,
		&i.IsSystem,
		&i.Config,
		&i.Settings,
		&i.BotTokenRef,
		&i.LastPolledAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Managed,
		&i.TelegramBotUserID,
	)
	return i, err
}

const listActiveBridges = `-- name: ListActiveBridges :many
SELECT id, agent_id, owner_id, type, name, bot_username, status, is_system, config, settings, bot_token_ref, last_polled_at, created_at, updated_at, managed, telegram_bot_user_id FROM bridges WHERE status IN ('active', 'error')
`

// All bridges to start polling on startup. Includes 'error' so a bridge that
// crashed during the previous run gets a fresh poll attempt — the next
// successful poll flips it back to 'active' via UpdateBridgeLastPolled.
func (q *Queries) ListActiveBridges(ctx context.Context) ([]Bridge, error) {
	rows, err := q.db.Query(ctx, listActiveBridges)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Bridge{}
	for rows.Next() {
		var i Bridge
		if err := rows.Scan(
			&i.ID,
			&i.AgentID,
			&i.OwnerID,
			&i.Type,
			&i.Name,
			&i.BotUsername,
			&i.Status,
			&i.IsSystem,
			&i.Config,
			&i.Settings,
			&i.BotTokenRef,
			&i.LastPolledAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Managed,
			&i.TelegramBotUserID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBridgesAccessible = `-- name: ListBridgesAccessible :many
SELECT b.id, b.agent_id, b.owner_id, b.type, b.name, b.bot_username, b.status, b.is_system, b.config, b.settings, b.bot_token_ref, b.last_polled_at, b.created_at, b.updated_at, b.managed, b.telegram_bot_user_id, u.email AS owner_email, u.display_name AS owner_display_name
FROM bridges b
LEFT JOIN users u ON u.id = b.owner_id
WHERE b.is_system
   OR b.agent_id IN (SELECT agent_id FROM agent_members WHERE user_id = $1)
   OR (b.agent_id IS NULL AND b.owner_id = $1)
ORDER BY b.created_at
`

type ListBridgesAccessibleRow struct {
	ID                pgtype.UUID        `json:"id"`
	AgentID           pgtype.UUID        `json:"agent_id"`
	OwnerID           pgtype.UUID        `json:"owner_id"`
	Type              string             `json:"type"`
	Name              string             `json:"name"`
	BotUsername       string             `json:"bot_username"`
	Status            string             `json:"status"`
	IsSystem          bool               `json:"is_system"`
	Config            []byte             `json:"config"`
	Settings          []byte             `json:"settings"`
	BotTokenRef       string             `json:"bot_token_ref"`
	LastPolledAt      pgtype.Timestamptz `json:"last_polled_at"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
	Managed           bool               `json:"managed"`
	TelegramBotUserID pgtype.Int8        `json:"telegram_bot_user_id"`
	OwnerEmail        pgtype.Text        `json:"owner_email"`
	OwnerDisplayName  pgtype.Text        `json:"owner_display_name"`
}

// Non-admin variant: system bridges plus bridges bound to agents the
// user has access to via agent_members, plus bridges the user owns
// that have since been orphaned (agent deleted but bridge preserved).
// The agent's creator is auto-added to agent_members at agent-create
// time, so the membership check also covers "agents I created."
func (q *Queries) ListBridgesAccessible(ctx context.Context, userID pgtype.UUID) ([]ListBridgesAccessibleRow, error) {
	rows, err := q.db.Query(ctx, listBridgesAccessible, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListBridgesAccessibleRow{}
	for rows.Next() {
		var i ListBridgesAccessibleRow
		if err := rows.Scan(
			&i.ID,
			&i.AgentID,
			&i.OwnerID,
			&i.Type,
			&i.Name,
			&i.BotUsername,
			&i.Status,
			&i.IsSystem,
			&i.Config,
			&i.Settings,
			&i.BotTokenRef,
			&i.LastPolledAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Managed,
			&i.TelegramBotUserID,
			&i.OwnerEmail,
			&i.OwnerDisplayName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBridgesAdmin = `-- name: ListBridgesAdmin :many
SELECT b.id, b.agent_id, b.owner_id, b.type, b.name, b.bot_username, b.status, b.is_system, b.config, b.settings, b.bot_token_ref, b.last_polled_at, b.created_at, b.updated_at, b.managed, b.telegram_bot_user_id, u.email AS owner_email, u.display_name AS owner_display_name
FROM bridges b
LEFT JOIN users u ON u.id = b.owner_id
ORDER BY b.created_at
`

type ListBridgesAdminRow struct {
	ID                pgtype.UUID        `json:"id"`
	AgentID           pgtype.UUID        `json:"agent_id"`
	OwnerID           pgtype.UUID        `json:"owner_id"`
	Type              string             `json:"type"`
	Name              string             `json:"name"`
	BotUsername       string             `json:"bot_username"`
	Status            string             `json:"status"`
	IsSystem          bool               `json:"is_system"`
	Config            []byte             `json:"config"`
	Settings          []byte             `json:"settings"`
	BotTokenRef       string             `json:"bot_token_ref"`
	LastPolledAt      pgtype.Timestamptz `json:"last_polled_at"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
	Managed           bool               `json:"managed"`
	TelegramBotUserID pgtype.Int8        `json:"telegram_bot_user_id"`
	OwnerEmail        pgtype.Text        `json:"owner_email"`
	OwnerDisplayName  pgtype.Text        `json:"owner_display_name"`
}

// Admin variant: every bridge in the tenant with the owner joined for
// the Owner column in the UI. owner_id is NULL for system bridges (and
// for owner-deleted orphans, though those CASCADE today), so LEFT JOIN
// keeps those rows.
func (q *Queries) ListBridgesAdmin(ctx context.Context) ([]ListBridgesAdminRow, error) {
	rows, err := q.db.Query(ctx, listBridgesAdmin)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListBridgesAdminRow{}
	for rows.Next() {
		var i ListBridgesAdminRow
		if err := rows.Scan(
			&i.ID,
			&i.AgentID,
			&i.OwnerID,
			&i.Type,
			&i.Name,
			&i.BotUsername,
			&i.Status,
			&i.IsSystem,
			&i.Config,
			&i.Settings,
			&i.BotTokenRef,
			&i.LastPolledAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Managed,
			&i.TelegramBotUserID,
			&i.OwnerEmail,
			&i.OwnerDisplayName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBridgesByAgentID = `-- name: ListBridgesByAgentID :many
SELECT id FROM bridges WHERE agent_id = $1
`

// All bridges bound to a specific agent. The schema doesn't unique-constrain
// bridges.agent_id, so use this to enumerate before tearing the agent down —
// the agent Delete handler must cancel each poller individually since
// CASCADE delete kills only the DB row, leaving the in-memory goroutine
// polling forever (and racing on the bot token if the bridge is re-added).
func (q *Queries) ListBridgesByAgentID(ctx context.Context, agentID pgtype.UUID) ([]pgtype.UUID, error) {
	rows, err := q.db.Query(ctx, listBridgesByAgentID, agentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []pgtype.UUID{}
	for rows.Next() {
		var id pgtype.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBridgesByOwner = `-- name: ListBridgesByOwner :many
SELECT id FROM bridges WHERE owner_id = $1
`

// All bridges owned by a specific user. Used by service/users.Delete to
// pre-stop the BridgeManager pollers before the ON DELETE CASCADE wipes
// the rows — leaving a goroutine polling a deleted row would race on
// token re-encryption if the user is re-created with the same id.
func (q *Queries) ListBridgesByOwner(ctx context.Context, ownerID pgtype.UUID) ([]pgtype.UUID, error) {
	rows, err := q.db.Query(ctx, listBridgesByOwner, ownerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []pgtype.UUID{}
	for rows.Next() {
		var id pgtype.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBridgesForAgent = `-- name: ListBridgesForAgent :many
SELECT id, agent_id, owner_id, type, name, bot_username, status, is_system, config, settings, bot_token_ref, last_polled_at, created_at, updated_at, managed, telegram_bot_user_id FROM bridges
WHERE agent_id = $1 OR is_system
ORDER BY created_at
`

// Bridges relevant to a specific agent: its own bridge + system bridges.
func (q *Queries) ListBridgesForAgent(ctx context.Context, agentID pgtype.UUID) ([]Bridge, error) {
	rows, err := q.db.Query(ctx, listBridgesForAgent, agentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Bridge{}
	for rows.Next() {
		var i Bridge
		if err := rows.Scan(
			&i.ID,
			&i.AgentID,
			&i.OwnerID,
			&i.Type,
			&i.Name,
			&i.BotUsername,
			&i.Status,
			&i.IsSystem,
			&i.Config,
			&i.Settings,
			&i.BotTokenRef,
			&i.LastPolledAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Managed,
			&i.TelegramBotUserID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateBridgeBinding = `-- name: UpdateBridgeBinding :one
UPDATE bridges
SET agent_id = $1, is_system = $2, updated_at = now()
WHERE id = $3
RETURNING id, agent_id, owner_id, type, name, bot_username, status, is_system, config, settings, bot_token_ref, last_polled_at, created_at, updated_at, managed, telegram_bot_user_id
`

type UpdateBridgeBindingParams struct {
	AgentID  pgtype.UUID `json:"agent_id"`
	IsSystem bool        `json:"is_system"`
	ID       pgtype.UUID `json:"id"`
}

// Rebind the bridge's target. Either is_system=true with NULL agent_id
// (operator surface — routes to the in-airlock sysagent) or is_system=false
// with a non-NULL agent_id (agent surface) — the XOR is enforced by the
// service layer, not the schema. The running poller must be reloaded via
// BridgeManager.AddBridge after this update — it holds AgentID in memory.
func (q *Queries) UpdateBridgeBinding(ctx context.Context, arg UpdateBridgeBindingParams) (Bridge, error) {
	row := q.db.QueryRow(ctx, updateBridgeBinding, arg.AgentID, arg.IsSystem, arg.ID)
	var i Bridge
	err := row.Scan(
		&i.ID,
		&i.AgentID,
		&i.OwnerID,
		&i.Type,
		&i.Name,
		&i.BotUsername,
		&i.Status,
		&i.IsSystem,
		&i.Config,
		&i.Settings,
		&i.BotTokenRef,
		&i.LastPolledAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Managed,
		&i.TelegramBotUserID,
	)
	return i, err
}

const updateBridgeLastPolled = `-- name: UpdateBridgeLastPolled :exec
UPDATE bridges SET last_polled_at = now(), config = $1, status = 'active', updated_at = now() WHERE id = $2
`

type UpdateBridgeLastPolledParams struct {
	Config []byte      `json:"config"`
	ID     pgtype.UUID `json:"id"`
}

// Status flips back to 'active' on every successful poll so a past transient
// failure (network blip, brief upstream hiccup) doesn't leave the row stuck
// at 'error' once the poller recovers.
func (q *Queries) UpdateBridgeLastPolled(ctx context.Context, arg UpdateBridgeLastPolledParams) error {
	_, err := q.db.Exec(ctx, updateBridgeLastPolled, arg.Config, arg.ID)
	return err
}

const updateBridgeSettings = `-- name: UpdateBridgeSettings :one
UPDATE bridges SET settings = $1, updated_at = now() WHERE id = $2
RETURNING id, agent_id, owner_id, type, name, bot_username, status, is_system, config, settings, bot_token_ref, last_polled_at, created_at, updated_at, managed, telegram_bot_user_id
`

type UpdateBridgeSettingsParams struct {
	Settings []byte      `json:"settings"`
	ID       pgtype.UUID `json:"id"`
}

// Replaces the whole settings JSON. Caller is responsible for merging if
// they want partial updates; v1 of the edit dialog sends the full payload.
func (q *Queries) UpdateBridgeSettings(ctx context.Context, arg UpdateBridgeSettingsParams) (Bridge, error) {
	row := q.db.QueryRow(ctx, updateBridgeSettings, arg.Settings, arg.ID)
	var i Bridge
	err := row.Scan(
		&i.ID,
		&i.AgentID,
		&i.OwnerID,
		&i.Type,
		&i.Name,
		&i.BotUsername,
		&i.Status,
		&i.IsSystem,
		&i.Config,
		&i.Settings,
		&i.BotTokenRef,
		&i.LastPolledAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Managed,
		&i.TelegramBotUserID,
	)
	return i, err
}

const updateBridgeStatus = `-- name: UpdateBridgeStatus :exec
UPDATE bridges SET status = $1, updated_at = now() WHERE id = $2
`

type UpdateBridgeStatusParams struct {
	Status string      `json:"status"`
	ID     pgtype.UUID `json:"id"`
}

func (q *Queries) UpdateBridgeStatus(ctx context.Context, arg UpdateBridgeStatusParams) error {
	_, err := q.db.Exec(ctx, updateBridgeStatus, arg.Status, arg.ID)
	return err
}
