// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: connections.sql

package dbq

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const clearConnectionCredentials = `-- name: ClearConnectionCredentials :exec
UPDATE connections SET
    access_token_ref = '',
    refresh_token = '',
    token_expires_at = NULL,
    updated_at = now()
WHERE agent_id = $1 AND slug = $2
`

type ClearConnectionCredentialsParams struct {
	AgentID pgtype.UUID `json:"agent_id"`
	Slug    string      `json:"slug"`
}

// Revoke: clear access_token, refresh_token, expiry
func (q *Queries) ClearConnectionCredentials(ctx context.Context, arg ClearConnectionCredentialsParams) error {
	_, err := q.db.Exec(ctx, clearConnectionCredentials, arg.AgentID, arg.Slug)
	return err
}

const getConnectionBySlug = `-- name: GetConnectionBySlug :one
SELECT id, agent_id, slug, name, description, llm_hint, access, auth_mode, auth_url, token_url, base_url, scopes, auth_injection, test_path, setup_instructions, config, client_id, client_secret, access_token_ref, refresh_token, token_expires_at, created_at, updated_at FROM connections WHERE agent_id = $1 AND slug = $2
`

type GetConnectionBySlugParams struct {
	AgentID pgtype.UUID `json:"agent_id"`
	Slug    string      `json:"slug"`
}

func (q *Queries) GetConnectionBySlug(ctx context.Context, arg GetConnectionBySlugParams) (Connection, error) {
	row := q.db.QueryRow(ctx, getConnectionBySlug, arg.AgentID, arg.Slug)
	var i Connection
	err := row.Scan(
		&i.ID,
		&i.AgentID,
		&i.Slug,
		&i.Name,
		&i.Description,
		&i.LlmHint,
		&i.Access,
		&i.AuthMode,
		&i.AuthUrl,
		&i.TokenUrl,
		&i.BaseUrl,
		&i.Scopes,
		&i.AuthInjection,
		&i.TestPath,
		&i.SetupInstructions,
		&i.Config,
		&i.ClientID,
		&i.ClientSecret,
		&i.AccessTokenRef,
		&i.RefreshToken,
		&i.TokenExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getConnectionForOAuth = `-- name: GetConnectionForOAuth :one
SELECT id, agent_id, slug, name, auth_mode, auth_url, token_url, scopes,
       client_id, client_secret
FROM connections WHERE agent_id = $1 AND slug = $2
`

type GetConnectionForOAuthParams struct {
	AgentID pgtype.UUID `json:"agent_id"`
	Slug    string      `json:"slug"`
}

type GetConnectionForOAuthRow struct {
	ID           pgtype.UUID `json:"id"`
	AgentID      pgtype.UUID `json:"agent_id"`
	Slug         string      `json:"slug"`
	Name         string      `json:"name"`
	AuthMode     string      `json:"auth_mode"`
	AuthUrl      string      `json:"auth_url"`
	TokenUrl     string      `json:"token_url"`
	Scopes       string      `json:"scopes"`
	ClientID     string      `json:"client_id"`
	ClientSecret string      `json:"client_secret"`
}

// For OAuth flow: need auth_url, token_url, scopes, client_id, client_secret
func (q *Queries) GetConnectionForOAuth(ctx context.Context, arg GetConnectionForOAuthParams) (GetConnectionForOAuthRow, error) {
	row := q.db.QueryRow(ctx, getConnectionForOAuth, arg.AgentID, arg.Slug)
	var i GetConnectionForOAuthRow
	err := row.Scan(
		&i.ID,
		&i.AgentID,
		&i.Slug,
		&i.Name,
		&i.AuthMode,
		&i.AuthUrl,
		&i.TokenUrl,
		&i.Scopes,
		&i.ClientID,
		&i.ClientSecret,
	)
	return i, err
}

const getConnectionWithCredentialStatus = `-- name: GetConnectionWithCredentialStatus :one
SELECT id, agent_id, slug, name, description, auth_mode, auth_url, base_url,
       scopes, setup_instructions, test_path,
       (access_token_ref != '') AS authorized,
       (client_id != '') AS has_oauth_app,
       token_expires_at
FROM connections WHERE agent_id = $1 AND slug = $2
`

type GetConnectionWithCredentialStatusParams struct {
	AgentID pgtype.UUID `json:"agent_id"`
	Slug    string      `json:"slug"`
}

type GetConnectionWithCredentialStatusRow struct {
	ID                pgtype.UUID        `json:"id"`
	AgentID           pgtype.UUID        `json:"agent_id"`
	Slug              string             `json:"slug"`
	Name              string             `json:"name"`
	Description       string             `json:"description"`
	AuthMode          string             `json:"auth_mode"`
	AuthUrl           string             `json:"auth_url"`
	BaseUrl           string             `json:"base_url"`
	Scopes            string             `json:"scopes"`
	SetupInstructions string             `json:"setup_instructions"`
	TestPath          string             `json:"test_path"`
	Authorized        bool               `json:"authorized"`
	HasOauthApp       bool               `json:"has_oauth_app"`
	TokenExpiresAt    pgtype.Timestamptz `json:"token_expires_at"`
}

// Returns connection with enough info to determine if authorized
func (q *Queries) GetConnectionWithCredentialStatus(ctx context.Context, arg GetConnectionWithCredentialStatusParams) (GetConnectionWithCredentialStatusRow, error) {
	row := q.db.QueryRow(ctx, getConnectionWithCredentialStatus, arg.AgentID, arg.Slug)
	var i GetConnectionWithCredentialStatusRow
	err := row.Scan(
		&i.ID,
		&i.AgentID,
		&i.Slug,
		&i.Name,
		&i.Description,
		&i.AuthMode,
		&i.AuthUrl,
		&i.BaseUrl,
		&i.Scopes,
		&i.SetupInstructions,
		&i.TestPath,
		&i.Authorized,
		&i.HasOauthApp,
		&i.TokenExpiresAt,
	)
	return i, err
}

const listConnectionsByAgent = `-- name: ListConnectionsByAgent :many
SELECT id, agent_id, slug, name, description, llm_hint, access, auth_mode, auth_url, token_url, base_url, scopes, auth_injection, test_path, setup_instructions, config, client_id, client_secret, access_token_ref, refresh_token, token_expires_at, created_at, updated_at FROM connections WHERE agent_id = $1
`

func (q *Queries) ListConnectionsByAgent(ctx context.Context, agentID pgtype.UUID) ([]Connection, error) {
	rows, err := q.db.Query(ctx, listConnectionsByAgent, agentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Connection{}
	for rows.Next() {
		var i Connection
		if err := rows.Scan(
			&i.ID,
			&i.AgentID,
			&i.Slug,
			&i.Name,
			&i.Description,
			&i.LlmHint,
			&i.Access,
			&i.AuthMode,
			&i.AuthUrl,
			&i.TokenUrl,
			&i.BaseUrl,
			&i.Scopes,
			&i.AuthInjection,
			&i.TestPath,
			&i.SetupInstructions,
			&i.Config,
			&i.ClientID,
			&i.ClientSecret,
			&i.AccessTokenRef,
			&i.RefreshToken,
			&i.TokenExpiresAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listConnectionsWithStatus = `-- name: ListConnectionsWithStatus :many
SELECT id, agent_id, slug, name, description, auth_mode, auth_url, base_url,
       scopes, setup_instructions, test_path,
       (access_token_ref != '') AS authorized,
       (client_id != '') AS has_oauth_app,
       token_expires_at
FROM connections WHERE agent_id = $1 ORDER BY slug
`

type ListConnectionsWithStatusRow struct {
	ID                pgtype.UUID        `json:"id"`
	AgentID           pgtype.UUID        `json:"agent_id"`
	Slug              string             `json:"slug"`
	Name              string             `json:"name"`
	Description       string             `json:"description"`
	AuthMode          string             `json:"auth_mode"`
	AuthUrl           string             `json:"auth_url"`
	BaseUrl           string             `json:"base_url"`
	Scopes            string             `json:"scopes"`
	SetupInstructions string             `json:"setup_instructions"`
	TestPath          string             `json:"test_path"`
	Authorized        bool               `json:"authorized"`
	HasOauthApp       bool               `json:"has_oauth_app"`
	TokenExpiresAt    pgtype.Timestamptz `json:"token_expires_at"`
}

// For GET /api/v1/agents/{agentID}/connections
func (q *Queries) ListConnectionsWithStatus(ctx context.Context, agentID pgtype.UUID) ([]ListConnectionsWithStatusRow, error) {
	rows, err := q.db.Query(ctx, listConnectionsWithStatus, agentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListConnectionsWithStatusRow{}
	for rows.Next() {
		var i ListConnectionsWithStatusRow
		if err := rows.Scan(
			&i.ID,
			&i.AgentID,
			&i.Slug,
			&i.Name,
			&i.Description,
			&i.AuthMode,
			&i.AuthUrl,
			&i.BaseUrl,
			&i.Scopes,
			&i.SetupInstructions,
			&i.TestPath,
			&i.Authorized,
			&i.HasOauthApp,
			&i.TokenExpiresAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listExpiringConnections = `-- name: ListExpiringConnections :many
SELECT c.id, c.agent_id, c.slug, c.name, c.auth_mode, c.token_url,
       c.client_id, c.client_secret, c.access_token_ref, c.refresh_token,
       c.token_expires_at, c.scopes,
       a.slug AS agent_slug
FROM connections c
JOIN agents a ON c.agent_id = a.id
WHERE c.auth_mode = 'oauth'
  AND c.access_token_ref != ''
  AND c.refresh_token != ''
  AND c.token_expires_at IS NOT NULL
  AND c.token_expires_at < $1
  AND a.status = 'active'
`

type ListExpiringConnectionsRow struct {
	ID             pgtype.UUID        `json:"id"`
	AgentID        pgtype.UUID        `json:"agent_id"`
	Slug           string             `json:"slug"`
	Name           string             `json:"name"`
	AuthMode       string             `json:"auth_mode"`
	TokenUrl       string             `json:"token_url"`
	ClientID       string             `json:"client_id"`
	ClientSecret   string             `json:"client_secret"`
	AccessTokenRef string             `json:"access_token_ref"`
	RefreshToken   string             `json:"refresh_token"`
	TokenExpiresAt pgtype.Timestamptz `json:"token_expires_at"`
	Scopes         string             `json:"scopes"`
	AgentSlug      string             `json:"agent_slug"`
}

// For refresh job: find tokens expiring within buffer window
func (q *Queries) ListExpiringConnections(ctx context.Context, expiryThreshold pgtype.Timestamptz) ([]ListExpiringConnectionsRow, error) {
	rows, err := q.db.Query(ctx, listExpiringConnections, expiryThreshold)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListExpiringConnectionsRow{}
	for rows.Next() {
		var i ListExpiringConnectionsRow
		if err := rows.Scan(
			&i.ID,
			&i.AgentID,
			&i.Slug,
			&i.Name,
			&i.AuthMode,
			&i.TokenUrl,
			&i.ClientID,
			&i.ClientSecret,
			&i.AccessTokenRef,
			&i.RefreshToken,
			&i.TokenExpiresAt,
			&i.Scopes,
			&i.AgentSlug,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateConnectionCredentials = `-- name: UpdateConnectionCredentials :exec
UPDATE connections SET
    access_token_ref = $1,
    token_expires_at = $2,
    refresh_token = $3,
    updated_at = now()
WHERE agent_id = $4 AND slug = $5
`

type UpdateConnectionCredentialsParams struct {
	AccessTokenRef string             `json:"access_token_ref"`
	TokenExpiresAt pgtype.Timestamptz `json:"token_expires_at"`
	RefreshToken   string             `json:"refresh_token"`
	AgentID        pgtype.UUID        `json:"agent_id"`
	Slug           string             `json:"slug"`
}

func (q *Queries) UpdateConnectionCredentials(ctx context.Context, arg UpdateConnectionCredentialsParams) error {
	_, err := q.db.Exec(ctx, updateConnectionCredentials,
		arg.AccessTokenRef,
		arg.TokenExpiresAt,
		arg.RefreshToken,
		arg.AgentID,
		arg.Slug,
	)
	return err
}

const updateConnectionOAuthApp = `-- name: UpdateConnectionOAuthApp :exec
UPDATE connections SET
    client_id = $1,
    client_secret = $2,
    updated_at = now()
WHERE agent_id = $3 AND slug = $4
`

type UpdateConnectionOAuthAppParams struct {
	ClientID     string      `json:"client_id"`
	ClientSecret string      `json:"client_secret"`
	AgentID      pgtype.UUID `json:"agent_id"`
	Slug         string      `json:"slug"`
}

// User enters OAuth client_id + client_secret
func (q *Queries) UpdateConnectionOAuthApp(ctx context.Context, arg UpdateConnectionOAuthAppParams) error {
	_, err := q.db.Exec(ctx, updateConnectionOAuthApp,
		arg.ClientID,
		arg.ClientSecret,
		arg.AgentID,
		arg.Slug,
	)
	return err
}

const upsertConnection = `-- name: UpsertConnection :one
INSERT INTO connections (agent_id, slug, name, description, llm_hint, auth_mode, auth_url, token_url, base_url, scopes, auth_injection, setup_instructions, test_path, config, access, client_id, client_secret, access_token_ref, refresh_token)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, '', '', '', '')
ON CONFLICT (agent_id, slug) DO UPDATE SET
    name = EXCLUDED.name,
    description = EXCLUDED.description,
    llm_hint = EXCLUDED.llm_hint,
    auth_mode = EXCLUDED.auth_mode,
    auth_url = EXCLUDED.auth_url,
    token_url = EXCLUDED.token_url,
    base_url = EXCLUDED.base_url,
    scopes = EXCLUDED.scopes,
    auth_injection = EXCLUDED.auth_injection,
    setup_instructions = EXCLUDED.setup_instructions,
    test_path = EXCLUDED.test_path,
    config = EXCLUDED.config,
    access = EXCLUDED.access,
    access_token_ref = CASE WHEN connections.scopes != EXCLUDED.scopes THEN '' ELSE connections.access_token_ref END,
    refresh_token = CASE WHEN connections.scopes != EXCLUDED.scopes THEN '' ELSE connections.refresh_token END,
    token_expires_at = CASE WHEN connections.scopes != EXCLUDED.scopes THEN NULL ELSE connections.token_expires_at END,
    updated_at = now()
RETURNING id, agent_id, slug, name, description, llm_hint, access, auth_mode, auth_url, token_url, base_url, scopes, auth_injection, test_path, setup_instructions, config, client_id, client_secret, access_token_ref, refresh_token, token_expires_at, created_at, updated_at
`

type UpsertConnectionParams struct {
	AgentID           pgtype.UUID `json:"agent_id"`
	Slug              string      `json:"slug"`
	Name              string      `json:"name"`
	Description       string      `json:"description"`
	LlmHint           string      `json:"llm_hint"`
	AuthMode          string      `json:"auth_mode"`
	AuthUrl           string      `json:"auth_url"`
	TokenUrl          string      `json:"token_url"`
	BaseUrl           string      `json:"base_url"`
	Scopes            string      `json:"scopes"`
	AuthInjection     []byte      `json:"auth_injection"`
	SetupInstructions string      `json:"setup_instructions"`
	TestPath          string      `json:"test_path"`
	Config            []byte      `json:"config"`
	Access            string      `json:"access"`
}

// When scopes change, clear access_token_ref so the user must re-authorize with the new scopes.
// Credential fields (client_id, client_secret, access_token_ref, refresh_token)
// are passed explicitly as ” on first insert; the ON CONFLICT clause
// preserves existing access_token_ref unless scopes changed.
func (q *Queries) UpsertConnection(ctx context.Context, arg UpsertConnectionParams) (Connection, error) {
	row := q.db.QueryRow(ctx, upsertConnection,
		arg.AgentID,
		arg.Slug,
		arg.Name,
		arg.Description,
		arg.LlmHint,
		arg.AuthMode,
		arg.AuthUrl,
		arg.TokenUrl,
		arg.BaseUrl,
		arg.Scopes,
		arg.AuthInjection,
		arg.SetupInstructions,
		arg.TestPath,
		arg.Config,
		arg.Access,
	)
	var i Connection
	err := row.Scan(
		&i.ID,
		&i.AgentID,
		&i.Slug,
		&i.Name,
		&i.Description,
		&i.LlmHint,
		&i.Access,
		&i.AuthMode,
		&i.AuthUrl,
		&i.TokenUrl,
		&i.BaseUrl,
		&i.Scopes,
		&i.AuthInjection,
		&i.TestPath,
		&i.SetupInstructions,
		&i.Config,
		&i.ClientID,
		&i.ClientSecret,
		&i.AccessTokenRef,
		&i.RefreshToken,
		&i.TokenExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
