// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: directories.sql

package dbq

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteDirectoriesByAgentExcept = `-- name: DeleteDirectoriesByAgentExcept :exec
DELETE FROM agent_directories WHERE agent_id = $1 AND path != ALL($2::text[])
`

type DeleteDirectoriesByAgentExceptParams struct {
	AgentID pgtype.UUID `json:"agent_id"`
	Paths   []string    `json:"paths"`
}

func (q *Queries) DeleteDirectoriesByAgentExcept(ctx context.Context, arg DeleteDirectoriesByAgentExceptParams) error {
	_, err := q.db.Exec(ctx, deleteDirectoriesByAgentExcept, arg.AgentID, arg.Paths)
	return err
}

const getDirectoryByPath = `-- name: GetDirectoryByPath :one
SELECT id, agent_id, path, read_access, write_access, list_access, description, created_at, updated_at FROM agent_directories
WHERE agent_id = $1 AND $2::text LIKE path || '%'
ORDER BY length(path) DESC LIMIT 1
`

type GetDirectoryByPathParams struct {
	AgentID pgtype.UUID `json:"agent_id"`
	Path    string      `json:"path"`
}

// Longest-prefix match for nested registrations. Returns the most-specific
// directory whose path is a prefix of the requested path.
func (q *Queries) GetDirectoryByPath(ctx context.Context, arg GetDirectoryByPathParams) (AgentDirectory, error) {
	row := q.db.QueryRow(ctx, getDirectoryByPath, arg.AgentID, arg.Path)
	var i AgentDirectory
	err := row.Scan(
		&i.ID,
		&i.AgentID,
		&i.Path,
		&i.ReadAccess,
		&i.WriteAccess,
		&i.ListAccess,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listDirectoriesByAgent = `-- name: ListDirectoriesByAgent :many
SELECT id, agent_id, path, read_access, write_access, list_access, description, created_at, updated_at FROM agent_directories WHERE agent_id = $1 ORDER BY path
`

func (q *Queries) ListDirectoriesByAgent(ctx context.Context, agentID pgtype.UUID) ([]AgentDirectory, error) {
	rows, err := q.db.Query(ctx, listDirectoriesByAgent, agentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AgentDirectory{}
	for rows.Next() {
		var i AgentDirectory
		if err := rows.Scan(
			&i.ID,
			&i.AgentID,
			&i.Path,
			&i.ReadAccess,
			&i.WriteAccess,
			&i.ListAccess,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertDirectory = `-- name: UpsertDirectory :exec
INSERT INTO agent_directories (agent_id, path, read_access, write_access, list_access, description)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (agent_id, path) DO UPDATE SET
    read_access = EXCLUDED.read_access,
    write_access = EXCLUDED.write_access,
    list_access = EXCLUDED.list_access,
    description = EXCLUDED.description,
    updated_at = now()
`

type UpsertDirectoryParams struct {
	AgentID     pgtype.UUID `json:"agent_id"`
	Path        string      `json:"path"`
	ReadAccess  string      `json:"read_access"`
	WriteAccess string      `json:"write_access"`
	ListAccess  string      `json:"list_access"`
	Description string      `json:"description"`
}

func (q *Queries) UpsertDirectory(ctx context.Context, arg UpsertDirectoryParams) error {
	_, err := q.db.Exec(ctx, upsertDirectory,
		arg.AgentID,
		arg.Path,
		arg.ReadAccess,
		arg.WriteAccess,
		arg.ListAccess,
		arg.Description,
	)
	return err
}
