// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: git_credentials.sql

package dbq

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createGitCredential = `-- name: CreateGitCredential :one
INSERT INTO git_credentials (id, user_id, type, name, token_ref, github_install_id)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, user_id, type, name, token_ref, github_install_id, created_at, last_used_at
`

type CreateGitCredentialParams struct {
	ID              pgtype.UUID `json:"id"`
	UserID          pgtype.UUID `json:"user_id"`
	Type            string      `json:"type"`
	Name            string      `json:"name"`
	TokenRef        string      `json:"token_ref"`
	GithubInstallID string      `json:"github_install_id"`
}

// id is caller-supplied (uuid.New) so token_ref ciphertext can be
// bound to it via AAD before INSERT — same shape as CreateProvider.
func (q *Queries) CreateGitCredential(ctx context.Context, arg CreateGitCredentialParams) (GitCredential, error) {
	row := q.db.QueryRow(ctx, createGitCredential,
		arg.ID,
		arg.UserID,
		arg.Type,
		arg.Name,
		arg.TokenRef,
		arg.GithubInstallID,
	)
	var i GitCredential
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Type,
		&i.Name,
		&i.TokenRef,
		&i.GithubInstallID,
		&i.CreatedAt,
		&i.LastUsedAt,
	)
	return i, err
}

const deleteGitCredential = `-- name: DeleteGitCredential :exec
DELETE FROM git_credentials WHERE id = $1 AND user_id = $2
`

type DeleteGitCredentialParams struct {
	ID     pgtype.UUID `json:"id"`
	UserID pgtype.UUID `json:"user_id"`
}

// Owner-scoped: a user can only delete their own credentials.
func (q *Queries) DeleteGitCredential(ctx context.Context, arg DeleteGitCredentialParams) error {
	_, err := q.db.Exec(ctx, deleteGitCredential, arg.ID, arg.UserID)
	return err
}

const getGitCredential = `-- name: GetGitCredential :one
SELECT id, user_id, type, name, token_ref, github_install_id, created_at, last_used_at FROM git_credentials WHERE id = $1
`

// Runtime resolution path: caller fetches the encrypted token_ref to
// decrypt and use against the remote. NOT scoped by user_id — the
// caller (e.g. the codegen push) must enforce permission via the
// owning agent's user_id matching.
func (q *Queries) GetGitCredential(ctx context.Context, id pgtype.UUID) (GitCredential, error) {
	row := q.db.QueryRow(ctx, getGitCredential, id)
	var i GitCredential
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Type,
		&i.Name,
		&i.TokenRef,
		&i.GithubInstallID,
		&i.CreatedAt,
		&i.LastUsedAt,
	)
	return i, err
}

const listGitCredentialsByUser = `-- name: ListGitCredentialsByUser :many
SELECT id, user_id, type, name, github_install_id, created_at, last_used_at
FROM git_credentials WHERE user_id = $1 ORDER BY name
`

type ListGitCredentialsByUserRow struct {
	ID              pgtype.UUID        `json:"id"`
	UserID          pgtype.UUID        `json:"user_id"`
	Type            string             `json:"type"`
	Name            string             `json:"name"`
	GithubInstallID string             `json:"github_install_id"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	LastUsedAt      pgtype.Timestamptz `json:"last_used_at"`
}

// Omits token_ref by design — listing should never need to read the
// encrypted blob. Defense in depth against accidental token leaks.
func (q *Queries) ListGitCredentialsByUser(ctx context.Context, userID pgtype.UUID) ([]ListGitCredentialsByUserRow, error) {
	rows, err := q.db.Query(ctx, listGitCredentialsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListGitCredentialsByUserRow{}
	for rows.Next() {
		var i ListGitCredentialsByUserRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Type,
			&i.Name,
			&i.GithubInstallID,
			&i.CreatedAt,
			&i.LastUsedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const touchGitCredentialUsage = `-- name: TouchGitCredentialUsage :exec
UPDATE git_credentials SET last_used_at = now() WHERE id = $1
`

// Stamped on successful clone/push/refresh — surfaces "is this credential
// actually being used?" without needing audit-log scrubbing.
func (q *Queries) TouchGitCredentialUsage(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, touchGitCredentialUsage, id)
	return err
}
