// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: mcp_servers.sql

package dbq

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const clearMCPServerCredentials = `-- name: ClearMCPServerCredentials :exec
UPDATE agent_mcp_servers SET
    credentials = '',
    refresh_token = '',
    token_expires_at = NULL,
    updated_at = now()
WHERE agent_id = $1 AND slug = $2
`

type ClearMCPServerCredentialsParams struct {
	AgentID pgtype.UUID `json:"agent_id"`
	Slug    string      `json:"slug"`
}

func (q *Queries) ClearMCPServerCredentials(ctx context.Context, arg ClearMCPServerCredentialsParams) error {
	_, err := q.db.Exec(ctx, clearMCPServerCredentials, arg.AgentID, arg.Slug)
	return err
}

const clearMCPServerOAuthApp = `-- name: ClearMCPServerOAuthApp :exec
UPDATE agent_mcp_servers SET
    client_id = '',
    client_secret = '',
    credentials = '',
    refresh_token = '',
    token_expires_at = NULL,
    updated_at = now()
WHERE agent_id = $1 AND slug = $2
`

type ClearMCPServerOAuthAppParams struct {
	AgentID pgtype.UUID `json:"agent_id"`
	Slug    string      `json:"slug"`
}

// Wipe the OAuth app config (client_id/secret) AND the credentials that
// belong to it. Used by "Re-register client" (oauth_discovery, forces a
// fresh DCR on next authorize) and "Edit OAuth app" (oauth, paste new
// credentials). Existing tokens MUST go too — they're tied to the old
// client_id at the OAuth provider and would 401 the moment they're used.
func (q *Queries) ClearMCPServerOAuthApp(ctx context.Context, arg ClearMCPServerOAuthAppParams) error {
	_, err := q.db.Exec(ctx, clearMCPServerOAuthApp, arg.AgentID, arg.Slug)
	return err
}

const deleteMCPServersByAgentExcept = `-- name: DeleteMCPServersByAgentExcept :exec
DELETE FROM agent_mcp_servers
WHERE agent_id = $1 AND slug != ALL($2::text[])
`

type DeleteMCPServersByAgentExceptParams struct {
	AgentID pgtype.UUID `json:"agent_id"`
	Slugs   []string    `json:"slugs"`
}

// Delete MCP servers not in the current sync.
func (q *Queries) DeleteMCPServersByAgentExcept(ctx context.Context, arg DeleteMCPServersByAgentExceptParams) error {
	_, err := q.db.Exec(ctx, deleteMCPServersByAgentExcept, arg.AgentID, arg.Slugs)
	return err
}

const getMCPServerBySlug = `-- name: GetMCPServerBySlug :one
SELECT id, agent_id, slug, name, access, url, auth_mode, auth_url, token_url, registration_endpoint, scopes, tool_schemas, client_id, client_secret, credentials, refresh_token, token_expires_at, last_synced_at, created_at, updated_at FROM agent_mcp_servers WHERE agent_id = $1 AND slug = $2
`

type GetMCPServerBySlugParams struct {
	AgentID pgtype.UUID `json:"agent_id"`
	Slug    string      `json:"slug"`
}

func (q *Queries) GetMCPServerBySlug(ctx context.Context, arg GetMCPServerBySlugParams) (AgentMcpServer, error) {
	row := q.db.QueryRow(ctx, getMCPServerBySlug, arg.AgentID, arg.Slug)
	var i AgentMcpServer
	err := row.Scan(
		&i.ID,
		&i.AgentID,
		&i.Slug,
		&i.Name,
		&i.Access,
		&i.Url,
		&i.AuthMode,
		&i.AuthUrl,
		&i.TokenUrl,
		&i.RegistrationEndpoint,
		&i.Scopes,
		&i.ToolSchemas,
		&i.ClientID,
		&i.ClientSecret,
		&i.Credentials,
		&i.RefreshToken,
		&i.TokenExpiresAt,
		&i.LastSyncedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getMCPServerForOAuth = `-- name: GetMCPServerForOAuth :one
SELECT id, agent_id, slug, name, url, auth_mode, auth_url, token_url,
       registration_endpoint, scopes, client_id, client_secret
FROM agent_mcp_servers WHERE agent_id = $1 AND slug = $2
`

type GetMCPServerForOAuthParams struct {
	AgentID pgtype.UUID `json:"agent_id"`
	Slug    string      `json:"slug"`
}

type GetMCPServerForOAuthRow struct {
	ID                   pgtype.UUID `json:"id"`
	AgentID              pgtype.UUID `json:"agent_id"`
	Slug                 string      `json:"slug"`
	Name                 string      `json:"name"`
	Url                  string      `json:"url"`
	AuthMode             string      `json:"auth_mode"`
	AuthUrl              string      `json:"auth_url"`
	TokenUrl             string      `json:"token_url"`
	RegistrationEndpoint string      `json:"registration_endpoint"`
	Scopes               string      `json:"scopes"`
	ClientID             string      `json:"client_id"`
	ClientSecret         string      `json:"client_secret"`
}

func (q *Queries) GetMCPServerForOAuth(ctx context.Context, arg GetMCPServerForOAuthParams) (GetMCPServerForOAuthRow, error) {
	row := q.db.QueryRow(ctx, getMCPServerForOAuth, arg.AgentID, arg.Slug)
	var i GetMCPServerForOAuthRow
	err := row.Scan(
		&i.ID,
		&i.AgentID,
		&i.Slug,
		&i.Name,
		&i.Url,
		&i.AuthMode,
		&i.AuthUrl,
		&i.TokenUrl,
		&i.RegistrationEndpoint,
		&i.Scopes,
		&i.ClientID,
		&i.ClientSecret,
	)
	return i, err
}

const hasDirtyMCPServers = `-- name: HasDirtyMCPServers :one
SELECT EXISTS(
    SELECT 1 FROM agent_mcp_servers
    WHERE agent_id = $1
      AND (last_synced_at IS NULL OR updated_at > last_synced_at)
) AS dirty
`

// Check if any MCP server has been updated since last sync (for dirty flag).
func (q *Queries) HasDirtyMCPServers(ctx context.Context, agentID pgtype.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, hasDirtyMCPServers, agentID)
	var dirty bool
	err := row.Scan(&dirty)
	return dirty, err
}

const listExpiringMCPServers = `-- name: ListExpiringMCPServers :many
SELECT m.id, m.agent_id, m.slug, m.name, m.auth_mode, m.token_url,
       m.client_id, m.client_secret, m.credentials, m.refresh_token,
       m.token_expires_at, m.scopes,
       a.slug AS agent_slug
FROM agent_mcp_servers m
JOIN agents a ON m.agent_id = a.id
WHERE m.auth_mode IN ('oauth', 'oauth_discovery')
  AND m.credentials != ''
  AND m.refresh_token != ''
  AND m.token_expires_at IS NOT NULL
  AND m.token_expires_at < $1
  AND a.status = 'active'
`

type ListExpiringMCPServersRow struct {
	ID             pgtype.UUID        `json:"id"`
	AgentID        pgtype.UUID        `json:"agent_id"`
	Slug           string             `json:"slug"`
	Name           string             `json:"name"`
	AuthMode       string             `json:"auth_mode"`
	TokenUrl       string             `json:"token_url"`
	ClientID       string             `json:"client_id"`
	ClientSecret   string             `json:"client_secret"`
	Credentials    string             `json:"credentials"`
	RefreshToken   string             `json:"refresh_token"`
	TokenExpiresAt pgtype.Timestamptz `json:"token_expires_at"`
	Scopes         string             `json:"scopes"`
	AgentSlug      string             `json:"agent_slug"`
}

// For refresh job: find tokens expiring within buffer window.
func (q *Queries) ListExpiringMCPServers(ctx context.Context, expiryThreshold pgtype.Timestamptz) ([]ListExpiringMCPServersRow, error) {
	rows, err := q.db.Query(ctx, listExpiringMCPServers, expiryThreshold)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListExpiringMCPServersRow{}
	for rows.Next() {
		var i ListExpiringMCPServersRow
		if err := rows.Scan(
			&i.ID,
			&i.AgentID,
			&i.Slug,
			&i.Name,
			&i.AuthMode,
			&i.TokenUrl,
			&i.ClientID,
			&i.ClientSecret,
			&i.Credentials,
			&i.RefreshToken,
			&i.TokenExpiresAt,
			&i.Scopes,
			&i.AgentSlug,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMCPServersByAgent = `-- name: ListMCPServersByAgent :many
SELECT id, agent_id, slug, name, access, url, auth_mode, auth_url, token_url, registration_endpoint, scopes, tool_schemas, client_id, client_secret, credentials, refresh_token, token_expires_at, last_synced_at, created_at, updated_at FROM agent_mcp_servers WHERE agent_id = $1 ORDER BY slug
`

func (q *Queries) ListMCPServersByAgent(ctx context.Context, agentID pgtype.UUID) ([]AgentMcpServer, error) {
	rows, err := q.db.Query(ctx, listMCPServersByAgent, agentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AgentMcpServer{}
	for rows.Next() {
		var i AgentMcpServer
		if err := rows.Scan(
			&i.ID,
			&i.AgentID,
			&i.Slug,
			&i.Name,
			&i.Access,
			&i.Url,
			&i.AuthMode,
			&i.AuthUrl,
			&i.TokenUrl,
			&i.RegistrationEndpoint,
			&i.Scopes,
			&i.ToolSchemas,
			&i.ClientID,
			&i.ClientSecret,
			&i.Credentials,
			&i.RefreshToken,
			&i.TokenExpiresAt,
			&i.LastSyncedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMCPServersWithStatus = `-- name: ListMCPServersWithStatus :many
SELECT id, agent_id, slug, name, url, auth_mode, auth_url,
       (credentials != '') AS authorized,
       (client_id != '') AS has_oauth_app,
       tool_schemas,
       token_expires_at,
       last_synced_at
FROM agent_mcp_servers WHERE agent_id = $1 ORDER BY slug
`

type ListMCPServersWithStatusRow struct {
	ID             pgtype.UUID        `json:"id"`
	AgentID        pgtype.UUID        `json:"agent_id"`
	Slug           string             `json:"slug"`
	Name           string             `json:"name"`
	Url            string             `json:"url"`
	AuthMode       string             `json:"auth_mode"`
	AuthUrl        string             `json:"auth_url"`
	Authorized     bool               `json:"authorized"`
	HasOauthApp    bool               `json:"has_oauth_app"`
	ToolSchemas    []byte             `json:"tool_schemas"`
	TokenExpiresAt pgtype.Timestamptz `json:"token_expires_at"`
	LastSyncedAt   pgtype.Timestamptz `json:"last_synced_at"`
}

// For frontend: list with auth status
func (q *Queries) ListMCPServersWithStatus(ctx context.Context, agentID pgtype.UUID) ([]ListMCPServersWithStatusRow, error) {
	rows, err := q.db.Query(ctx, listMCPServersWithStatus, agentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListMCPServersWithStatusRow{}
	for rows.Next() {
		var i ListMCPServersWithStatusRow
		if err := rows.Scan(
			&i.ID,
			&i.AgentID,
			&i.Slug,
			&i.Name,
			&i.Url,
			&i.AuthMode,
			&i.AuthUrl,
			&i.Authorized,
			&i.HasOauthApp,
			&i.ToolSchemas,
			&i.TokenExpiresAt,
			&i.LastSyncedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateMCPServerCredentials = `-- name: UpdateMCPServerCredentials :exec
UPDATE agent_mcp_servers SET
    credentials = $1,
    token_expires_at = $2,
    refresh_token = $3,
    updated_at = now()
WHERE agent_id = $4 AND slug = $5
`

type UpdateMCPServerCredentialsParams struct {
	Credentials    string             `json:"credentials"`
	TokenExpiresAt pgtype.Timestamptz `json:"token_expires_at"`
	RefreshToken   string             `json:"refresh_token"`
	AgentID        pgtype.UUID        `json:"agent_id"`
	Slug           string             `json:"slug"`
}

func (q *Queries) UpdateMCPServerCredentials(ctx context.Context, arg UpdateMCPServerCredentialsParams) error {
	_, err := q.db.Exec(ctx, updateMCPServerCredentials,
		arg.Credentials,
		arg.TokenExpiresAt,
		arg.RefreshToken,
		arg.AgentID,
		arg.Slug,
	)
	return err
}

const updateMCPServerDiscovery = `-- name: UpdateMCPServerDiscovery :exec
UPDATE agent_mcp_servers SET
    auth_url = $1,
    token_url = $2,
    registration_endpoint = $3,
    updated_at = now()
WHERE agent_id = $4 AND slug = $5
`

type UpdateMCPServerDiscoveryParams struct {
	AuthUrl              string      `json:"auth_url"`
	TokenUrl             string      `json:"token_url"`
	RegistrationEndpoint string      `json:"registration_endpoint"`
	AgentID              pgtype.UUID `json:"agent_id"`
	Slug                 string      `json:"slug"`
}

// Lazy re-discovery: refresh auth_url / token_url / registration_endpoint
// after a fresh RFC 8414 fetch. Only used by oauth_discovery's MCPOAuthStart
// when registration_endpoint is missing (the only path forward for DCR).
// Does NOT touch credentials — re-discovery never invalidates auth state by
// itself; callers chain it with DCR + UpdateMCPServerOAuthApp when needed.
func (q *Queries) UpdateMCPServerDiscovery(ctx context.Context, arg UpdateMCPServerDiscoveryParams) error {
	_, err := q.db.Exec(ctx, updateMCPServerDiscovery,
		arg.AuthUrl,
		arg.TokenUrl,
		arg.RegistrationEndpoint,
		arg.AgentID,
		arg.Slug,
	)
	return err
}

const updateMCPServerOAuthApp = `-- name: UpdateMCPServerOAuthApp :exec
UPDATE agent_mcp_servers SET
    client_id = $1,
    client_secret = $2,
    updated_at = now()
WHERE agent_id = $3 AND slug = $4
`

type UpdateMCPServerOAuthAppParams struct {
	ClientID     string      `json:"client_id"`
	ClientSecret string      `json:"client_secret"`
	AgentID      pgtype.UUID `json:"agent_id"`
	Slug         string      `json:"slug"`
}

func (q *Queries) UpdateMCPServerOAuthApp(ctx context.Context, arg UpdateMCPServerOAuthAppParams) error {
	_, err := q.db.Exec(ctx, updateMCPServerOAuthApp,
		arg.ClientID,
		arg.ClientSecret,
		arg.AgentID,
		arg.Slug,
	)
	return err
}

const updateMCPServerToolSchemas = `-- name: UpdateMCPServerToolSchemas :exec
UPDATE agent_mcp_servers SET
    tool_schemas = $1,
    last_synced_at = now(),
    updated_at = now()
WHERE agent_id = $2 AND slug = $3
`

type UpdateMCPServerToolSchemasParams struct {
	ToolSchemas []byte      `json:"tool_schemas"`
	AgentID     pgtype.UUID `json:"agent_id"`
	Slug        string      `json:"slug"`
}

func (q *Queries) UpdateMCPServerToolSchemas(ctx context.Context, arg UpdateMCPServerToolSchemasParams) error {
	_, err := q.db.Exec(ctx, updateMCPServerToolSchemas, arg.ToolSchemas, arg.AgentID, arg.Slug)
	return err
}

const upsertMCPServer = `-- name: UpsertMCPServer :one
INSERT INTO agent_mcp_servers (agent_id, slug, name, url, auth_mode, auth_url, token_url, registration_endpoint, scopes, access, tool_schemas, client_id, client_secret, credentials, refresh_token)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, '[]'::jsonb, '', '', '', '')
ON CONFLICT (agent_id, slug) DO UPDATE SET
    name = EXCLUDED.name,
    url = EXCLUDED.url,
    auth_mode = EXCLUDED.auth_mode,
    -- Preserve discovered URLs when a fresh sync turns up empty (transient
    -- discovery failure shouldn't wipe state we already proved good by
    -- successfully exchanging tokens against it).
    auth_url = CASE
        WHEN EXCLUDED.auth_url != '' THEN EXCLUDED.auth_url
        ELSE agent_mcp_servers.auth_url END,
    token_url = CASE
        WHEN EXCLUDED.token_url != '' THEN EXCLUDED.token_url
        ELSE agent_mcp_servers.token_url END,
    registration_endpoint = CASE
        WHEN EXCLUDED.registration_endpoint != '' THEN EXCLUDED.registration_endpoint
        ELSE agent_mcp_servers.registration_endpoint END,
    scopes = EXCLUDED.scopes,
    access = EXCLUDED.access,
    credentials = CASE
        WHEN agent_mcp_servers.url != EXCLUDED.url OR agent_mcp_servers.scopes != EXCLUDED.scopes
        THEN '' ELSE agent_mcp_servers.credentials END,
    refresh_token = CASE
        WHEN agent_mcp_servers.url != EXCLUDED.url OR agent_mcp_servers.scopes != EXCLUDED.scopes
        THEN '' ELSE agent_mcp_servers.refresh_token END,
    token_expires_at = CASE
        WHEN agent_mcp_servers.url != EXCLUDED.url OR agent_mcp_servers.scopes != EXCLUDED.scopes
        THEN NULL ELSE agent_mcp_servers.token_expires_at END,
    updated_at = now()
RETURNING id, agent_id, slug, name, access, url, auth_mode, auth_url, token_url, registration_endpoint, scopes, tool_schemas, client_id, client_secret, credentials, refresh_token, token_expires_at, last_synced_at, created_at, updated_at
`

type UpsertMCPServerParams struct {
	AgentID              pgtype.UUID `json:"agent_id"`
	Slug                 string      `json:"slug"`
	Name                 string      `json:"name"`
	Url                  string      `json:"url"`
	AuthMode             string      `json:"auth_mode"`
	AuthUrl              string      `json:"auth_url"`
	TokenUrl             string      `json:"token_url"`
	RegistrationEndpoint string      `json:"registration_endpoint"`
	Scopes               string      `json:"scopes"`
	Access               string      `json:"access"`
}

// When url or scopes change, clear credentials so the user must re-authorize.
// Discovery + credential fields are passed explicitly as empty on first
// insert; ON CONFLICT preserves existing credentials unless invalidated.
// registration_endpoint is taken from EXCLUDED only when newly populated —
// a fresh discovery run that turned up empty doesn't blow away a previously
// discovered endpoint.
func (q *Queries) UpsertMCPServer(ctx context.Context, arg UpsertMCPServerParams) (AgentMcpServer, error) {
	row := q.db.QueryRow(ctx, upsertMCPServer,
		arg.AgentID,
		arg.Slug,
		arg.Name,
		arg.Url,
		arg.AuthMode,
		arg.AuthUrl,
		arg.TokenUrl,
		arg.RegistrationEndpoint,
		arg.Scopes,
		arg.Access,
	)
	var i AgentMcpServer
	err := row.Scan(
		&i.ID,
		&i.AgentID,
		&i.Slug,
		&i.Name,
		&i.Access,
		&i.Url,
		&i.AuthMode,
		&i.AuthUrl,
		&i.TokenUrl,
		&i.RegistrationEndpoint,
		&i.Scopes,
		&i.ToolSchemas,
		&i.ClientID,
		&i.ClientSecret,
		&i.Credentials,
		&i.RefreshToken,
		&i.TokenExpiresAt,
		&i.LastSyncedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
