// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: oauth_clients.sql

package dbq

import (
	"context"
)

const createOAuthClient = `-- name: CreateOAuthClient :one
INSERT INTO oauth_clients (
    client_id, client_name, redirect_uris, grant_types, response_types,
    token_endpoint_auth_method, scope
)
VALUES (
    $1, $2, $3, $4, $5,
    $6, $7
)
RETURNING client_id, client_name, redirect_uris, grant_types, response_types, token_endpoint_auth_method, scope, created_at, last_used_at
`

type CreateOAuthClientParams struct {
	ClientID                string   `json:"client_id"`
	ClientName              string   `json:"client_name"`
	RedirectUris            []string `json:"redirect_uris"`
	GrantTypes              []string `json:"grant_types"`
	ResponseTypes           []string `json:"response_types"`
	TokenEndpointAuthMethod string   `json:"token_endpoint_auth_method"`
	Scope                   string   `json:"scope"`
}

func (q *Queries) CreateOAuthClient(ctx context.Context, arg CreateOAuthClientParams) (OauthClient, error) {
	row := q.db.QueryRow(ctx, createOAuthClient,
		arg.ClientID,
		arg.ClientName,
		arg.RedirectUris,
		arg.GrantTypes,
		arg.ResponseTypes,
		arg.TokenEndpointAuthMethod,
		arg.Scope,
	)
	var i OauthClient
	err := row.Scan(
		&i.ClientID,
		&i.ClientName,
		&i.RedirectUris,
		&i.GrantTypes,
		&i.ResponseTypes,
		&i.TokenEndpointAuthMethod,
		&i.Scope,
		&i.CreatedAt,
		&i.LastUsedAt,
	)
	return i, err
}

const getOAuthClient = `-- name: GetOAuthClient :one
SELECT client_id, client_name, redirect_uris, grant_types, response_types, token_endpoint_auth_method, scope, created_at, last_used_at FROM oauth_clients WHERE client_id = $1
`

func (q *Queries) GetOAuthClient(ctx context.Context, clientID string) (OauthClient, error) {
	row := q.db.QueryRow(ctx, getOAuthClient, clientID)
	var i OauthClient
	err := row.Scan(
		&i.ClientID,
		&i.ClientName,
		&i.RedirectUris,
		&i.GrantTypes,
		&i.ResponseTypes,
		&i.TokenEndpointAuthMethod,
		&i.Scope,
		&i.CreatedAt,
		&i.LastUsedAt,
	)
	return i, err
}

const touchOAuthClient = `-- name: TouchOAuthClient :exec
UPDATE oauth_clients SET last_used_at = now() WHERE client_id = $1
`

// Bump last_used_at on a successful /token exchange. Used by the GC to
// prune stale, never-used DCR registrations (currently informational
// only — no auto-prune in v1).
func (q *Queries) TouchOAuthClient(ctx context.Context, clientID string) error {
	_, err := q.db.Exec(ctx, touchOAuthClient, clientID)
	return err
}
