// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: oauth_grants.sql

package dbq

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const cleanupExpiredGrants = `-- name: CleanupExpiredGrants :execrows
DELETE FROM oauth_grants
WHERE (expires_at < now() - interval '1 year')
   OR (revoked_at IS NOT NULL AND revoked_at < now() - interval '1 year')
`

// GC: drop expired-or-revoked rows older than 1 year. Keeps audit
// trail for the typical compliance window.
func (q *Queries) CleanupExpiredGrants(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, cleanupExpiredGrants)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getActiveGrant = `-- name: GetActiveGrant :one
SELECT user_id, client_id, agent_id, scope, granted_at, expires_at, revoked_at FROM oauth_grants
WHERE user_id = $1
  AND client_id = $2
  AND agent_id = $3
  AND revoked_at IS NULL
  AND expires_at > now()
`

type GetActiveGrantParams struct {
	UserID   pgtype.UUID `json:"user_id"`
	ClientID string      `json:"client_id"`
	AgentID  pgtype.UUID `json:"agent_id"`
}

// Looks up an active (non-revoked, non-expired) grant. /authorize uses
// this to decide whether to skip the consent screen.
func (q *Queries) GetActiveGrant(ctx context.Context, arg GetActiveGrantParams) (OauthGrant, error) {
	row := q.db.QueryRow(ctx, getActiveGrant, arg.UserID, arg.ClientID, arg.AgentID)
	var i OauthGrant
	err := row.Scan(
		&i.UserID,
		&i.ClientID,
		&i.AgentID,
		&i.Scope,
		&i.GrantedAt,
		&i.ExpiresAt,
		&i.RevokedAt,
	)
	return i, err
}

const listGrantsForUser = `-- name: ListGrantsForUser :many
SELECT g.user_id, g.client_id, g.agent_id, g.scope, g.granted_at,
       g.expires_at, g.revoked_at,
       c.client_name,
       a.slug AS agent_slug, a.name AS agent_name
FROM oauth_grants g
JOIN oauth_clients c ON c.client_id = g.client_id
JOIN agents a ON a.id = g.agent_id
WHERE g.user_id = $1 AND g.revoked_at IS NULL
ORDER BY g.granted_at DESC
`

type ListGrantsForUserRow struct {
	UserID     pgtype.UUID        `json:"user_id"`
	ClientID   string             `json:"client_id"`
	AgentID    pgtype.UUID        `json:"agent_id"`
	Scope      string             `json:"scope"`
	GrantedAt  pgtype.Timestamptz `json:"granted_at"`
	ExpiresAt  pgtype.Timestamptz `json:"expires_at"`
	RevokedAt  pgtype.Timestamptz `json:"revoked_at"`
	ClientName string             `json:"client_name"`
	AgentSlug  string             `json:"agent_slug"`
	AgentName  string             `json:"agent_name"`
}

// Drives the "Connected apps" section in Settings. Joins clients +
// agents so the UI can show "Claude → weather (granted 5 days ago)".
func (q *Queries) ListGrantsForUser(ctx context.Context, userID pgtype.UUID) ([]ListGrantsForUserRow, error) {
	rows, err := q.db.Query(ctx, listGrantsForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListGrantsForUserRow{}
	for rows.Next() {
		var i ListGrantsForUserRow
		if err := rows.Scan(
			&i.UserID,
			&i.ClientID,
			&i.AgentID,
			&i.Scope,
			&i.GrantedAt,
			&i.ExpiresAt,
			&i.RevokedAt,
			&i.ClientName,
			&i.AgentSlug,
			&i.AgentName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeGrant = `-- name: RevokeGrant :execrows
UPDATE oauth_grants
SET revoked_at = now()
WHERE user_id = $1
  AND client_id = $2
  AND agent_id = $3
  AND revoked_at IS NULL
`

type RevokeGrantParams struct {
	UserID   pgtype.UUID `json:"user_id"`
	ClientID string      `json:"client_id"`
	AgentID  pgtype.UUID `json:"agent_id"`
}

// Marks a grant revoked. Caller also calls RevokeRefreshForGrant in
// the same handler so already-issued refresh tokens stop working.
func (q *Queries) RevokeGrant(ctx context.Context, arg RevokeGrantParams) (int64, error) {
	result, err := q.db.Exec(ctx, revokeGrant, arg.UserID, arg.ClientID, arg.AgentID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const upsertGrant = `-- name: UpsertGrant :exec
INSERT INTO oauth_grants (user_id, client_id, agent_id, scope, expires_at)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (user_id, client_id, agent_id) DO UPDATE SET
    scope      = EXCLUDED.scope,
    granted_at = now(),
    expires_at = EXCLUDED.expires_at,
    revoked_at = NULL
`

type UpsertGrantParams struct {
	UserID    pgtype.UUID        `json:"user_id"`
	ClientID  string             `json:"client_id"`
	AgentID   pgtype.UUID        `json:"agent_id"`
	Scope     string             `json:"scope"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

// Inserts or refreshes a consent record. Called from /oauth/consent
// on user approval. The 90-day window slides forward on every
// consent; revoked_at is cleared on re-grant (user explicitly
// approving wipes the revoke).
func (q *Queries) UpsertGrant(ctx context.Context, arg UpsertGrantParams) error {
	_, err := q.db.Exec(ctx, upsertGrant,
		arg.UserID,
		arg.ClientID,
		arg.AgentID,
		arg.Scope,
		arg.ExpiresAt,
	)
	return err
}
