// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: oauth_consent_transactions.sql

package dbq

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const cleanupExpiredOAuthConsentTransactions = `-- name: CleanupExpiredOAuthConsentTransactions :execrows
DELETE FROM oauth_consent_transactions WHERE expires_at <= now()
`

func (q *Queries) CleanupExpiredOAuthConsentTransactions(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, cleanupExpiredOAuthConsentTransactions)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const consumeOAuthConsentTransaction = `-- name: ConsumeOAuthConsentTransaction :one
DELETE FROM oauth_consent_transactions
WHERE transaction_id = $1
  AND binding_hash = $2
  AND user_id = $3
  AND client_id = $4
  AND agent_id = $5
  AND expires_at > now()
RETURNING transaction_id, binding_hash, user_id, client_id, agent_id, expires_at, created_at
`

type ConsumeOAuthConsentTransactionParams struct {
	TransactionID pgtype.UUID `json:"transaction_id"`
	BindingHash   []byte      `json:"binding_hash"`
	UserID        pgtype.UUID `json:"user_id"`
	ClientID      string      `json:"client_id"`
	AgentID       pgtype.UUID `json:"agent_id"`
}

// Approve and deny both call this inside their response transaction. Deleting
// by transaction ID and signed-token hash gives every consent screen one
// successful decision across all replicas.
func (q *Queries) ConsumeOAuthConsentTransaction(ctx context.Context, arg ConsumeOAuthConsentTransactionParams) (OauthConsentTransaction, error) {
	row := q.db.QueryRow(ctx, consumeOAuthConsentTransaction,
		arg.TransactionID,
		arg.BindingHash,
		arg.UserID,
		arg.ClientID,
		arg.AgentID,
	)
	var i OauthConsentTransaction
	err := row.Scan(
		&i.TransactionID,
		&i.BindingHash,
		&i.UserID,
		&i.ClientID,
		&i.AgentID,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const createOAuthConsentTransaction = `-- name: CreateOAuthConsentTransaction :exec
INSERT INTO oauth_consent_transactions (
    transaction_id, binding_hash, user_id, client_id, agent_id, expires_at
)
VALUES (
    $1, $2, $3, $4, $5, $6
)
`

type CreateOAuthConsentTransactionParams struct {
	TransactionID pgtype.UUID        `json:"transaction_id"`
	BindingHash   []byte             `json:"binding_hash"`
	UserID        pgtype.UUID        `json:"user_id"`
	ClientID      string             `json:"client_id"`
	AgentID       pgtype.UUID        `json:"agent_id"`
	ExpiresAt     pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreateOAuthConsentTransaction(ctx context.Context, arg CreateOAuthConsentTransactionParams) error {
	_, err := q.db.Exec(ctx, createOAuthConsentTransaction,
		arg.TransactionID,
		arg.BindingHash,
		arg.UserID,
		arg.ClientID,
		arg.AgentID,
		arg.ExpiresAt,
	)
	return err
}

const deleteOAuthConsentTransactionsForGrant = `-- name: DeleteOAuthConsentTransactionsForGrant :execrows
DELETE FROM oauth_consent_transactions
WHERE user_id = $1
  AND client_id = $2
  AND agent_id = $3
`

type DeleteOAuthConsentTransactionsForGrantParams struct {
	UserID   pgtype.UUID `json:"user_id"`
	ClientID string      `json:"client_id"`
	AgentID  pgtype.UUID `json:"agent_id"`
}

// Revocation invalidates consent screens issued before it commits, preventing
// a pending request from recreating the revoked grant.
func (q *Queries) DeleteOAuthConsentTransactionsForGrant(ctx context.Context, arg DeleteOAuthConsentTransactionsForGrantParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteOAuthConsentTransactionsForGrant, arg.UserID, arg.ClientID, arg.AgentID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const lockOAuthGrantLifecycle = `-- name: LockOAuthGrantLifecycle :exec
SELECT pg_advisory_xact_lock(hashtextextended(
    $1::text || ':' || $2::text || ':' || $3::text,
    134770336
))
`

type LockOAuthGrantLifecycleParams struct {
	UserID   string `json:"user_id"`
	ClientID string `json:"client_id"`
	AgentID  string `json:"agent_id"`
}

// Serialize consent creation, consent decisions, and revocation for one grant
// identity. Hash collisions only serialize unrelated grants.
func (q *Queries) LockOAuthGrantLifecycle(ctx context.Context, arg LockOAuthGrantLifecycleParams) error {
	_, err := q.db.Exec(ctx, lockOAuthGrantLifecycle, arg.UserID, arg.ClientID, arg.AgentID)
	return err
}
