// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: resource_grants.sql

package dbq

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getConnectionOwner = `-- name: GetConnectionOwner :one

SELECT owner_principal_id FROM connections WHERE id = $1
`

// Resource owner lookups for the capability check (owner holds all caps).
func (q *Queries) GetConnectionOwner(ctx context.Context, id pgtype.UUID) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, getConnectionOwner, id)
	var owner_principal_id pgtype.UUID
	err := row.Scan(&owner_principal_id)
	return owner_principal_id, err
}

const getExecEndpointOwner = `-- name: GetExecEndpointOwner :one
SELECT owner_principal_id FROM agent_exec_endpoints WHERE id = $1
`

func (q *Queries) GetExecEndpointOwner(ctx context.Context, id pgtype.UUID) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, getExecEndpointOwner, id)
	var owner_principal_id pgtype.UUID
	err := row.Scan(&owner_principal_id)
	return owner_principal_id, err
}

const getGitCredentialOwner = `-- name: GetGitCredentialOwner :one
SELECT user_id FROM git_credentials WHERE id = $1
`

func (q *Queries) GetGitCredentialOwner(ctx context.Context, id pgtype.UUID) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, getGitCredentialOwner, id)
	var user_id pgtype.UUID
	err := row.Scan(&user_id)
	return user_id, err
}

const getMCPServerOwner = `-- name: GetMCPServerOwner :one
SELECT owner_principal_id FROM agent_mcp_servers WHERE id = $1
`

func (q *Queries) GetMCPServerOwner(ctx context.Context, id pgtype.UUID) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, getMCPServerOwner, id)
	var owner_principal_id pgtype.UUID
	err := row.Scan(&owner_principal_id)
	return owner_principal_id, err
}

const listConnectionGrants = `-- name: ListConnectionGrants :many

SELECT id, grantee_id, capabilities FROM resource_grants WHERE connection_id = $1
`

type ListConnectionGrantsRow struct {
	ID           pgtype.UUID `json:"id"`
	GranteeID    pgtype.UUID `json:"grantee_id"`
	Capabilities []string    `json:"capabilities"`
}

// Stored capability grants are read by resource authorization. The owner holds
// view/bind/manage implicitly (see authz.HasResourceCapability).
func (q *Queries) ListConnectionGrants(ctx context.Context, connectionID pgtype.UUID) ([]ListConnectionGrantsRow, error) {
	rows, err := q.db.Query(ctx, listConnectionGrants, connectionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListConnectionGrantsRow{}
	for rows.Next() {
		var i ListConnectionGrantsRow
		if err := rows.Scan(&i.ID, &i.GranteeID, &i.Capabilities); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listExecEndpointGrants = `-- name: ListExecEndpointGrants :many
SELECT id, grantee_id, capabilities FROM resource_grants WHERE exec_endpoint_id = $1
`

type ListExecEndpointGrantsRow struct {
	ID           pgtype.UUID `json:"id"`
	GranteeID    pgtype.UUID `json:"grantee_id"`
	Capabilities []string    `json:"capabilities"`
}

func (q *Queries) ListExecEndpointGrants(ctx context.Context, execEndpointID pgtype.UUID) ([]ListExecEndpointGrantsRow, error) {
	rows, err := q.db.Query(ctx, listExecEndpointGrants, execEndpointID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListExecEndpointGrantsRow{}
	for rows.Next() {
		var i ListExecEndpointGrantsRow
		if err := rows.Scan(&i.ID, &i.GranteeID, &i.Capabilities); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGitCredentialGrants = `-- name: ListGitCredentialGrants :many
SELECT id, grantee_id, capabilities FROM resource_grants WHERE git_credential_id = $1
`

type ListGitCredentialGrantsRow struct {
	ID           pgtype.UUID `json:"id"`
	GranteeID    pgtype.UUID `json:"grantee_id"`
	Capabilities []string    `json:"capabilities"`
}

func (q *Queries) ListGitCredentialGrants(ctx context.Context, gitCredentialID pgtype.UUID) ([]ListGitCredentialGrantsRow, error) {
	rows, err := q.db.Query(ctx, listGitCredentialGrants, gitCredentialID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListGitCredentialGrantsRow{}
	for rows.Next() {
		var i ListGitCredentialGrantsRow
		if err := rows.Scan(&i.ID, &i.GranteeID, &i.Capabilities); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMCPServerGrants = `-- name: ListMCPServerGrants :many
SELECT id, grantee_id, capabilities FROM resource_grants WHERE mcp_server_id = $1
`

type ListMCPServerGrantsRow struct {
	ID           pgtype.UUID `json:"id"`
	GranteeID    pgtype.UUID `json:"grantee_id"`
	Capabilities []string    `json:"capabilities"`
}

func (q *Queries) ListMCPServerGrants(ctx context.Context, mcpServerID pgtype.UUID) ([]ListMCPServerGrantsRow, error) {
	rows, err := q.db.Query(ctx, listMCPServerGrants, mcpServerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListMCPServerGrantsRow{}
	for rows.Next() {
		var i ListMCPServerGrantsRow
		if err := rows.Scan(&i.ID, &i.GranteeID, &i.Capabilities); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockConnectionResource = `-- name: LockConnectionResource :exec
SELECT id FROM connections WHERE id = $1 FOR UPDATE
`

func (q *Queries) LockConnectionResource(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, lockConnectionResource, id)
	return err
}

const lockExecEndpointResource = `-- name: LockExecEndpointResource :exec
SELECT id FROM agent_exec_endpoints WHERE id = $1 FOR UPDATE
`

func (q *Queries) LockExecEndpointResource(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, lockExecEndpointResource, id)
	return err
}

const lockGitCredentialResource = `-- name: LockGitCredentialResource :exec
SELECT id FROM git_credentials WHERE id = $1 FOR UPDATE
`

func (q *Queries) LockGitCredentialResource(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, lockGitCredentialResource, id)
	return err
}

const lockMCPServerResource = `-- name: LockMCPServerResource :exec
SELECT id FROM agent_mcp_servers WHERE id = $1 FOR UPDATE
`

func (q *Queries) LockMCPServerResource(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, lockMCPServerResource, id)
	return err
}
