// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: resource_grants.sql

package dbq

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createConnectionGrant = `-- name: CreateConnectionGrant :one

INSERT INTO resource_grants (connection_id, grantee_id, capabilities)
VALUES ($1, $2, $3)
ON CONFLICT (connection_id, grantee_id) WHERE connection_id IS NOT NULL
DO UPDATE SET capabilities = EXCLUDED.capabilities
RETURNING id, connection_id, mcp_server_id, exec_endpoint_id, git_credential_id, grantee_id, capabilities, created_at
`

type CreateConnectionGrantParams struct {
	ConnectionID pgtype.UUID `json:"connection_id"`
	GranteeID    pgtype.UUID `json:"grantee_id"`
	Capabilities []string    `json:"capabilities"`
}

// Management-plane capability grants on user-owned resources. The owner holds
// view/bind/manage implicitly (see authz.HasResourceCapability); these rows
// extend capabilities to other principals (users or built-in role-groups).
func (q *Queries) CreateConnectionGrant(ctx context.Context, arg CreateConnectionGrantParams) (ResourceGrant, error) {
	row := q.db.QueryRow(ctx, createConnectionGrant, arg.ConnectionID, arg.GranteeID, arg.Capabilities)
	var i ResourceGrant
	err := row.Scan(
		&i.ID,
		&i.ConnectionID,
		&i.McpServerID,
		&i.ExecEndpointID,
		&i.GitCredentialID,
		&i.GranteeID,
		&i.Capabilities,
		&i.CreatedAt,
	)
	return i, err
}

const createExecEndpointGrant = `-- name: CreateExecEndpointGrant :one
INSERT INTO resource_grants (exec_endpoint_id, grantee_id, capabilities)
VALUES ($1, $2, $3)
ON CONFLICT (exec_endpoint_id, grantee_id) WHERE exec_endpoint_id IS NOT NULL
DO UPDATE SET capabilities = EXCLUDED.capabilities
RETURNING id, connection_id, mcp_server_id, exec_endpoint_id, git_credential_id, grantee_id, capabilities, created_at
`

type CreateExecEndpointGrantParams struct {
	ExecEndpointID pgtype.UUID `json:"exec_endpoint_id"`
	GranteeID      pgtype.UUID `json:"grantee_id"`
	Capabilities   []string    `json:"capabilities"`
}

func (q *Queries) CreateExecEndpointGrant(ctx context.Context, arg CreateExecEndpointGrantParams) (ResourceGrant, error) {
	row := q.db.QueryRow(ctx, createExecEndpointGrant, arg.ExecEndpointID, arg.GranteeID, arg.Capabilities)
	var i ResourceGrant
	err := row.Scan(
		&i.ID,
		&i.ConnectionID,
		&i.McpServerID,
		&i.ExecEndpointID,
		&i.GitCredentialID,
		&i.GranteeID,
		&i.Capabilities,
		&i.CreatedAt,
	)
	return i, err
}

const createGitCredentialGrant = `-- name: CreateGitCredentialGrant :one
INSERT INTO resource_grants (git_credential_id, grantee_id, capabilities)
VALUES ($1, $2, $3)
ON CONFLICT (git_credential_id, grantee_id) WHERE git_credential_id IS NOT NULL
DO UPDATE SET capabilities = EXCLUDED.capabilities
RETURNING id, connection_id, mcp_server_id, exec_endpoint_id, git_credential_id, grantee_id, capabilities, created_at
`

type CreateGitCredentialGrantParams struct {
	GitCredentialID pgtype.UUID `json:"git_credential_id"`
	GranteeID       pgtype.UUID `json:"grantee_id"`
	Capabilities    []string    `json:"capabilities"`
}

func (q *Queries) CreateGitCredentialGrant(ctx context.Context, arg CreateGitCredentialGrantParams) (ResourceGrant, error) {
	row := q.db.QueryRow(ctx, createGitCredentialGrant, arg.GitCredentialID, arg.GranteeID, arg.Capabilities)
	var i ResourceGrant
	err := row.Scan(
		&i.ID,
		&i.ConnectionID,
		&i.McpServerID,
		&i.ExecEndpointID,
		&i.GitCredentialID,
		&i.GranteeID,
		&i.Capabilities,
		&i.CreatedAt,
	)
	return i, err
}

const createMCPServerGrant = `-- name: CreateMCPServerGrant :one
INSERT INTO resource_grants (mcp_server_id, grantee_id, capabilities)
VALUES ($1, $2, $3)
ON CONFLICT (mcp_server_id, grantee_id) WHERE mcp_server_id IS NOT NULL
DO UPDATE SET capabilities = EXCLUDED.capabilities
RETURNING id, connection_id, mcp_server_id, exec_endpoint_id, git_credential_id, grantee_id, capabilities, created_at
`

type CreateMCPServerGrantParams struct {
	McpServerID  pgtype.UUID `json:"mcp_server_id"`
	GranteeID    pgtype.UUID `json:"grantee_id"`
	Capabilities []string    `json:"capabilities"`
}

func (q *Queries) CreateMCPServerGrant(ctx context.Context, arg CreateMCPServerGrantParams) (ResourceGrant, error) {
	row := q.db.QueryRow(ctx, createMCPServerGrant, arg.McpServerID, arg.GranteeID, arg.Capabilities)
	var i ResourceGrant
	err := row.Scan(
		&i.ID,
		&i.ConnectionID,
		&i.McpServerID,
		&i.ExecEndpointID,
		&i.GitCredentialID,
		&i.GranteeID,
		&i.Capabilities,
		&i.CreatedAt,
	)
	return i, err
}

const getConnectionOwner = `-- name: GetConnectionOwner :one

SELECT owner_principal_id FROM connections WHERE id = $1
`

// Resource owner lookups for the capability check (owner holds all caps).
func (q *Queries) GetConnectionOwner(ctx context.Context, id pgtype.UUID) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, getConnectionOwner, id)
	var owner_principal_id pgtype.UUID
	err := row.Scan(&owner_principal_id)
	return owner_principal_id, err
}

const getExecEndpointOwner = `-- name: GetExecEndpointOwner :one
SELECT owner_principal_id FROM agent_exec_endpoints WHERE id = $1
`

func (q *Queries) GetExecEndpointOwner(ctx context.Context, id pgtype.UUID) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, getExecEndpointOwner, id)
	var owner_principal_id pgtype.UUID
	err := row.Scan(&owner_principal_id)
	return owner_principal_id, err
}

const getGitCredentialOwner = `-- name: GetGitCredentialOwner :one
SELECT user_id FROM git_credentials WHERE id = $1
`

func (q *Queries) GetGitCredentialOwner(ctx context.Context, id pgtype.UUID) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, getGitCredentialOwner, id)
	var user_id pgtype.UUID
	err := row.Scan(&user_id)
	return user_id, err
}

const getMCPServerOwner = `-- name: GetMCPServerOwner :one
SELECT owner_principal_id FROM agent_mcp_servers WHERE id = $1
`

func (q *Queries) GetMCPServerOwner(ctx context.Context, id pgtype.UUID) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, getMCPServerOwner, id)
	var owner_principal_id pgtype.UUID
	err := row.Scan(&owner_principal_id)
	return owner_principal_id, err
}

const listConnectionGrants = `-- name: ListConnectionGrants :many

SELECT grantee_id, capabilities FROM resource_grants WHERE connection_id = $1
`

type ListConnectionGrantsRow struct {
	GranteeID    pgtype.UUID `json:"grantee_id"`
	Capabilities []string    `json:"capabilities"`
}

// Per-resource grant lists, used both to render "who can this resource is
// shared with" and to evaluate HasResourceCapability for a caller.
func (q *Queries) ListConnectionGrants(ctx context.Context, connectionID pgtype.UUID) ([]ListConnectionGrantsRow, error) {
	rows, err := q.db.Query(ctx, listConnectionGrants, connectionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListConnectionGrantsRow{}
	for rows.Next() {
		var i ListConnectionGrantsRow
		if err := rows.Scan(&i.GranteeID, &i.Capabilities); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listExecEndpointGrants = `-- name: ListExecEndpointGrants :many
SELECT grantee_id, capabilities FROM resource_grants WHERE exec_endpoint_id = $1
`

type ListExecEndpointGrantsRow struct {
	GranteeID    pgtype.UUID `json:"grantee_id"`
	Capabilities []string    `json:"capabilities"`
}

func (q *Queries) ListExecEndpointGrants(ctx context.Context, execEndpointID pgtype.UUID) ([]ListExecEndpointGrantsRow, error) {
	rows, err := q.db.Query(ctx, listExecEndpointGrants, execEndpointID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListExecEndpointGrantsRow{}
	for rows.Next() {
		var i ListExecEndpointGrantsRow
		if err := rows.Scan(&i.GranteeID, &i.Capabilities); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGitCredentialGrants = `-- name: ListGitCredentialGrants :many
SELECT grantee_id, capabilities FROM resource_grants WHERE git_credential_id = $1
`

type ListGitCredentialGrantsRow struct {
	GranteeID    pgtype.UUID `json:"grantee_id"`
	Capabilities []string    `json:"capabilities"`
}

func (q *Queries) ListGitCredentialGrants(ctx context.Context, gitCredentialID pgtype.UUID) ([]ListGitCredentialGrantsRow, error) {
	rows, err := q.db.Query(ctx, listGitCredentialGrants, gitCredentialID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListGitCredentialGrantsRow{}
	for rows.Next() {
		var i ListGitCredentialGrantsRow
		if err := rows.Scan(&i.GranteeID, &i.Capabilities); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMCPServerGrants = `-- name: ListMCPServerGrants :many
SELECT grantee_id, capabilities FROM resource_grants WHERE mcp_server_id = $1
`

type ListMCPServerGrantsRow struct {
	GranteeID    pgtype.UUID `json:"grantee_id"`
	Capabilities []string    `json:"capabilities"`
}

func (q *Queries) ListMCPServerGrants(ctx context.Context, mcpServerID pgtype.UUID) ([]ListMCPServerGrantsRow, error) {
	rows, err := q.db.Query(ctx, listMCPServerGrants, mcpServerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListMCPServerGrantsRow{}
	for rows.Next() {
		var i ListMCPServerGrantsRow
		if err := rows.Scan(&i.GranteeID, &i.Capabilities); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeResourceGrant = `-- name: RevokeResourceGrant :exec
DELETE FROM resource_grants WHERE id = $1
`

func (q *Queries) RevokeResourceGrant(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, revokeResourceGrant, id)
	return err
}
