// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: storage_zones.sql

package dbq

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteStorageZonesByAgentExcept = `-- name: DeleteStorageZonesByAgentExcept :exec
DELETE FROM agent_storage_zones
WHERE agent_id = $1 AND slug != ALL($2::text[])
`

type DeleteStorageZonesByAgentExceptParams struct {
	AgentID pgtype.UUID `json:"agent_id"`
	Slugs   []string    `json:"slugs"`
}

func (q *Queries) DeleteStorageZonesByAgentExcept(ctx context.Context, arg DeleteStorageZonesByAgentExceptParams) error {
	_, err := q.db.Exec(ctx, deleteStorageZonesByAgentExcept, arg.AgentID, arg.Slugs)
	return err
}

const getStorageZone = `-- name: GetStorageZone :one
SELECT id, agent_id, slug, read_access, write_access, description, created_at, updated_at FROM agent_storage_zones WHERE agent_id = $1 AND slug = $2
`

type GetStorageZoneParams struct {
	AgentID pgtype.UUID `json:"agent_id"`
	Slug    string      `json:"slug"`
}

func (q *Queries) GetStorageZone(ctx context.Context, arg GetStorageZoneParams) (AgentStorageZone, error) {
	row := q.db.QueryRow(ctx, getStorageZone, arg.AgentID, arg.Slug)
	var i AgentStorageZone
	err := row.Scan(
		&i.ID,
		&i.AgentID,
		&i.Slug,
		&i.ReadAccess,
		&i.WriteAccess,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listStorageZonesByAgent = `-- name: ListStorageZonesByAgent :many
SELECT id, agent_id, slug, read_access, write_access, description, created_at, updated_at FROM agent_storage_zones WHERE agent_id = $1
`

func (q *Queries) ListStorageZonesByAgent(ctx context.Context, agentID pgtype.UUID) ([]AgentStorageZone, error) {
	rows, err := q.db.Query(ctx, listStorageZonesByAgent, agentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AgentStorageZone{}
	for rows.Next() {
		var i AgentStorageZone
		if err := rows.Scan(
			&i.ID,
			&i.AgentID,
			&i.Slug,
			&i.ReadAccess,
			&i.WriteAccess,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertStorageZone = `-- name: UpsertStorageZone :exec
INSERT INTO agent_storage_zones (agent_id, slug, read_access, write_access, description)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (agent_id, slug) DO UPDATE SET
    read_access = EXCLUDED.read_access,
    write_access = EXCLUDED.write_access,
    description = EXCLUDED.description,
    updated_at = now()
`

type UpsertStorageZoneParams struct {
	AgentID     pgtype.UUID `json:"agent_id"`
	Slug        string      `json:"slug"`
	ReadAccess  string      `json:"read_access"`
	WriteAccess string      `json:"write_access"`
	Description string      `json:"description"`
}

func (q *Queries) UpsertStorageZone(ctx context.Context, arg UpsertStorageZoneParams) error {
	_, err := q.db.Exec(ctx, upsertStorageZone,
		arg.AgentID,
		arg.Slug,
		arg.ReadAccess,
		arg.WriteAccess,
		arg.Description,
	)
	return err
}
