// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: system_agent.sql

package dbq

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const appendSystemMessage = `-- name: AppendSystemMessage :one
INSERT INTO system_messages (
    conversation_id, role, source, content, parts, tokens_in, tokens_out, cost_estimate
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8
)
RETURNING id, seq, conversation_id, role, source, content, parts, tokens_in, tokens_out, cost_estimate, created_at
`

type AppendSystemMessageParams struct {
	ConversationID pgtype.UUID    `json:"conversation_id"`
	Role           string         `json:"role"`
	Source         string         `json:"source"`
	Content        string         `json:"content"`
	Parts          []byte         `json:"parts"`
	TokensIn       int32          `json:"tokens_in"`
	TokensOut      int32          `json:"tokens_out"`
	CostEstimate   pgtype.Numeric `json:"cost_estimate"`
}

// Mirrors agent_messages' (content, parts) split: content is the
// plain-text display string; parts carries the goai multi-part Content
// shape only when there are tool calls / results / images / etc.
// (left NULL for plain text answers). source distinguishes operator
// prompts ("") from system-injected events ("upgrade", "error", ...).
func (q *Queries) AppendSystemMessage(ctx context.Context, arg AppendSystemMessageParams) (SystemMessage, error) {
	row := q.db.QueryRow(ctx, appendSystemMessage,
		arg.ConversationID,
		arg.Role,
		arg.Source,
		arg.Content,
		arg.Parts,
		arg.TokensIn,
		arg.TokensOut,
		arg.CostEstimate,
	)
	var i SystemMessage
	err := row.Scan(
		&i.ID,
		&i.Seq,
		&i.ConversationID,
		&i.Role,
		&i.Source,
		&i.Content,
		&i.Parts,
		&i.TokensIn,
		&i.TokensOut,
		&i.CostEstimate,
		&i.CreatedAt,
	)
	return i, err
}

const clearSystemConversationCheckpoint = `-- name: ClearSystemConversationCheckpoint :exec
UPDATE system_conversations
SET status = 'active',
    checkpoint = NULL,
    updated_at = now()
WHERE id = $1
`

func (q *Queries) ClearSystemConversationCheckpoint(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, clearSystemConversationCheckpoint, id)
	return err
}

const createSystemConversation = `-- name: CreateSystemConversation :one

INSERT INTO system_conversations (user_id, title)
VALUES ($1, $2)
RETURNING id, user_id, title, status, checkpoint, context_checkpoint_message_id, settings, created_at, updated_at, source, bridge_id, external_id
`

type CreateSystemConversationParams struct {
	UserID pgtype.UUID `json:"user_id"`
	Title  string      `json:"title"`
}

// system_agent: per-user chat conversations + messages + lightweight
// runs + audit log for the in-airlock system agent. Schema lives in
// migrations/002_a2a.sql.
func (q *Queries) CreateSystemConversation(ctx context.Context, arg CreateSystemConversationParams) (SystemConversation, error) {
	row := q.db.QueryRow(ctx, createSystemConversation, arg.UserID, arg.Title)
	var i SystemConversation
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Status,
		&i.Checkpoint,
		&i.ContextCheckpointMessageID,
		&i.Settings,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Source,
		&i.BridgeID,
		&i.ExternalID,
	)
	return i, err
}

const createSystemRun = `-- name: CreateSystemRun :one
INSERT INTO system_runs (conversation_id, user_id)
VALUES ($1, $2)
RETURNING id, conversation_id, user_id, status, error_message, started_at, finished_at
`

type CreateSystemRunParams struct {
	ConversationID pgtype.UUID `json:"conversation_id"`
	UserID         pgtype.UUID `json:"user_id"`
}

// Inserts a fresh run row at the start of a turn. The id becomes the
// run_id every WS event carries so the frontend can group
// text_delta/tool_call/tool_result events under one bubble — same
// contract as agent chat's runs.id.
func (q *Queries) CreateSystemRun(ctx context.Context, arg CreateSystemRunParams) (SystemRun, error) {
	row := q.db.QueryRow(ctx, createSystemRun, arg.ConversationID, arg.UserID)
	var i SystemRun
	err := row.Scan(
		&i.ID,
		&i.ConversationID,
		&i.UserID,
		&i.Status,
		&i.ErrorMessage,
		&i.StartedAt,
		&i.FinishedAt,
	)
	return i, err
}

const deleteSystemConversation = `-- name: DeleteSystemConversation :exec
DELETE FROM system_conversations WHERE id = $1 AND user_id = $2
`

type DeleteSystemConversationParams struct {
	ID     pgtype.UUID `json:"id"`
	UserID pgtype.UUID `json:"user_id"`
}

func (q *Queries) DeleteSystemConversation(ctx context.Context, arg DeleteSystemConversationParams) error {
	_, err := q.db.Exec(ctx, deleteSystemConversation, arg.ID, arg.UserID)
	return err
}

const ensureSystemConversationForBridge = `-- name: EnsureSystemConversationForBridge :one
INSERT INTO system_conversations (user_id, bridge_id, source, title, external_id)
VALUES ($1, $2, 'bridge', $3, $4)
ON CONFLICT (user_id, bridge_id) WHERE bridge_id IS NOT NULL
DO UPDATE SET external_id = EXCLUDED.external_id
RETURNING id, user_id, title, status, checkpoint, context_checkpoint_message_id, settings, created_at, updated_at, source, bridge_id, external_id
`

type EnsureSystemConversationForBridgeParams struct {
	UserID     pgtype.UUID `json:"user_id"`
	BridgeID   pgtype.UUID `json:"bridge_id"`
	Title      string      `json:"title"`
	ExternalID pgtype.Text `json:"external_id"`
}

// Upsert one sticky thread per (user, bridge) on the partial unique
// index (user_id, bridge_id) WHERE bridge_id IS NOT NULL — every system
// bridge funnels that user's inbound DMs into the same row. The first
// INSERT for a pair returns the new row; subsequent calls hit the
// conflict and return the existing one, refreshing external_id (the
// platform chat id) so a server-initiated follow-up — e.g. a build /
// upgrade completion auto-resume, which has no live inbound update to
// read the chat id from — can deliver back to the right chat.
func (q *Queries) EnsureSystemConversationForBridge(ctx context.Context, arg EnsureSystemConversationForBridgeParams) (SystemConversation, error) {
	row := q.db.QueryRow(ctx, ensureSystemConversationForBridge,
		arg.UserID,
		arg.BridgeID,
		arg.Title,
		arg.ExternalID,
	)
	var i SystemConversation
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Status,
		&i.Checkpoint,
		&i.ContextCheckpointMessageID,
		&i.Settings,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Source,
		&i.BridgeID,
		&i.ExternalID,
	)
	return i, err
}

const getLatestRunningSystemRun = `-- name: GetLatestRunningSystemRun :one
SELECT id FROM system_runs
WHERE conversation_id = $1
  AND status IN ('running', 'suspended')
ORDER BY started_at DESC
LIMIT 1
`

// /cancel target: the most recent run on this conversation that hasn't
// terminated yet. Both 'running' and 'suspended' are cancellable —
// suspended runs that the user cancels via /cancel rather than via the
// confirmation dialog still need to be torn down.
func (q *Queries) GetLatestRunningSystemRun(ctx context.Context, conversationID pgtype.UUID) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, getLatestRunningSystemRun, conversationID)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const getLatestSuspendedSystemRun = `-- name: GetLatestSuspendedSystemRun :one
SELECT id FROM system_runs
WHERE conversation_id = $1
  AND status = 'suspended'
ORDER BY started_at DESC
LIMIT 1
`

// /clear target: a suspended run on this conversation belongs to the
// pending-confirmation UI; once the context is cleared the dialog is
// meaningless, so we cancel the run alongside the checkpoint advance.
func (q *Queries) GetLatestSuspendedSystemRun(ctx context.Context, conversationID pgtype.UUID) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, getLatestSuspendedSystemRun, conversationID)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const getSystemConversationByID = `-- name: GetSystemConversationByID :one
SELECT id, user_id, title, status, checkpoint, context_checkpoint_message_id, settings, created_at, updated_at, source, bridge_id, external_id FROM system_conversations WHERE id = $1
`

func (q *Queries) GetSystemConversationByID(ctx context.Context, id pgtype.UUID) (SystemConversation, error) {
	row := q.db.QueryRow(ctx, getSystemConversationByID, id)
	var i SystemConversation
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Status,
		&i.Checkpoint,
		&i.ContextCheckpointMessageID,
		&i.Settings,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Source,
		&i.BridgeID,
		&i.ExternalID,
	)
	return i, err
}

const getSystemRunByID = `-- name: GetSystemRunByID :one
SELECT id, conversation_id, user_id, status, error_message, started_at, finished_at FROM system_runs WHERE id = $1
`

func (q *Queries) GetSystemRunByID(ctx context.Context, id pgtype.UUID) (SystemRun, error) {
	row := q.db.QueryRow(ctx, getSystemRunByID, id)
	var i SystemRun
	err := row.Scan(
		&i.ID,
		&i.ConversationID,
		&i.UserID,
		&i.Status,
		&i.ErrorMessage,
		&i.StartedAt,
		&i.FinishedAt,
	)
	return i, err
}

const insertSystemAuditPending = `-- name: InsertSystemAuditPending :one
INSERT INTO system_audit (
    user_id, conversation_id, tool, args, result_summary, ok
) VALUES (
    $1, $2, $3, $4, 'pending', false
)
RETURNING id
`

type InsertSystemAuditPendingParams struct {
	UserID         pgtype.UUID `json:"user_id"`
	ConversationID pgtype.UUID `json:"conversation_id"`
	Tool           string      `json:"tool"`
	Args           []byte      `json:"args"`
}

// Append an audit row BEFORE invoking the tool body. ok defaults to
// false / result_summary='pending' so a panic mid-tool leaves a
// visible trace. The follow-up UpdateSystemAudit flips ok + writes
// the real summary on completion.
func (q *Queries) InsertSystemAuditPending(ctx context.Context, arg InsertSystemAuditPendingParams) (int64, error) {
	row := q.db.QueryRow(ctx, insertSystemAuditPending,
		arg.UserID,
		arg.ConversationID,
		arg.Tool,
		arg.Args,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const listSystemConversationsByUser = `-- name: ListSystemConversationsByUser :many
SELECT id, user_id, title, status, checkpoint, context_checkpoint_message_id, settings, created_at, updated_at, source, bridge_id, external_id FROM system_conversations
WHERE user_id = $1 AND source = 'web'
ORDER BY updated_at DESC
`

// Web-UI sidebar. Bridge-routed threads (source='bridge') are
// intentionally hidden — they live on Telegram, the operator can't
// meaningfully resume them from the web, and surfacing them would
// leak bot-driven chat into the operator's conversation list.
// Ordered by updated_at DESC so the most-recently-active web
// conversation is first. Covered by (user_id, updated_at DESC).
func (q *Queries) ListSystemConversationsByUser(ctx context.Context, userID pgtype.UUID) ([]SystemConversation, error) {
	rows, err := q.db.Query(ctx, listSystemConversationsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SystemConversation{}
	for rows.Next() {
		var i SystemConversation
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Title,
			&i.Status,
			&i.Checkpoint,
			&i.ContextCheckpointMessageID,
			&i.Settings,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Source,
			&i.BridgeID,
			&i.ExternalID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSystemMessagesByConversation = `-- name: ListSystemMessagesByConversation :many
SELECT m.id, m.seq, m.conversation_id, m.role, m.source, m.content, m.parts, m.tokens_in, m.tokens_out, m.cost_estimate, m.created_at FROM system_messages m
JOIN system_conversations c ON c.id = m.conversation_id
WHERE m.conversation_id = $1
  AND (m.parts -> 0 ->> 'type') IS DISTINCT FROM 'checkpoint'
  AND (
    c.context_checkpoint_message_id IS NULL
    OR m.seq >= (
      SELECT seq FROM system_messages WHERE id = c.context_checkpoint_message_id
    )
  )
ORDER BY m.seq ASC
`

// Used by sol.SessionStore.Load: returns post-checkpoint messages in
// canonical seq order, skipping checkpoint-marker rows (UI-only, never
// sent to the LLM). When no checkpoint is set, returns the full
// conversation history.
func (q *Queries) ListSystemMessagesByConversation(ctx context.Context, conversationID pgtype.UUID) ([]SystemMessage, error) {
	rows, err := q.db.Query(ctx, listSystemMessagesByConversation, conversationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SystemMessage{}
	for rows.Next() {
		var i SystemMessage
		if err := rows.Scan(
			&i.ID,
			&i.Seq,
			&i.ConversationID,
			&i.Role,
			&i.Source,
			&i.Content,
			&i.Parts,
			&i.TokensIn,
			&i.TokensOut,
			&i.CostEstimate,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSystemMessagesByConversationAfter = `-- name: ListSystemMessagesByConversationAfter :many
SELECT id, seq, conversation_id, role, source, content, parts, tokens_in, tokens_out, cost_estimate, created_at FROM system_messages
WHERE conversation_id = $1 AND seq > $2
ORDER BY seq ASC
LIMIT $3
`

type ListSystemMessagesByConversationAfterParams struct {
	ConversationID pgtype.UUID `json:"conversation_id"`
	AfterSeq       int64       `json:"after_seq"`
	MaxRows        int32       `json:"max_rows"`
}

// Pagination cursor for the UI: rows with seq > the client's last
// known seq, capped at @max_rows. Used to backfill on reconnect.
func (q *Queries) ListSystemMessagesByConversationAfter(ctx context.Context, arg ListSystemMessagesByConversationAfterParams) ([]SystemMessage, error) {
	rows, err := q.db.Query(ctx, listSystemMessagesByConversationAfter, arg.ConversationID, arg.AfterSeq, arg.MaxRows)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SystemMessage{}
	for rows.Next() {
		var i SystemMessage
		if err := rows.Scan(
			&i.ID,
			&i.Seq,
			&i.ConversationID,
			&i.Role,
			&i.Source,
			&i.Content,
			&i.Parts,
			&i.TokensIn,
			&i.TokensOut,
			&i.CostEstimate,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSystemMessagesByConversationAll = `-- name: ListSystemMessagesByConversationAll :many
SELECT id, seq, conversation_id, role, source, content, parts, tokens_in, tokens_out, cost_estimate, created_at FROM system_messages
WHERE conversation_id = $1
ORDER BY seq ASC
`

// Returns every row including pre-checkpoint history + checkpoint
// markers. Used by the UI message list (so the operator still sees
// everything that happened in the conversation), separate from the LLM
// context load above.
func (q *Queries) ListSystemMessagesByConversationAll(ctx context.Context, conversationID pgtype.UUID) ([]SystemMessage, error) {
	rows, err := q.db.Query(ctx, listSystemMessagesByConversationAll, conversationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SystemMessage{}
	for rows.Next() {
		var i SystemMessage
		if err := rows.Scan(
			&i.ID,
			&i.Seq,
			&i.ConversationID,
			&i.Role,
			&i.Source,
			&i.Content,
			&i.Parts,
			&i.TokensIn,
			&i.TokensOut,
			&i.CostEstimate,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSystemRunsByUser = `-- name: ListSystemRunsByUser :many
SELECT r.id, r.conversation_id, r.user_id, r.status, r.error_message,
       r.started_at, r.finished_at, c.title AS conversation_title
FROM system_runs r
JOIN system_conversations c ON c.id = r.conversation_id
WHERE r.user_id = $1
  AND ($2::timestamptz IS NULL OR r.started_at < $2)
ORDER BY r.started_at DESC
LIMIT $3
`

type ListSystemRunsByUserParams struct {
	UserID pgtype.UUID        `json:"user_id"`
	Cursor pgtype.Timestamptz `json:"cursor"`
	Lim    int32              `json:"lim"`
}

type ListSystemRunsByUserRow struct {
	ID                pgtype.UUID        `json:"id"`
	ConversationID    pgtype.UUID        `json:"conversation_id"`
	UserID            pgtype.UUID        `json:"user_id"`
	Status            string             `json:"status"`
	ErrorMessage      string             `json:"error_message"`
	StartedAt         pgtype.Timestamptz `json:"started_at"`
	FinishedAt        pgtype.Timestamptz `json:"finished_at"`
	ConversationTitle string             `json:"conversation_title"`
}

// Caller's runs across all their conversations, paginated by started_at.
// JOINs system_conversations for the conversation title so the operator's
// activity view doesn't need a second per-row fetch.
func (q *Queries) ListSystemRunsByUser(ctx context.Context, arg ListSystemRunsByUserParams) ([]ListSystemRunsByUserRow, error) {
	rows, err := q.db.Query(ctx, listSystemRunsByUser, arg.UserID, arg.Cursor, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSystemRunsByUserRow{}
	for rows.Next() {
		var i ListSystemRunsByUserRow
		if err := rows.Scan(
			&i.ID,
			&i.ConversationID,
			&i.UserID,
			&i.Status,
			&i.ErrorMessage,
			&i.StartedAt,
			&i.FinishedAt,
			&i.ConversationTitle,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const renameSystemConversation = `-- name: RenameSystemConversation :exec
UPDATE system_conversations
SET title = $1, updated_at = now()
WHERE id = $2 AND user_id = $3
`

type RenameSystemConversationParams struct {
	Title  string      `json:"title"`
	ID     pgtype.UUID `json:"id"`
	UserID pgtype.UUID `json:"user_id"`
}

func (q *Queries) RenameSystemConversation(ctx context.Context, arg RenameSystemConversationParams) error {
	_, err := q.db.Exec(ctx, renameSystemConversation, arg.Title, arg.ID, arg.UserID)
	return err
}

const setSystemConversationCheckpoint = `-- name: SetSystemConversationCheckpoint :exec
UPDATE system_conversations
SET status = 'awaiting_confirmation',
    checkpoint = $1,
    updated_at = now()
WHERE id = $2
`

type SetSystemConversationCheckpointParams struct {
	Checkpoint []byte      `json:"checkpoint"`
	ID         pgtype.UUID `json:"id"`
}

// Stash the sol SuspensionContext (pending tool calls + completed
// results) and flip the conversation to 'awaiting_confirmation'. The
// resume path reads checkpoint back, executes the gated tools per the
// approve/deny flag, and calls ClearSystemConversationCheckpoint.
func (q *Queries) SetSystemConversationCheckpoint(ctx context.Context, arg SetSystemConversationCheckpointParams) error {
	_, err := q.db.Exec(ctx, setSystemConversationCheckpoint, arg.Checkpoint, arg.ID)
	return err
}

const setSystemConversationContextCheckpoint = `-- name: SetSystemConversationContextCheckpoint :exec
UPDATE system_conversations
SET context_checkpoint_message_id = $1,
    updated_at = now()
WHERE id = $2
`

type SetSystemConversationContextCheckpointParams struct {
	CheckpointMessageID pgtype.UUID `json:"checkpoint_message_id"`
	ID                  pgtype.UUID `json:"id"`
}

// Compaction pointer: advances the context window so subsequent
// Loads filter to messages with seq >= the checkpoint message's seq.
// See ListSystemMessagesByConversation.
func (q *Queries) SetSystemConversationContextCheckpoint(ctx context.Context, arg SetSystemConversationContextCheckpointParams) error {
	_, err := q.db.Exec(ctx, setSystemConversationContextCheckpoint, arg.CheckpointMessageID, arg.ID)
	return err
}

const touchSystemConversation = `-- name: TouchSystemConversation :exec
UPDATE system_conversations SET updated_at = now() WHERE id = $1
`

// Bumps updated_at after a new message lands so list order reflects
// recency. Separate from rename so a chat turn doesn't accidentally
// rewrite the title.
func (q *Queries) TouchSystemConversation(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, touchSystemConversation, id)
	return err
}

const updateSystemAuditResult = `-- name: UpdateSystemAuditResult :exec
UPDATE system_audit
SET result_summary = $1, ok = $2
WHERE id = $3
`

type UpdateSystemAuditResultParams struct {
	ResultSummary string `json:"result_summary"`
	Ok            bool   `json:"ok"`
	ID            int64  `json:"id"`
}

func (q *Queries) UpdateSystemAuditResult(ctx context.Context, arg UpdateSystemAuditResultParams) error {
	_, err := q.db.Exec(ctx, updateSystemAuditResult, arg.ResultSummary, arg.Ok, arg.ID)
	return err
}

const updateSystemConversationSettings = `-- name: UpdateSystemConversationSettings :exec
UPDATE system_conversations
SET settings = settings || $1::jsonb,
    updated_at = now()
WHERE id = $2
`

type UpdateSystemConversationSettingsParams struct {
	Patch []byte      `json:"patch"`
	ID    pgtype.UUID `json:"id"`
}

// JSONB shallow merge: caller passes a patch with only the keys to
// overwrite; existing keys not in the patch survive. Used by /echo to
// flip the echo setting without touching anything else.
func (q *Queries) UpdateSystemConversationSettings(ctx context.Context, arg UpdateSystemConversationSettingsParams) error {
	_, err := q.db.Exec(ctx, updateSystemConversationSettings, arg.Patch, arg.ID)
	return err
}

const updateSystemRunStatus = `-- name: UpdateSystemRunStatus :exec
UPDATE system_runs
SET status = $1,
    error_message = $2,
    finished_at = CASE WHEN $1 IN ('complete', 'error', 'cancelled') THEN now() ELSE finished_at END
WHERE id = $3
`

type UpdateSystemRunStatusParams struct {
	Status       string      `json:"status"`
	ErrorMessage string      `json:"error_message"`
	ID           pgtype.UUID `json:"id"`
}

func (q *Queries) UpdateSystemRunStatus(ctx context.Context, arg UpdateSystemRunStatusParams) error {
	_, err := q.db.Exec(ctx, updateSystemRunStatus, arg.Status, arg.ErrorMessage, arg.ID)
	return err
}
