// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: user_sessions.sql

package dbq

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const cleanupExpiredUserSessions = `-- name: CleanupExpiredUserSessions :execrows
DELETE FROM user_sessions
WHERE expires_at < now() - interval '30 days'
   OR (revoked_at IS NOT NULL AND revoked_at < now() - interval '30 days')
`

func (q *Queries) CleanupExpiredUserSessions(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, cleanupExpiredUserSessions)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const createUserSession = `-- name: CreateUserSession :one
INSERT INTO user_sessions (
    user_id, kind, client_name, device_name, refresh_token_hash, expires_at
)
VALUES (
    $1, $2, $3, $4, $5, $6
)
RETURNING id, user_id, kind, client_name, device_name, refresh_token_hash, created_at, last_used_at, expires_at, revoked_at
`

type CreateUserSessionParams struct {
	UserID           pgtype.UUID        `json:"user_id"`
	Kind             string             `json:"kind"`
	ClientName       string             `json:"client_name"`
	DeviceName       string             `json:"device_name"`
	RefreshTokenHash []byte             `json:"refresh_token_hash"`
	ExpiresAt        pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreateUserSession(ctx context.Context, arg CreateUserSessionParams) (UserSession, error) {
	row := q.db.QueryRow(ctx, createUserSession,
		arg.UserID,
		arg.Kind,
		arg.ClientName,
		arg.DeviceName,
		arg.RefreshTokenHash,
		arg.ExpiresAt,
	)
	var i UserSession
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Kind,
		&i.ClientName,
		&i.DeviceName,
		&i.RefreshTokenHash,
		&i.CreatedAt,
		&i.LastUsedAt,
		&i.ExpiresAt,
		&i.RevokedAt,
	)
	return i, err
}

const getActiveUserSessionByRefreshHash = `-- name: GetActiveUserSessionByRefreshHash :one
SELECT id, user_id, kind, client_name, device_name, refresh_token_hash, created_at, last_used_at, expires_at, revoked_at FROM user_sessions
WHERE refresh_token_hash = $1
  AND revoked_at IS NULL
  AND expires_at > now()
`

func (q *Queries) GetActiveUserSessionByRefreshHash(ctx context.Context, refreshTokenHash []byte) (UserSession, error) {
	row := q.db.QueryRow(ctx, getActiveUserSessionByRefreshHash, refreshTokenHash)
	var i UserSession
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Kind,
		&i.ClientName,
		&i.DeviceName,
		&i.RefreshTokenHash,
		&i.CreatedAt,
		&i.LastUsedAt,
		&i.ExpiresAt,
		&i.RevokedAt,
	)
	return i, err
}

const listUserSessionsByUser = `-- name: ListUserSessionsByUser :many
SELECT id, user_id, kind, client_name, device_name, refresh_token_hash, created_at, last_used_at, expires_at, revoked_at FROM user_sessions
WHERE user_id = $1
  AND revoked_at IS NULL
  AND expires_at > now()
ORDER BY COALESCE(last_used_at, created_at) DESC
`

func (q *Queries) ListUserSessionsByUser(ctx context.Context, userID pgtype.UUID) ([]UserSession, error) {
	rows, err := q.db.Query(ctx, listUserSessionsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []UserSession{}
	for rows.Next() {
		var i UserSession
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Kind,
			&i.ClientName,
			&i.DeviceName,
			&i.RefreshTokenHash,
			&i.CreatedAt,
			&i.LastUsedAt,
			&i.ExpiresAt,
			&i.RevokedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeUserSessionByID = `-- name: RevokeUserSessionByID :execrows
UPDATE user_sessions
SET revoked_at = now()
WHERE id = $1
  AND user_id = $2
  AND revoked_at IS NULL
`

type RevokeUserSessionByIDParams struct {
	ID     pgtype.UUID `json:"id"`
	UserID pgtype.UUID `json:"user_id"`
}

func (q *Queries) RevokeUserSessionByID(ctx context.Context, arg RevokeUserSessionByIDParams) (int64, error) {
	result, err := q.db.Exec(ctx, revokeUserSessionByID, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const revokeUserSessionByRefreshHash = `-- name: RevokeUserSessionByRefreshHash :execrows
UPDATE user_sessions
SET revoked_at = now()
WHERE refresh_token_hash = $1
  AND revoked_at IS NULL
`

func (q *Queries) RevokeUserSessionByRefreshHash(ctx context.Context, refreshTokenHash []byte) (int64, error) {
	result, err := q.db.Exec(ctx, revokeUserSessionByRefreshHash, refreshTokenHash)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const touchUserSession = `-- name: TouchUserSession :exec
UPDATE user_sessions
SET last_used_at = now()
WHERE id = $1
`

func (q *Queries) TouchUserSession(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, touchUserSession, id)
	return err
}
